### ISSUE TITLE
[FEATURE REQUEST] Ability to schedule starting a print at a given date/time

### ISSUE THREAD

**Issue by josedpedroso** [luc-github/ESP8266#1001]
It'd be nice to be able to schedule printing a file already in the card (or sending a custom g-code command to the printer) at a specified date and time. Not sure how feasible that is, especially if ESP3D doesn't already have a global date/time, but as an alternative, being able to schedule the print or command to happen after some minutes, days, or hours, would still be useful. It'd also be nice to be able to set the schedule as one-shot or repeating.

**Comment by luc-github** [comment]
what is the purpose of scheduling a job ? what is the user case?

**Comment by josedpedroso** [comment]
My printer is a bit noisy and I have it at my parents', so I'd like to
avoid running it at night. However, I'm often not at home in the morning to
start a job, so I may not be able to start long prints until I actually
spend the night there. Scheduling would solve this for me, without having
to setup remote access and without having to get up in the morning.

**Comment by luc-github** [comment]
so what you need is just starting time and not a repeating 
In that case it is safer to use https://fr.aliexpress.com/item/1005004251720806.html because if your esp does not have internet and time may not be set it won't work
Just put you gcode file as init command in ESP3D or even in Printer Firmware init file

**Comment by josedpedroso** [comment]
As I said in the first message, even just scheduling for after some
minutes/hours/days, without an absolute date/time, would still be helpful.

**Comment by luc-github** [comment]
My todo list is already full of helpful feature requests  so I need to sort them by "is it useful ?" "Does manyl people will use it ?" "Is there an existing solution ?"

So to be honest currently this FR would the last one

**Comment by josedpedroso** [comment]
I'm ok with that.

**Comment by kleffa** [comment]
Launch macros on determinate time sounds very interesting, by now using macros or comands like "G4 S3600 ;" makes a solution to pause at some time, but have lit of limitations, some printers have lights, buzzers and noises that can easily activate/deactivate using macros on time, by now ESP3D has NTP so sontime should not be a gteat problem

**Comment by luc-github** [comment]
nothing is difficult in programming, it's just a matter of spending time thinking about a problem and its solution and implementing the proper solution

so sure, PR is welcome
