### ISSUE TITLE
[Question] Some clarifications

### ISSUE THREAD

**Issue by ilko-k** [luc-github/ESP8266#1012]
First question, is this project still maintained ? No release since more than a year.

Second, some things differ bewteen the master branch here on git and the online configurator regarding the _platformio.ini_ file.

• **board_build.filesystem = littlefs** → not present in master
• **lib_ignore = ESP32SSDP** → is ESP32SSPD in master ( **D** and **P** are inverted ) 

Which one is up to date ?

**Comment by luc-github** [comment]
Reading the readme should answer all your questions:
![image](https://github.com/luc-github/ESP3D/assets/8822552/e34b429f-b62d-4cdf-b317-ce01abfe74ef)
No mention you can check the commit history to see even no release there was a fix 2 month ago for 2.1 and yesterday for 3.0 

>board_build.filesystem = littlefs → not present in master 

Well 2.1 only support SPIFFS ... and for 3.0 this is handle by the configurator

>lib_ignore = ESP32SSDP → is ESP32SSPD 

Wow orz...  I missed that - Thank You 2.1 and 3.0 updated , configurator looks Ok already

**Comment by ilko-k** [comment]
Allright thanks!
