### ISSUE TITLE
[BUG] Trobles to flash

### ISSUE THREAD

**Issue by kleffa** [luc-github/ESP8266#1020]
**Describe the bug**
![imagen](https://github.com/luc-github/ESP3D/assets/26838533/a925980f-5233-4be5-9a2b-37ae386eee9b)
try to open it on arduino IDE on windows 11
C:\Users\kleff\Desktop\ESP3D-3.0-alpha2\esp3d\src\core\hal.cpp:30:10: fatal error: soc/rtc_wdt.h: No such file or directory
   30 | #include <soc/rtc_wdt.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: soc/rtc_wdt.h: No such file or directory

**To Reproduce**

download relase from this page ESP3D-3.0-alpha2
open in arduino IDE

notify force to rename littlefs_esp8266_filesystem .cppo to littlefs_esp8266_filesystem.cppo (has a space)

**Expected behavior**

flashing the esp32

**Screenshots**

![imagen](https://github.com/luc-github/ESP3D/assets/26838533/1fb7df61-55f1-4582-aca6-8ddac6663e9a)

**ESP3D Firmware:**

- ESP3D FW version: 3.0 beta 1 (also tried with other version, same troubles)
- Flash method: Arduino Ide 
- Any change done in FW: nothing

**Comment by kleffa** [comment]
This still be a problem in Arduino IDE 2

**Comment by luc-github** [comment]
https://esp3d.io/esp3d/v2.x/installation/arduino/

**Comment by luc-github** [comment]
https://esp3d.io/esp3d/v3.x/installation/arduino/
