### ISSUE TITLE
[FEATURE REQUEST]Extra SD with M20 and M20L

### ISSUE THREAD

**Issue by kleffa** [luc-github/ESP8266#1021]
I see the SD root of my 3d printer with M20 and works!
 but if I try use M20L for entire name of files, M23 only works with M20 
so I have to chose see entire name of files or comand printer to work blinded

**Describe the solution you'd like**
I think just asking printer M20 and M20L then show user M20L, but play button with the M20 version, printer send same list so compare both lists should be easy

**Describe alternatives you've considered**
For now I list M20L so remember position, so change to M20
**Additional context**

this work to play
![imagen](https://github.com/luc-github/ESP3D/assets/26838533/4b73dd44-6db7-49b6-89e7-6d4f3105a363)
 this is better for users, but doesnt play
![imagen](https://github.com/luc-github/ESP3D/assets/26838533/c38ac6d4-daa2-4575-9979-0bf1a3787dd9)

**Comment by luc-github** [comment]
M200 ? https://marlinfw.org/docs/gcode/M200.html ?

Why using M20 but display M20 L ?

Long name worked in past - if now it is not the case, better ask Marlin to fix it instead of ask me to patch not working feature

**Comment by kleffa** [comment]
> M200 ? https://marlinfw.org/docs/gcode/M200.html ?
> 
> Why using M20 but display M20 L ?
> 
> Long name worked in past - if now it is not the case, better ask Marlin to fix it instead of ask me to patch not working feature

Here is the answer to M20 and M20L
In esp3d 3.0 beta3 it shows well, but M23 requires short filename. As I can see M20 returns both short and long names. 
How it's suppose to worked before?


M21

M20 L

echo:SD card ok

ok

Begin file list

CE3E04~1.GCO 13164510 CE3e04-30x5_huesitos-4h16m-23g.gcode

04/CE3-15~1.GCO 8958851 /CE3-15xgaleonataco-4h26m-24g.gcode

04/CE3-2X~1.GCO 2096208 /CE3-2x Pirata-0h56m-4g.gcode

04/CE3-3X~1.GCO 17631963 /CE3-3xGoro_R-15h42m-95g.gcode

04/CE3-50~1.GCO 5262191 /CE3-50_huesitos-1h22m-7g.gcode

04/CE3-5_~1.GCO 4665811 /CE3-5_arakar-1h25m-9g.gcode

04/CE3-5_~2.GCO 4783962 /CE3-5_chilesaurio-1h12m-8g.gcode

04/CE3-5_~3.GCO 4666366 /CE3-5_domeikodactilo-1h11m-8g.gcode

04/CE3-5_~4.GCO 6233093 /CE3-5_estegouros-1h23m-9g.gcode

04/CE9A0D~1.GCO 3765417 /CE3-5_ictiosaurio-1h07m-8g.gcode

04/CE3-BA~1.GCO 13560180 /CE3-Barco_6xGaleon-7h19m-40g.gcode

04/CE3-BA~2.GCO 6239102 /CE3-Barco_6xPirata-2h49m-13g.gcode

04/CE3-GO~1.GCO 5246172 /CE3-Goroshogi_1xRecta-4h38m.gcode

04/CE3-GO~2.GCO 10426693 /CE3-Goroshogi_2xR-9h09m-55g.gcode

04/CE3-GO~3.GCO 2779101 /CE3-Goroshogi_Exp_2xR-2h09m-13g.gcode

04/CE3-KO~1.GCO 19017814 /CE3-komikan_24xperro-5h22m-28g.gcode

04/CE3-KO~2.GCO 3078002 /CE3-komikan_2xPuma-0h55m-5g.gcode

04/CE3-LE~1.GCO 19002940 /CE3-Legion Barricada-4h34m.gcode

04/CE3-PI~1.GCO 18013935 /CE3-Piezas-7h38m-49g.gcode

04/CE3-QU~1.GCO 11065272 /CE3-quarto 6xCuadr-11h04m-79g.gcode

04/CE3-QU~2.GCO 11299200 /CE3-quarto 6xhexa-10h05m-68g.gcode

04/CE3-SH~1.GCO 13470718 /CE3-Shogi_1xR-11h05m-66g.gcode

04/CE3-SH~2.GCO 856218 /CE3-Shogi_Exp_2xR-0h41m-4g.gcode

04/CE3E04~1.GCO 20643043 /CE3e04-CALCIFER_cults-6h28m-42g.gcode

08/CE3E08~1.GCO 3702027 /CE3e08-arakar-1h16m-22g.gcode

08/CE3E08~2.GCO 3915118 /CE3e08-chilesaurio-1h06m-19g.gcode

08/CE3E08~3.GCO 3726164 /CE3e08-domeikodactilo-1h13m-20g.gcode

08/CE3E08~4.GCO 5044401 /CE3e08-estegouros-1h10m-23g.gcode

08/CE4F94~1.GCO 3205100 /CE3e08-ictiosaurio-1h07m-18g.gcode

CE3E04~2.GCO 23636275 CE3e04-33_arakar-8h32m-51g.gcode

CE3E04~3.GCO 25639657 CE3e04-33_chilesaurio-7h23m-45g.gcode

CE3E04~4.GCO 24009624 CE3e04-33_domeikodactilo-7h23m-44g.gcode

CE133C~1.GCO 32505132 CE3e04-33_estegouros-8h19m-51g.gcode

CEA9FC~1.GCO 20135376 CE3e04-33_ictiosaurio-6h57m-42g.gcode

CEF32E~1.GCO 10561759 CE3e04-088PA_L_MK1-4h06m-22g.gcode

CE19DC~1.GCO 0 CE3e04-CALCIFER_cults-6h28m-42g.gcode

CE410F~1.GCO 27910054 CE3e04-deathw-10h06m-60g.gcode

CE8CEE~1.GCO 4495695 CE3e04-Fermin_Serio-1h13m-8g.gcode

CE6490~1.GCO 4995684 CE3e04-Fermin_Serio-1h31m-11g.gcode

CE7131~1.GCO 5701488 CE3e04-Fermin_Serio-1h49m-11g.gcode

CE3E08~1.GCO 2128047 CE3e08-1quarto-2h12m-45g.gcode

CE3E08~2.GCO 2948251 CE3e08-60_huesitos-0h47m-11g.gcode

CE3-SH~1.GCO 13470734 CE3-Shogi_1xR-11h05m-66g.gcode

CED428~1.GCO 21291538 CE3e04-Laser mod S9-19h37m-123g.gcode

CE832C~1.GCO 3251596 CE3e04-mod screen-4h49m-36g.gcode

MOD1~1.GCO 5739231 mod 1.gcode

MOD2~1.GCO 27704227 mod 2.gcode

MOD3~1.GCO 18854798 mod 3.gcode

CE0043~1.GCO 2098116 CE3e04-Zero_Nose-0h41m-4g.gcode

CE3E08~3.GCO 307547 CE3e08-himobead_ressha-hiuma-0h20m-5g.gcode

CE3E08~4.GCO 2913438 CE3e08-audifonos 1-2h37m-55g.gcode

FANFA~1.GCO 172 fanfa.gcode

CE46F2~1.GCO 4853684 CE3e08-headband-side-right-5h42m-120g.gcode

CEF33F~1.GCO 4093068 CE3e08-pandita2-4h34m-94g.gcode

CE061B~1.GCO 6427563 CE3e08-panda2-left-5h01m-98g.gcode

CE56E2~1.GCO 923532 CE3e08-panda3-0h47m-12g.gcode

CE55BE~1.GCO 883597 CE3e08-firelordgary-1h24m-30g.gcode

CE4480~1.GCO 6320957 CE3e08-quarto cuadras 6-6h32m-133g.gcode

CEC2CD~1.GCO 6046295 CE3e08-quarto hexas 6-6h32m-133g.gcode

CE7E21~1.GCO 715102 CE3e08-Mount-0h58m-19g.gcode

08MOUN~1.GCO 715102 08mount 58m-19g - copia.gcode

End file list

ok

**Comment by luc-github** [comment]
no if you enable long name in Marlin `M20 L`
then `M23 long_name.gcode` is supposed to work and I tested before it was working, if now it is again broken(it was several times) it is marlin bug

**Comment by kleffa** [comment]
in marlin documentation, only shows short name 
https://marlinfw.org/docs/gcode/M023.html
also a closed issue of this long ago in marlin 
https://github.com/MarlinFirmware/Marlin/issues/3079 

so basically it was no a feature and marlin have no intention to work with long names.
maybe a simple solution should be add a button next to play to ask m33 of a short name file

**Comment by luc-github** [comment]
no Marlin is now supposed to support long name, there  were several PR for this

**Comment by kleffa** [comment]
I can´t find that M23 doesn´t work with long filename... maybe in futrure versions of marlin, but still considering almost easy implement play button for this kind of lines 
CE46F2~1.GCO 4853684 CE3e08-headband-side-right-5h42m-120g.gcode 
to

CE3e08-headband-side-right-5h42m-120g.gcode [M23 CE46F2~1.GCO ; M24]

**Comment by luc-github** [comment]
you did ot search a lot here one of the PR https://github.com/MarlinFirmware/Marlin/pull/25540

as wrote it is.Marlin bug, I do not plan to workaround because it will not fix ESP3DLib which use shared SD

**Comment by kleffa** [comment]
maybe just a change on the play button on the webUI, the #define UTF_FILENAME_SUPPORT is not suported universally, requires more memory and that stuff

**Comment by luc-github** [comment]
UTF is not long name is related to unicode and multibytes chars like chinese

**Comment by kleffa** [comment]
> you did ot search a lot here one of the PR [MarlinFirmware/Marlin#25540](https://github.com/MarlinFirmware/Marlin/pull/25540)
> 
> as wrote it is.Marlin bug, I do not plan to workaround because it will not fix ESP3DLib which use shared SD

who undestand? I will try that and maybe it get solved, but as I said, not standar answer

**Comment by kleffa** [comment]
NOP doesn´t worked at all
