### ISSUE TITLE
EXTRA GİRİŞ ÇIKIŞ OKUMA VE YAZMA İÇİN PCF8575 DESDEĞİ

### ISSUE THREAD

**Issue by hsyngndz85** [luc-github/ESP8266#1022]
pcf8575 is a 16-bit expansion chip, available in the Arduino library, it can address up to 8 chips, which means a total of 8 * 16 128 pin control, which is an essential issue for ESP.

for example
M64P0.1
Set the 1st pin of the 0th IC in the I2C port to 1.
M65P0.1
Set the 1st pin of the 0th IC in the I2C port to 0.

example
M66P0.1
he. wait until pin 1 of the chip becomes 1
like in linux cnc
In this way, we have a total of 128 pins that can be used as input and output.

**Comment by luc-github** [comment]
there is no user case for this for esp3d
that component would be used for different FW like  Marlin for esp32 or grblHAL for esp32
