### ISSUE TITLE
There is no pindebug.h file for esp32

### ISSUE THREAD

**Issue by hsyngndz85** [luc-github/ESP8266#1023]
When the pin debug feature is turned on, it gives a "no file" error.

**Comment by luc-github** [comment]
what is pin debug feature?
what is pindebug.h ? that file is not part of esp3d

**Comment by luc-github** [comment]
looking at https://github.com/MarlinFirmware/Marlin/issues/created_by/hsyngndz85, I am not Marlin dev you ask in wrong place
