### ISSUE TITLE
[FEATURE REQUEST] octoprint server

### ISSUE THREAD

**Issue by kleffa** [luc-github/ESP8266#1027]
is simple to conect Cura or any slicer to octoprint, so make a octoprint like server, so maybe its a god idea to check how octoprint is conected to cura via plugin

I noted this proyect https://github.com/probonopd/WirelessPrinting basically is a octoprint server, but is not so complet as ESP3D

maybe some code from there can be imported to make that

**Comment by luc-github** [comment]
there is some pluggin as far I know that allow cura to be connected to esp3d but I do not remember in which place I saw it because I do not use cura

I do not have time to investigate on such feature sorry - but PR are always welcome
