### ISSUE TITLE
ESP3D 3.0 git with Octoprint socket connection

### ISSUE THREAD

**Issue by SOliver78** [luc-github/ESP8266#1035]
Hello,
I have a problem connecting ESP3D 3.0 git to Octoprint.
Octoprint 1.10.2 and Network-Printing Plugin (0.1.0) run with ESP3D 2.1.4 without any problems.
With ESP3D 3.0 git I can't get a connection with socket://192.168.110.23:8282, even though the port is open according to nmap.
Does anyone know the problem?

Why I want to use ESP3D 3.0 git? Because I want to use a WT32-ETH01 with LAN.

Thank you.
Olli

**Comment by luc-github** [comment]
did you check the port is correct in your settings ?

**Comment by SOliver78** [comment]
In ESP3D the following settings are set:
![2024-07-09 14_47_37-esp3d – Mozilla Firefox](https://github.com/luc-github/ESP3D/assets/107271539/a7b55fb3-ded5-4030-820d-6325cecdc935)
In Octoprint the connection is:
![2024-07-09 14_48_28-OctoPrint](https://github.com/luc-github/ESP3D/assets/107271539/0ada9d06-e795-4a90-b133-9d8ea3870e73)
But after a few seconds, the status is offline:
![2024-07-09 14_49_10-OctoPrint](https://github.com/luc-github/ESP3D/assets/107271539/2636031e-b6d2-4aff-87b1-443a2b5104b3)

The Octoprint server can reach the web socket port of the ESP3D:
![2024-07-09 14_50_27-opp@optoprint_ ~](https://github.com/luc-github/ESP3D/assets/107271539/0e108786-08a5-49b1-b999-54c83bafdbe9)

Is it possible, to look into any connection logs on the EDP3D?

**Comment by luc-github** [comment]
I am confused in 2.1 there is no websocket support for extra communication  but you mention it works, are you sure you are not using telnet in 2.1 ?

in that case you should use port 23 and looking at octoprint UI I am pretty sure that is what they use 
`socket` is different than `websocket `

**Comment by SOliver78** [comment]
In ESP3D 2.1 i used the data port für the socket connection in Octoprint:
![2024-07-09 16_06_17-3D-Drucker-Wifi – Mozilla Firefox](https://github.com/luc-github/ESP3D/assets/107271539/76c13725-87eb-44eb-9796-de5c08a94279)

Is it not the same as the websocket port in EDP3D 3.0?
If not, where i can configure the data port in ESP3D 3.0?
I have enabled the following in configuration.h:
`/* Use Websocket server
 * Enable websocket communications
 */
#define WS_DATA_FEATURE`

**Comment by luc-github** [comment]
data port in 2.1 is the telnet  port in 3.0 , it is raw tcp actually 
so based on your setting use the port 23 for your Network-Printing Plugin 

using same port for different purpose between 2.1 and 3.0 is may be confusing, but it is not when you know what is for

**Comment by luc-github** [comment]
I guess issue is now fixed - I close ticket then

**Comment by SOliver78** [comment]
Hi, yes if you know that it is the telnet port, it works now ;)

Thanks for the hint.
