### ISSUE TITLE
[BUG] cannot get the esp32 and the board to communicate

### ISSUE THREAD

**Issue by Reza-v** [luc-github/ESP8266#1038]
**Describe the bug**

the esp32 and the 3d printer mainboard do not want to communicate over serial, no matter the pins or uart i use. i am using a lolin esp32 s2 mini and a mega 2560 based board, using the rx0 and tx0 bootloader serial pins.

**To Reproduce**

1. uploaded code to esp32
2. connected the esp32 s2 to the mainboard using jumpers  with a voltage divider on the tx pin coming from the mega (have confirmed the rx and tx pins used on the mainboard do work as intended and the problem is with the esp

i have tried using the default pins in pins.h as well as selecting another set of pins.
**Screenshots**

![Screenshot 2024-07-21 210134](https://github.com/user-attachments/assets/6dcbb8a7-c12c-4ce7-8cad-c64666ffa3ac)

**ESP3D Firmware:**

- ESP3D FW version: [3.0] 
- ESP3D-WebUI Version:[3.0]
- Wifi mode:[STA]
- Flash method: [PlatformIO]  
- Any change done in FW: only the changes in configuration.h

**Target Firmware:**

- Name: [Marlin]
- Version [2.1.2.4]

**Board used (please complete the following information):**

- MCU:[esp32 s2}
- Name:[lolin s2 mini]
- Flash size: [4M]

**Comment by luc-github** [comment]
that screen is not related to serial communication but communication between webUI and esp3D
what EXACT version of webUI are you using ?
what EXACT version of esp3d are you using ?
type `http:\\<your-IP>?forcefallback=yes` to go to maintenance page and delete the current webUI which is either bad version or corrupted

**Comment by Reza-v** [comment]
I clicked on "latest development version" on the github page and downloaded that, built it and uploaded it. i will try doing it again today. thank you for the help.

**Comment by luc-github** [comment]
webui packages are already build in dist directory, what about esp3d version , it is visible in maintenance page

**Comment by Reza-v** [comment]
![image](https://github.com/user-attachments/assets/654c9d2b-fff4-4a92-af6a-976b36311e69)
this is the one

**Comment by luc-github** [comment]
ok this is latest version

**Comment by Reza-v** [comment]
Ok so the prebuilt webui worked like a charm and I'm past the connecting page but now I still can't communicate with the board, the gcodes I send are given no response. I tried reuploading the code to the ESP, using default pins, using serial0 and 1, both with default rx tx pins and different pins, nothing is working.

i have used pins 4 and 5 as the default rx tx pins for serial1 suggested by you in another issue thread, no dice,

also I must point out that sometimes when I connect the jumpers, the wifi just dies and I need to reset the board to get it working again. is that something you've seen before?

**Comment by luc-github** [comment]
connect the jumpers ? what jumpers are you talking about?

**Comment by Reza-v** [comment]
the jumpers to connect tx and rx pins to the 3d printer board.
i am using a voltage divider on the tx pin coming from the 2560

**Comment by luc-github** [comment]
you hàve a picture of your wiring ? I do not understand what you mean

**Comment by Reza-v** [comment]
what's so hard to understand? i just don't know what pins on the esp32 s2 is the default serial1 pins and no one seems to know either, and nothing i try works. shouldn't you connect the esp board to the 3d printer board through serial in order for them to communicate with each other? that's my main issue. i cannot get them to communicate with each other no matter what pins i try or what pins i set the esp32 to recognize as tx and rx.

**Comment by luc-github** [comment]
looking at https://docs.espressif.com/projects/esp-idf/en/stable/esp32s2/_images/esp32-s2_saola1-pinout.jpg
TX1 = GPIO17 / RX1 = GPIO18  is that what you use for serial 1 or do you use custom pins ?
https://esp3d.io/esp3d/v3.x/hardware/esp_boards/esp32-s2/wemos-s2-mini/index.html

**Comment by luc-github** [comment]
> what's so hard to understand? i just don't know what pins on the esp32 s2 is the default serial1 pins and no one seems to know either, and nothing i try works. shouldn't you connect the esp board to the 3d printer board through serial in order for them to communicate with each other? that's my main issue. i cannot get them to communicate with each other no matter what pins i try or what pins i set the esp32 to recognize as tx and rx.

well I do not understand why you have jumpers - sorry - I am not by your side I do not know what you are doing, I do not know what your board looks like because none of mega / esp32-s2 I know have jumpers - and having wifi down when doing wiring is not normal - I am not mind reader I just try to understand your wiring

**Comment by Reza-v** [comment]
oh you must be confused, i am talking about jumper wires not the other type of jumpers. i am using jumper wires temporarily for testing and i'll make proper connectors after it actually works.

unfortunately pins 17 and 18 did not work.

**Comment by luc-github** [comment]
then in configuration.h
use Serial0
`#define ESP_SERIAL_OUTPUT USE_SERIAL_0`

and add these 2 lines
```
#define ESP_RX_PIN 37
#define ESP_TX_PIN 39
```

Like this you use custom pins and there will be no guess

**Comment by Reza-v** [comment]
what about the lines in esp3d_pins.h file? those don't matter? i've been changing those values to custom pins

**Comment by luc-github** [comment]
you do not have to edit this file everything is made to only use configure.h, so if you modified another file then I do not know what to say because I have no idea what changes you did

**Comment by luc-github** [comment]
in all case I suggest you to use this kind of device : https://www.amazon.com/HiLetgo-FT232RL-Converter-Adapter-Breakout/dp/B00IJXZQ7C/ref=sr_1_2_sspa

to check your esp board pins and also to check your mega wiring is correct - you will save time in debug
be sure baudrate is same on both side

**Comment by Reza-v** [comment]
how do you change baud rate in your code? i could not find it

**Comment by luc-github** [comment]
in when UI not in code, in settings /features

**Comment by Reza-v** [comment]
oh that's interesting...

**Comment by luc-github** [comment]
or using direct commands : https://esp3d.io/esp3d/v3.x/documentation/commands/esp901/index.html

**Comment by Reza-v** [comment]
that worked. sorry i wanted to ask you how to change the baud rate but i totally forgot. i never got to the UI and just assumed it's stuck on connecting because i didn't get the serial hooked up correctly. thanks a lot for the help.
