### ISSUE TITLE
[FEATURE REQUEST] Add Obico client support

### ISSUE THREAD

**Issue by dzervas** [luc-github/ESP8266#1041]
**Is your feature request related to a problem? Please describe.**

It would be amazing to add the ability to make ESP3D act like an [Obico Client](https://www.obico.io/docs/api/api-objects/)

**Describe the solution you'd like**

The way I see it, it should be implemented natively as plugins are web-only (right?)

**Describe alternatives you've considered**

I don't see any

**Comment by luc-github** [comment]
esp3d does not have access to many of the item status so there is few chance, no mention esp3d is just a bridge it does not analyse store any data, may be that could be applied to ESP3D-TFT TBD
