### ISSUE TITLE
Feature request. Adjustable delay for file transfer. 

### ISSUE THREAD

**Issue by A13xund3r** [luc-github/ESP8266#1051]
### Discussed in https://github.com/luc-github/ESP3D/discussions/1010

<div type='discussions-op-text'>

<sup>Originally posted by **A13xund3r** March 19, 2024</sup>
I was repairing BTT GTR V1 mainboard at work and took opportunity to check how does ESP3D communicate during file upload. So this is scope screenshot, yellow line is data sent by ESP3D, blue line is GTR response.
![esp3d](https://github.com/luc-github/ESP3D/assets/47088783/4a7cd0c8-30eb-40c8-8d5b-e07b4a8cb64c)
As you can see GTR respond literally immediately after ESP finish line, I didn't sniffed what it is but I'm 100% sure it is "OK". So why ESP wait 20ms before it send another line? I suspect it is safety measure to give mainboard time to process data it just received but I expect it is already processed when it reply "OK". Also BTT GTR is a monster comparing to any Atmel based controller so I think we can play with shorter or no delay at all. At least it could be available as adjustable option in settings.

</div>

**Comment by luc-github** [comment]
What file transfert are you refering to? And what version of ESP3D are you using?

**Comment by A13xund3r** [comment]
Old style M28/M29 file transfer protocol, ESP3D2.1.x
Where in the code is this delay implemented? I can't find it to try it myself.

**Comment by luc-github** [comment]
This protocol is no more supported https://esp3d.io/ESP3D/Version_2.1.X/documentation/sdtransfert/

**Comment by A13xund3r** [comment]
Like big corpo discontinuing functional products... 
Could you at least point me to the file with command holding CPU for 20ms during file transfer?

**Comment by luc-github** [comment]
I am not Big corpo, I am not paid for what I do
I share my code for free, so such comment is pretty rude
If you are not happy with ESP3D do not use it, that is very simple, my code is fully available so do your homework by yourself, I am not willing to give any help after such attitude

**Comment by A13xund3r** [comment]
Won't fix
And if you think my comment was rude then look at your "no more supported" when I asked where this delay is.
Yes I tried to find it 3 hours of browsing all files, I'm assembler guy and feel sick when I look at C++.

**Comment by luc-github** [comment]
sorry I disagree my comment was not rude I answered to your feature request and my comment had a link that explained why it is not supported, it was not rude but explained.
You had a bad day I am sorry for you

**Comment by A13xund3r** [comment]
Absolutely not bad day, you just misinterpreted my comment which was meant to have humoristic attitude. Especially when my work does exist mainly because big fishes in industrial business say they no longer support something and offer expensive upgrade so we are here to fix things.
So as you see both of us doesn't see anything wrong in our words but does see in each other. Normal in txt communication where body language is missing.
