### ISSUE TITLE
[Question]<Enter comprehensive title>

### ISSUE THREAD

**Issue by Hoanghung3003** [luc-github/ESP8266#1052]
i have mks robin wifi use on mks robin nano with firmware marlin and i can't build #define COMMUNICATION_PROTOCOL MKS_SERIAL in visual studio code but #define COMMUNICATION_PROTOCOL RAW_SERIAL can.

**Comment by luc-github** [comment]
I have no issue compiling with MKS_SERIAL and without any information I close ticket
