### ISSUE TITLE
[BUG] SD stream failed: 1

### ISSUE THREAD

**Issue by piotr-go** [luc-github/ESP8266#1053]
**Describe the bug**
**To Reproduce**

Sending a "[ESP700]/SD/test.gcode" in web gui terminal gives me:
> [ESP700]/SD/test.gcode
> ok
> error: stream failed: 1

**Expected behavior**
no error

**ESP3D Firmware:**

ESP3D v3

**Target Firmware:**

Marlin 2.1.x

**Board used (please complete the following information):**

ESP32-S3 (4MB flash, 2MB PSRAM)
SKR-Mini E3 v1.2

**Additional context**

I checked what serial output looks like, and there is no '\n' after command.
If i fake "ok" answer with serial terminal (ESP32---uart---PC ), i sill got "error: stream failed: 1".
It seems there is no reaction to incoming data.

Two way terminal communication in web gui is working. Two way telnet-uart also OK.

**Comment by luc-github** [comment]
1 - Streaming is not implemented yet  for Marlin only for grbl and it is very basic only ping/pong streaming: https://github.com/luc-github/ESP3D/issues/243

2 - it seems there is no SD connected to your ESP because error says file cannot be opened

3 - the Ok means command received, not command executed, that is why you have a error after

**Comment by piotr-go** [comment]
1. I don't understand, I thought that communication with Marlin is basic ping/pong streaming?
2. I uploaded this file over wifi. Missing file is error 12, error 1 is answer timeout.

File read is OK. I see first command over UART. Command have no '\n' ending.

**Comment by luc-github** [comment]
1 not really webui send commands and analyse serial from Marlin
2 you upload to which sd ? your above description does not mention any

**Comment by luc-github** [comment]
you should read this:
https://esp3d.io/ESP3D/Version_3.X/documentation/sdtransfer/

**Comment by piotr-go** [comment]
2. to ESP_DIRECT_SD, file is there, i confirmed. MD5 sum mach, no errors.

**Comment by luc-github** [comment]
ok so you have direct connection to sd but content is not visible from printer and streaming feature is not yet available
there is no print button in webui, right ?

**Comment by piotr-go** [comment]
Yes.
So no SD streaming in v3 for now?

**Comment by luc-github** [comment]
not in v3 yet,  streaming properly is not that easy
ESP3D-TFT has basic Marlin ping pong streaming but it is slow on small movement,  must add buffered streaming to be good.
so still some work to do
will be same.for V3

**Comment by piotr-go** [comment]
Is it possible to run v2 on esp32-s3 (or s2) ? Is SD streaming supported in v2?

**Comment by luc-github** [comment]
sd streaming is not supported in v2, direct sd upload is even not supported in v2

**Comment by piotr-go** [comment]
OK, Thank You for your answers.
I do have couple more question, but not SD related so i open new thread.

**Comment by luc-github** [comment]
have look to https://esp3d.io/ there are a lot of information
