### ISSUE TITLE
esp3d and grblhal connecting using ioSender

### ISSUE THREAD

**Issue by semos2k** [luc-github/ESP8266#1065]
**Describe the bug**

Hi, i connected board running esp3d to other board running GRBLHal STM32F407 when connect using ioSender not work telnet o websocket. when test lightburn works correctly, The problem has been found by @terjeio I attach the conversation and more details

**To Reproduce**

connect te grblhal-serial to esp3d and connecting using telnet from ioSender

**Expected behavior**

when connect using ioSender show error.

**Screenshots**

**ESP3D Firmware:**

- ESP3D FW version: v3.0
- ESP3D-WebUI Version: v3.0
- Wifi mode: STA
- Flash method: PlatformIO
- Any change done in FW: N/A

**Target Firmware:**

- Name: GRBLHal
- Version: latest

**Board used (please complete the following information):**

- MCU: ESP32
- Name: dev
- Flash size: 4M

**Additional context**

https://github.com/terjeio/ioSender/discussions/417

**Comment by luc-github** [comment]
pls try latest git , it should be fixed already

**Comment by semos2k** [comment]
Yes, it worked very well, thank you for your time.
