### ISSUE TITLE
reset after connecting to webserver

### ISSUE THREAD

**Issue by CaptBlaubaer** [luc-github/ESP8266#32]
ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld

is thrown by device via serial interface.
any idea what i`m making wrong?

Best regards,
CaptBlaubaer

**Comment by luc-github** [comment]
using default settings or you already changed some ?

**Comment by luc-github** [comment]
not sure it is same as mine : https://github.com/luc-github/ESP8266/issues/18
It happen randomly, I reported issue as I have it also with hellowwebserver sample code : github.com/esp8266/Arduino/issues/428

**Comment by CaptBlaubaer** [comment]
am using default settings

**Comment by luc-github** [comment]
check you power supply - be sure you added some pull up resistors - also do not forget after flash to remove GPIO 0 from GND

**Comment by CaptBlaubaer** [comment]
![esp2kit](https://cloud.githubusercontent.com/assets/13705351/9150267/3dfaf924-3dd0-11e5-82ef-a2be3dde8488.jpg)

Using this design, Prog jumper is removed. Powersupply 2a wallwart

**Comment by luc-github** [comment]
I only have ESP01 so cannot comment about 12

**Comment by CaptBlaubaer** [comment]
same behaviour with a brand new nodemcu.
reset after the first load of a web page

ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld

**Comment by luc-github** [comment]
Strange - I do not reproduce - I connect from W7 to AP and can navigate to each page without problem

**Comment by luc-github** [comment]
can you reproduce when using webserver sample App ?

**Comment by CaptBlaubaer** [comment]
AdvancedWebServer example works without a reset. device is station mode and connected to my router

**Comment by luc-github** [comment]
may be try using AP mode for AdvancedWebServer 
or change code to use Station Mode by default in my code.

**Comment by luc-github** [comment]
Are you using internet explorer browser ? 

I am using Chrome and having no issue -  but usint IE I can reproduce the issue - the only page it does not happen on IE is unknown page.
Can you confirm ?

**Comment by luc-github** [comment]
Ok when can reproduce it is more easy 
The root cause is the css, I may introduce some bug by the deep clean up
If remove in webinterface.cpp:
``` "<link rel=\"stylesheet\" href=\"/mincss.css\" type=\"text/css\">\n</head>\n<body>"\```
it do not crash anymore under IE

additionally it solve a new issue that appear under chrome/IE about security setting block the refresh of the page on printer part

So css is definitively buggy - need to redo the UI without bootstrap CSS funtionnalities but keeping fancy

**Comment by luc-github** [comment]
New css embedded seems not crashing under Internet Explorer anymore
https://github.com/luc-github/ESP8266/commit/1cb93ef7873f352ac9d21772eeed8d43aad7be52
