### ISSUE TITLE
USB / SD /OnboardSD Acces over WEB UI

### ISSUE THREAD

**Issue by MrOmbre** [luc-github/ESP8266#408]
Will it be possible in future, to have access to Onboard Storage like USB or SDs LCD Storage and Printerboard SD from WEB UI ?

As example, I have a .gcode file on USB Stick plugged in BQ TFT35 V3.0 and want to start this print from WEB UI

**Comment by luc-github** [comment]
sorry, seems I missed this message

This may need BTT FW update as well as ESP3D /ESP3D-WEBUI

Anyway there is already an issue open for BTT and BQ TFT support : https://github.com/luc-github/ESP3D/issues/393
so feel free to continue there
