### ISSUE TITLE
[Question] How is implemented server-side of WEB UI ? is there possibility to hook up mobile application?

### ISSUE THREAD

**Issue by hunterius-prime** [luc-github/ESP8266#411]
I want to built mobile application to interface with ESP3D in adition to web interface and  use ( if possible) server-side part of web UI. It also make it possible to left out any UI parts and may be spare some space ( but this is not an issue). From developer perspective I would appreciate any information ( not like "there is web ui dedicated mobile app is obsolete" ) that can help me decide if use webui as backend or do something different. Or if it is even possible to use it. 

Sure , I will look into code myself and learn, but any heads-up is welcome.

**Comment by luc-github** [comment]
any app using telnet should work

https://github.com/luc-github/ESP3D/issues/20#issuecomment-366002974
another one is repetier host / server

**Comment by hunterius-prime** [comment]
thank you
