### ISSUE TITLE
bin files?

### ISSUE THREAD

**Issue by timbor123** [luc-github/ESP8266#414]
Hello.
If it’s not difficult, please, make the compiled files *bin* for the firmware?
I can not compile the source code for esp07, already a week.

**Comment by luc-github** [comment]
there is no plan to deliver binaries because there are too many  compilation target possible, also there are too many configurations settings in ESP3D.

What issues do you meet ?

**Comment by timbor123** [comment]
```
asyncwebserver.cpp:21:22: error: pgmspace.h: No such file or directory
compilation terminated.
exit status 1
pgmspace.h: No such file or directory
```

**Comment by luc-github** [comment]
Please do not use async - it is not well supported currently
I have clarified the readme : 
`Use webserver support (recommended as stable), asyncwebserver support is no more stable on ESP3D`
