### ISSUE TITLE
BIGTREETECH-TFT35-E3-V3.0

### ISSUE THREAD

**Issue by philoupat** [luc-github/ESP8266#426]
ola

y uses this screen BIGTREETECH-TFT35-E3-V3.0 with a mks v1.4 card
connection with esp3d is ok
but no parameters move
in the web page
unable to monitor printer in wifi
thank you for advice

**Comment by luc-github** [comment]
please check https://github.com/luc-github/ESP3D/issues/393
if you do not find the answer in it, please fill the issue template properly, all questions in it are important to give support

**Comment by luc-github** [comment]
@philoupat any update ?
