### ISSUE TITLE
Image container for WiKi

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#427]
This thread is to help people to share images on Wiki without using external storage

**Comment by gello0** [comment]
![59010169-9d471580-8830-11e9-97a9-ba0b46776449](https://user-images.githubusercontent.com/28871862/79461201-78f0c380-8013-11ea-83f7-db038b93a7cc.jpg)
Anet A8 1.7 board

**Comment by luc-github** [comment]
![image](https://user-images.githubusercontent.com/8822552/84999946-1078ac80-b152-11ea-84ce-84803b1ab02e.png)
