### ISSUE TITLE
WebUI Loading Error

### ISSUE THREAD

**Issue by I-FrosT-I** [luc-github/ESP8266#433]
When I access my WebUI on my ESP8266 WiFi board it just says loading all the time.  I've heard the following command fixes the issue:

[ESP710]FORMAT pwd=admin

However I can't seem to connect to it to send the command. Is there any particular consol you recomment for connecting and reseting the module or any video guides? I've been searching for a few days and can't seem to figure it out.

**Comment by luc-github** [comment]
[`ESP444]RESET`
