### ISSUE TITLE
[Question]Problems with SD CARD

### ISSUE THREAD

**Issue by adrirock1141** [luc-github/ESP8266#434]
Somebody can help me please, i just installed ESP3D, it works, i can conect to ip address, but when i want to upload a gcode to sd card, it say an error, start heating the bed automatically and after just reset the printer, i cant print from sd card with WEBIU.
If I try to print with WEBIU from SD card the printer doesnt do anything, but i can send gcode like home and temperatures.
I use Marlin

**Comment by luc-github** [comment]
Please fill a bug/problem report - there no information in your description to help you
