### ISSUE TITLE
No Upload SD Card, Cant Print with ESP3D

### ISSUE THREAD

**Issue by adrirock1141** [luc-github/ESP8266#435]
**Describe the bug**
I cant use de SD Card to upload using the WEBIU, I cant Print nothing using the WEBIU, the only thing i can do is home and move axis.
If i try to upload something an error ocurr

**ESP3D Firmware:**
- ESP core version: 2.5.2
- Version: 2.1
- Web UI Version:2.1
- Wifi mode:CLIENT 
- WebUI version: 2.0

**Target Firmware:**
 - Name: Marlin
 - Version 1.1.9

**Board used :**
 - MCU: ESP8266 
 - Name:NodeMCU V1.0
 - Flash size: 4M: 2M/2M 

.

**Comment by luc-github** [comment]
which error ?

your esp3d version is too old I guess as you do not give it

left the template without filling information is useless

**Comment by adrirock1141** [comment]
> **Describe the bug**
> I cant use de SD Card to upload using the WEBIU, I cant Print nothing using the WEBIU, the only thing i can do is home and move axis.
> If i try to upload something an error ocurr
> 
> **ESP3D Firmware:**
> 
> * ESP core version: 2.5.2
> * Version: 2.1
> * Web UI Version:2.1
> * Wifi mode:CLIENT
> * WebUI version: 2.0
> 
> **Target Firmware:**
> 
> * Name: [e.g. Marlin]
> * Version [e.g. 1.1.X]
> 
> **Board used :**
> 
> * MCU: ESP8266
> * Name:NodeMCU V1.0
> * Flash size: 4M: 2M/2M
> 
> .



> which error ?
> 
> your esp3d version is too old I guess as you do not give it
> 
> left the template without filling information is useless

I just  edit it, sorry im learning how to use this, the error is this

I cant use de SD Card to upload using the WEBIU, I cant Print nothing using the WEBIU, the only thing i can do is home and move axis.
If i try to upload something an error ocurr

**Comment by luc-github** [comment]
well, take time to collect information, versions, screen shot, etc.

you even do not say what are the error messages look like when uploading or when trying to print, 
sorry but cannot help with  current details

**Comment by adrirock1141** [comment]
> well, take time to collect information, versions, screen shot, etc.
> 
> you even do not say what are the error messages look like when uploading or when trying to print,
> sorry but cannot help with current details
Describe the bug
I cant use de SD Card to upload using the WEBIU, I cant Print nothing using the WEBIU, the only thing i can do is home and move axis.
If i try to upload something an error ocur

here i put screen of what happen
![Captura 1](https://user-images.githubusercontent.com/30213125/78829719-daca8100-79b4-11ea-972a-30dc92474579.PNG)
![Captura 2](https://user-images.githubusercontent.com/30213125/78829730-def69e80-79b4-11ea-84ec-86367bc75c6d.PNG)
![Captura 3](https://user-images.githubusercontent.com/30213125/78829739-e1f18f00-79b4-11ea-8f56-b4d17adedd80.PNG)




Here are the versions of everything

ESP core version: 2.5.2
Version: 2.1
Web UI Version:2.1
Wifi mode:CLIENT
WebUI version: 2.0
Firmware
Name: Marlin
Version 1.1.9
Board
MCU: ESP8266
Name:NodeMCU V1.0
Flash size: 4M: 2M/2M

**Comment by luc-github** [comment]
you cannot print such file name in Marlin, only only dos file name are accepted by Marlin.not long name
web ui does not allow such long file name neither but seems you can, which is not normal,
versions you give are incomplete

please copy the output of the following commands:
[ESP800]
[ESP420]

**Comment by adrirock1141** [comment]
[ESP800]
FW version:2.1.0.b39 # FW target:marlin # FW HW:Serial SD # primary sd:none # secondary sd:none # authentication:no # webcommunication:Sync:81:192.168.0.150 # hostname:Tevo

[ESP420]
{"chip_id":"10464640","cpu":"160","freemem":"36.77 KB","SDK":"2.2.1(cfd48f3)","flash_size":"4.00 MB","update_size":"530.31 KB","spiffs_size":"2.81 MB","baud_rate":"250000","sleep_mode":"Modem","channel":"1","phy_mode":"11g","web_port":"80","data_port":"8888","hostname":"Tevo","active_mode":"STA (68:C6:3A:9F:AD:80)","connected_ssid":"FerNaAd","connected_signal":"86%","ip_mode":"Static","ip":"192.168.0.150","gw":"192.168.0.1","msk":"255.255.255.0","dns":"(IP unset)","disabled_mode":"AP (6A:C6:3A:9F:AD:80)","captive_portal":"Enabled","ssdp":"Enabled","netbios":"Enabled","mdns":"Enabled","web_update":"Enabled","pin recovery":"Disabled","autentication":"Disabled","target_fw":"Marlin","M117_output":"Enabled","Notifications":"Disabled","Serial_output":"Enabled","Websocket_output":"Enabled","TCP_output":"Enabled","fw":"2.1.0.b39 ESP8266/8586"}

**Comment by adrirock1141** [comment]
i have read  https://github.com/luc-github/ESP3D/issues/321 and i send you this to complete the information that you may need

M115
FIRMWARE_NAME:Marlin   (Github) SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:  EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Cap:SERIAL_XON_XOFF:0
Cap:EEPROM:1
Cap:VOLUMETRIC:1
Cap:AUTOREPORT_TEMP:1
Cap:PROGRESS:0
Cap:PRINT_JOB:1
Cap:AUTOLEVEL:1
Cap:Z_PROBE:1
Cap:LEVELING_DATA:1
Cap:BUILD_PERCENT:0
Cap:SOFTWARE_POWER:0
Cap:TOGGLE_LIGHTS:0
Cap:CASE_LIGHT_BRIGHTNESS:0
Cap:EMERGENCY_PARSER:0
Cap:AUTOREPORT_SD_STATUS:0
Cap:THERMAL_PROTECTION:1
M20
Begin file list
/CATANI~1/CATANC~1.GCO 835739
/CATANI~1/CATANC~2.GCO 3413653
/CATANI~1/CATANC~3.GCO 7490159
/CATANI~1/CATANL~1.GCO 3597494
/CATANI~1/CATANP~1.GCO 662555
/CATANI~1/CATANP~2.GCO 3275822
/CATANI~1/CATANP~3.GCO 1377297
/CATANI~1/CATANP~4.GCO 151284
/LIBERA~1/22CALI~1.GCO 43199182
/LIBERA~1/FRAME~1.GCO 89084424
/LIBERA~1/GRIP~1.GCO 31740285
/LIBERA~1/REPUES~1.GCO 4419221
/LIBERA~1/TRIGGE~1.GCO 3598769
/MASCAR~1/1-PEST~1.GCO 745412
/MASCAR~1/2-PEST~1.GCO 1485128
/MASCAR~1/MASCAR~1.GCO 4088894
/MASCAR~1/MASCAR~2.GCO 4088894
/MASCAR~1/TARUGO~1.GCO 2180456
/MASCAR~1/TARUGO~2.GCO 444410
/MASCAR~1/VICERA~1.GCO 2847701
/TEST/MOAI~1.GCO 2413048
/TEST/PATA_T~1.GCO 3216100
/TEST/VIBRAC~1.GCO 6812378
/TEST/CUBO.GCO 362392
HOOK~1.GCO 930620
SEGURO~1.GCO 264488
SOPORT~1.GCO 257554
End file list
M21
echo:SD card ok

**Comment by luc-github** [comment]
I think you have issue with webUI as you cannot upload long file name and you show you upload :
`catan ladron.gcode` which is long file name and it is not accepted to be uploaded by webUI, and it is not working with Marlin
you should have this error message:
![image](https://user-images.githubusercontent.com/8822552/78838244-120d5200-79f6-11ea-9f64-0ec04f7c8de2.png)

**Comment by adrirock1141** [comment]
> I think you have issue with webUI as you cannot upload long file name and you show you upload :
> `catan ladron.gcode` which is long file name and it is not accepted to be uploaded by webUI, and it is not working with Marlin
> you should have this error message:
> ![image](https://user-images.githubusercontent.com/8822552/78838244-120d5200-79f6-11ea-9f64-0ec04f7c8de2.png)

i still have this error
![Captura 3](https://user-images.githubusercontent.com/30213125/78838816-fa69a580-79c4-11ea-9bcc-728fafa27379.PNG)

**Comment by adrirock1141** [comment]
I just make it work by just 3 letter name and changing the extension of .gcode to .gco
maybe the fact that in my sd cards are folders may cause this error?

**Comment by luc-github** [comment]
error 0 is usually due to a reset of esp because of power supply stability
check: https://github.com/luc-github/ESP3D/issues/417

**Comment by adrirock1141** [comment]
> error 0 is usually due to a reset of esp because of power supply stability
> check: #417

ok thanks, ill try to put a external source, i have one question more  sorry jejej
there is anyway that ESP3D notifies when the 3d printer finish printing

![image](https://user-images.githubusercontent.com/30213125/78846496-fc8a2f00-79d9-11ea-9c06-d371c69fa755.png)

i dont know what are these for

**Comment by adrirock1141** [comment]
Hello i figured out the notification i read this [https://github.com/luc-github/ESP3D/wiki/Line](url) , the problem i have now it is that when i try to send a message it says, wrong command

![image](https://user-images.githubusercontent.com/30213125/78853475-f2bdf700-79ec-11ea-972c-ad2729920269.png)

when i send a message it doesnt work
![image](https://user-images.githubusercontent.com/30213125/78853532-11bc8900-79ed-11ea-80a8-50ee7cca10e1.png)

**Comment by luc-github** [comment]
Yes it means the token you have entered is wrong, did you setup it according wiki ? 
also please type `[ESP610]TS=NONE` to clear this ugly line

**Comment by adrirock1141** [comment]
> Yes it means the token you have entered is wrong, did you setup it according wiki ?
> also please type `[ESP610]TS=NONE` to clear this ugly line

Yes i follow the wiki
![image](https://user-images.githubusercontent.com/30213125/78894493-2293eb80-7a3b-11ea-96b3-cce3b5df1ceb.png)

**Comment by adrirock1141** [comment]
i try using this because in Line you only have T1, you dont use T2 and TS
[ESP610]type=LINE T1=xxxxxxxxxxxxxxxxxx T2=NONE TS=NONE
insted of the xxxxxxxxx i put the token of line
but stilll error
![image](https://user-images.githubusercontent.com/30213125/78895134-4b68b080-7a3c-11ea-8316-f7d490db8254.png)


i generate this token
![image](https://user-images.githubusercontent.com/30213125/78895287-8cf95b80-7a3c-11ea-858c-4124be97ea89.png)

**Comment by luc-github** [comment]
what ESP8266 board are you using?

**Comment by adrirock1141** [comment]
> what ESP8266 board are you using?

Node MCU V3 Lolin

**Comment by luc-github** [comment]
ok because before your wrote `NodeMCU V1.0` so you did not filled proper info
what about webUI version ? you wrote 2.0 and 2.1 but none of them is the full version 
![image](https://user-images.githubusercontent.com/8822552/78897931-41ae6f80-7a73-11ea-9ee2-ebe0cc19de53.png)

Also did you do any modification in it ? because  you were able to try to upload long file name which is definitly not possible

**Comment by adrirock1141** [comment]
> ok because before your wrote `NodeMCU V1.0` so you did not filled proper info
> what about webUI version ? you wrote 2.0 and 2.1 but none of them is the full version
> ![image](https://user-images.githubusercontent.com/8822552/78897931-41ae6f80-7a73-11ea-9ee2-ebe0cc19de53.png)
> 
> Also did you do any modification in it ? because you were able to try to upload long file name which is definitly not possible

i dont do any modification, i upload as it was
![image](https://user-images.githubusercontent.com/30213125/78898675-2d05b380-7a42-11ea-9680-c97e90f8a015.png)

**Comment by luc-github** [comment]
version 0.9.5!!!! to use with FW 2.1 use UI 2.1....
 so please update it you cannot use such old one use lastest 

and once done re enter you Line token

**Comment by adrirock1141** [comment]
how do i update it

**Comment by luc-github** [comment]
how did you installed it in first place ?

**Comment by adrirock1141** [comment]
> how did you installed it in first place ?

i just did it, i dont installed, i just flash the arduino file and now i read that ESP3D comes with a version but you have tu upload the old one

**Comment by adrirock1141** [comment]
Thanks so much for your help

**Comment by adrirock1141** [comment]
i was talking to early
the same problem 
![image](https://user-images.githubusercontent.com/30213125/78900347-b74f1700-7a44-11ea-8f38-e7416fe5f190.png)


![image](https://user-images.githubusercontent.com/30213125/78900272-9ab2df00-7a44-11ea-9455-a23bc148dc74.png)

**Comment by luc-github** [comment]
the upload is not done by me and neither automatic  - it is done by user as mentioned in https://github.com/luc-github/ESP3D#installation

Anyway now you have latest version and this version works so lets continue...
replace this file (remove the .txt extension - it is to allow to be uploaded) : 
[notifications_service.cpp.txt](https://github.com/luc-github/ESP3D/files/4456459/notifications_service.cpp.txt)
in ESP3D firmware then reflash your board and open arduino serial monitor to see the output
it will show your token so do not share here but verify it is correct
![image](https://user-images.githubusercontent.com/8822552/78902360-fcda0700-7a79-11ea-9401-7f8f76068c3f.png)




then in serial monitor type `[ESP600] Hi`

![image](https://user-images.githubusercontent.com/8822552/78902213-c56b5a80-7a79-11ea-81e0-a13472ba29b6.png)

**Comment by luc-github** [comment]
share the output but remove your token - it will says what is wrong

**Comment by adrirock1141** [comment]
i figured out, i reflash everything and now it works, i dont know why, but it works

**Comment by adrirock1141** [comment]
thanks so much

**Comment by adrirock1141** [comment]
its very weird if i dont use a Static Ip it works

**Comment by adrirock1141** [comment]
![image](https://user-images.githubusercontent.com/30213125/78905977-c043e680-7a4c-11ea-9e7a-0bbbeb2365b5.png)
before i put here a static ip and i put it 192.168.0.150, now that i reflash everything i leave like it was before, and put a static ip in the router
![image](https://user-images.githubusercontent.com/30213125/78906086-e5385980-7a4c-11ea-92a7-b17d380ef7fc.png)

**Comment by adrirock1141** [comment]
these are all the files that de WEBUI has to have or is something else
![image](https://user-images.githubusercontent.com/30213125/78906162-00a36480-7a4d-11ea-9c59-69a14f2e6f12.png)

**Comment by luc-github** [comment]
it may due to your default gateway is not set properly

yes they are, the 2 first are optionals the 3 last are mandatories, the 2 last are generated by webUI
