### ISSUE TITLE
[FEATURE REQUEST] NEXTION HMI Screen Integration

### ISSUE THREAD

**Issue by fabian222005** [luc-github/ESP8266#436]
Can you develop with NEXTION HMI SCREEN? Please

**Comment by luc-github** [comment]
can you elaborate, give more context ? 

* which version of Nextion?
* for which purpose?

**Comment by fabian222005** [comment]
Dear luc:
For function like a control panel like in this video [https://youtu.be/Kq1StPYwWfQ](https://youtu.be/Kq1StPYwWfQ) , is for Nextion Enhanced 3.2inch in Nextion editor 1.60.2

**Comment by luc-github** [comment]
Yes I know Marlin kimbra support nextion, it is used as display, I have already played with it 

but unless esp act like a host, what is your goal connecting nextion to ESP32 by serial and esp32 to printer by serial ?

I try to understand what would need to be displayed and what would be the usage of touch screen if ESP is not acting as host for streaming GCODE

Can you clarify ? I am curious

**Comment by fabian222005** [comment]
Yes, for control quickly the printer without another device, like a MakerBot replicator that have an useful screen and a useful app. For a quickly gcode preview like printing time or print dimensions or resume a print with only the height

**Comment by luc-github** [comment]
gcode preview? on Nextion it won't be possible

so nextion is for printer without screen?

**Comment by fabian222005** [comment]
Yes, is for a non screen printer like CNC machines
