### ISSUE TITLE
[FEATURE REQUEST] Add servo or stepper motor integration

### ISSUE THREAD

**Issue by fabian222005** [luc-github/ESP8266#437]
Can you add a servo or stepper motor support for change filament color?

**Comment by luc-github** [comment]
can you elaborate?
Please give more context and information.

**Comment by fabian222005** [comment]
For change filament color like prusa mmu or like [https://youtu.be/0F38WQUEaGs](here) but with a servo an another for another thing. For action a servo using a command like this [ESP500]S:(servo number) D:(Servo degree)

**Comment by luc-github** [comment]
Sorry I am not familiar with servo usage so it is not clear for me
 it is not something that is done already  by 3D printer Firmware ? like here https://marlinfw.org/docs/gcode/M280.html

**Comment by fabian222005** [comment]
Yes, but I don't like to modify stock hardware or firmware because is a big deal and risk to damage the printer

**Comment by luc-github** [comment]
yes but because this feature is already present on printer FW there is no point to add it to ESP3D
 I have no plan to support such feature and I have no bandwith for it, sorry
