### ISSUE TITLE
Replace eeprom with w25q128 possible??

### ISSUE THREAD

**Issue by tnap1979** [luc-github/ESP8266#438]
So I have a esp-01s with the small memory chip.. 1M I believe..
I have a bunch of RC FPV flight boards around, and one of them that's got a dead stm32f4 chip, has a w25q128 chip on it.. I have a hot air station and chip quick flux, can I just use the 128m chip in place of the w25q32 that is stated... I know it's over kill but it's all I have right now, and with the covid crap... I doubt I'd see my w25q32 chips anytime soon if I ordered them..

**Comment by luc-github** [comment]
esp8266 has 16MB board ( D1 mini pro) so w25q128 is supported - just be patient when doing the first time formating of SPIFFS

**Comment by tnap1979** [comment]
Sorry for the questions.. lol
How would I go about doing this?
This is my first ever attempt, I know how to use vscode for firmware compilation and arduino ide and such, but never messed chip replacing and reflashing other then my fpv flight controllers

**Comment by luc-github** [comment]
I did 4 esp01 with 512KB and put 4MB - I followed this https://www.youtube.com/watch?v=7Q6ABad7U6o&feature=youtu.be

I am not good with a soldering station, I did not used air gun,  I killed one board on the process but the 3 working reworked are ok



![P_20200229_144050](https://user-images.githubusercontent.com/8822552/79098678-ca265c00-7d62-11ea-96a3-f4af21323289.jpg)

**Comment by tnap1979** [comment]
I already have the chip installed, just need to know how to test if it works or not, never really messed with this kind of stuff, coding stuff in arduino, but I just got my raspberry pi 3b+ and camera... so I dunno if I even need to worry about this anymore...
But would still love to know how to test and program it, incase i can still use it for something later

**Comment by tnap1979** [comment]
its working fine, all is well
