### ISSUE TITLE
[FEATURE REQUEST] Telegram notification support

### ISSUE THREAD

**Issue by fjriosp** [luc-github/ESP8266#439]
It'll be nice if you implement notifications to Telegram.

I've try but I don't know why cannot connect to api.telegram.org:443 using the Notificationclient.

Here you can get all the info about send messages to a Telegram chat via a telegram bot:
https://medium.com/@xabaras/sending-a-message-to-a-telegram-channel-the-easy-way-eb0a0b32968

Create a public channel is optional, really you only need:
1. Create a bot using BotFather
2. Get the bot token (will be our _token1)
3. Create a chat group with YourCreatedBot and RawDataBot
4. Get the chat_id (will be our _token2)
5. Remove @RawDataBot from group

Now you have all the info to make the HTTPS GET request:
https://api.telegram.org/bot[_token1]/sendMessage?chat_id=[_token2]&text=[MY_MESSAGE_TEXT]

Of course, MY_MESSAGE_TEXT must be urlencoded.

Thanks a lot!

**Comment by luc-github** [comment]
@fjriosp are you refering to https://telegram.org/ ?
I will have a look, if it is like you describe, it should not be hard to add it

Ok tested with https command line and it seems Ok, I did not  do 
`5 - Remove @RawDataBot from group` , any reason to do that ?
if I remove it from group  I got :
`{"ok":false,"error_code":403,"description":"Forbidden: bot was kicked from the channel chat"}1`
So seems need to keep the bot in group

**Comment by fjriosp** [comment]
The only reason is to keep on the group only you and your bot.

RawDataBot is used only to get the chat_id.
You also could create a public channel with a custom name, then you can choice your own chat_id.

**Comment by fjriosp** [comment]
Here you have the info about getting the chat_id using RawDataBot.
https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id

**Comment by luc-github** [comment]
ho I see I misunderstood the @rawdatabot, I though it was the bot I created
actually I created public channel so I know the name of chatid.

**Comment by fjriosp** [comment]
It's ok.
Each user have to configure it's own bot and get the chat_id or create a public channel.
Both options will work.

**Comment by luc-github** [comment]
![image](https://user-images.githubusercontent.com/8822552/79209323-87888080-7e43-11ea-9b8b-ed6f7db95525.png)

implemented in 3.0 - but some rewrite will be done, because it use GET request , it need a new `String urlencode(String str)` function for the message text, and I do not know where to put it if need to be reused.
Currently  I have just dropped it in notifications_service.cpp `as it is`, may be try to move to a POST request  would remove the need of it (TBD)
Porting to 2.X may not be done as new feature go to 3.X
Finally I  need to write a proper setup page in Wiki 
I am busy on 3.0  WebUI currently, so I will see when I will do that

EDIT: moved to POST request - so removed unecessary urlencode function

**Comment by fjriosp** [comment]
Yeah! Thanks a lot!

I'll wait the 3.0 beta to try it.

Thanks!

**Comment by fjriosp** [comment]
I'm trying to get it working on 2.1
I'm using an ESP01 board but I'm getting this error on "Notificationclient.connect(_serveraddress.c_str(), _port)":

>M117 Connecting... 
>ip:192.168.1.210,mask:255.255.255.0,gw:192.168.1.1
>M117 192.168.1.210
>State:	sending Client Hello (1)
>Alert: handshake failure
>Error: SSL error 40
>Alert: unexpected message
>Error: SSL error 40
>Alert: close notify
>Error connecting server api.telegram.org:443
>pm open,type:2 0

Reading on internet it seems a certificate problem. Do you know how to fix it?

**Comment by luc-github** [comment]
on esp82866 need to set insecure

**Comment by fjriosp** [comment]
Now it's working.
Thanks!

**Comment by tokaphi** [comment]
hello, and thank you for your work, 
I just tested and it works very well
it is possible to add several groups ==> chat_id 1 ,chat_id 2  (token 2 token 3 ....) 
thank you

**Comment by luc-github** [comment]
what would be the user case?
why need many chat id?

**Comment by tokaphi** [comment]
to send notifications to several chat
private(perso) , public

**Comment by luc-github** [comment]
@tokaphi yes that I got it
but why need notification to many chat id ? 
I try to understand the user case

**Comment by tokaphi** [comment]
to notify people who are in different groups

Ex:  Pierre, paul, jacques 
pierre (chat A, privé)  paul (chat B , public)  jacques( chat A&B)

**Comment by luc-github** [comment]
c'est quoi l interet de poster la fin d'un travail d'impression ou de cnc  a plusieurs chat id, il y a deja plusieurs personnes dans le chat id, je suis desole je voudrais comprendre 
pourquoi pierre paul jacques ne sont pas dans le meme chat id si c est pour la meme imprimante, c 'est peut etre clair pour vous mais je ne saisis pas, d'ou ma question

**Comment by tokaphi** [comment]
On peut avoir differents groupes de discutions  avec des personnes differentes que l'on ne veut pas forcément avoir ensemble et comme le plugin telegram de octopi permet de le faire je me permettais de demander si il était possible de faire la même chose avec esp3d , une autre question serait-il possible d'envoyer une commande (demande de status par exemple ) via telegram ?

**Comment by luc-github** [comment]
pour le multi chanel id il suffirait de mettre   les channels id separes par des points virgules et on process les uns apres les autres mais je ne comprend toujours pas le cas d application. une autre solution : utiliser un bot de forward comme https://github.com/riverosroca/telegram-forward-bot
 ou 
ou le bot Fowarderbot

pour la commande de status je ne connais pas bien l api de telegram mais je pense qu'il faudrait ecrire un bot pour ca, le bot d envoi de message ne les lit pas.
donc il faut un bot qui recoit la commande et qui envoit une requete http a esp3d qui repond par une notification

**Comment by tokaphi** [comment]
j'avais testé le point virgule entre chanel id mais ça ne fonctionne pas actuellement , il prend seulement le premier.
pour le multi chanel ,ca permet aussi d'avoir par exemple un chanel en sourdine et pas l'autre .

**Comment by luc-github** [comment]
le point virgule ce n est pas implemente j 'ai dit que cela pourrait etre une solution,  cela eviterait de creer de nouveaux token

**Comment by luc-github** [comment]
@tokaphi je vais reposer la question car je voudrais vraiment comprendre et la je ne comprend pas:
Dans quel cas de figure a- t-on besoin de plusieurs chat ID pour une imprimante ?
>On peut avoir differents groupes de discutions avec des personnes differentes que l'on ne veut pas forcément avoir ensemble
 
Pourquoi ? 

>ca permet aussi d'avoir par exemple un channel en sourdine et pas l'autre

Ca veut juste dire qu'on en veut plusieurs mais pas pourquoi, 
Donc pourquoi un channel en sourdine et pas l'autre ?

>to notify people who are in different groups

Je ne dois pas etre habitue a telegram mais quel est le cas de figure ou des gens partageant les meme info sur une imprimante, sont dans differents chat ID/groupes , au lieu d'etre dans celui de l'imprimante ?

**Comment by tokaphi** [comment]
j'ai par exemple un projet de réalisation d'une CNC où j'imprime pas mal de piéces , j'ai un chanel sur lequel je partage mon projet et veux partager quelques infos de l'impression des differentes pièces, en même temps je voudrais remonter les infos aussi a mon système domotique qui va me permettre par exemple de faire sceenshoot ou éteindre une lumière etc... , dans ce cas je ne veux pas que mon chanel privé de ma domotique apparaisse parmis le chanel de la CNC et pour la sourdine ,  ex le chanel CNC est en sourdine car je ne veux pas etre notifier toutes les 2 minutes par les différents membres en revanche je veux toujours avoir l'info de mon imprimante ..  

en fait , je découvre ESP3D et pensais que je pouvais etre notifié par exemple une impression qui plante , impression qui démarre , impression fini .... mais ce n'est peut être pas le cas ?

**Comment by luc-github** [comment]
pour le moment il y 2 type de notif 
1 - autonotif : qui envoit l'ip de l'esp au demarrage, dans GRBL_ESP32 et dans MARLIN_ESP32 il peut y avoir plus de notifications 
2- la notification manuelle a mettre dans le slicer ou toute appli qui controle l'impression 
`[ESP600]<le message de la notification>`
Contrairement a octoprint ESP3D n'est pas un host sur une carte fille, il envoit des requetes GCODE via le webUI, / telnet a l'imprimante/cnc par serial  pour connaitre le status  ou reagit a des commandes `[ESPXXX]`, dans dans GRBL_ESP32 et dans MARLIN_ESP32 la c'est different car si on imprime depuis la SD il y a plus de possibilitees (c'est implemente dans GRBL_ESP32 mais pas encore dans ESP3DLib pour MARLIN_ESP32)

**Comment by luc-github** [comment]
Documentation is done https://github.com/luc-github/ESP3D/wiki/Telegram
