### ISSUE TITLE
[Question]-compiled, uploaded, but get nothing from device... no wifi ssid shows up...

### ISSUE THREAD

**Issue by tnap1979** [luc-github/ESP8266#441]
what could be the issue??
it now uploads, i followed all directions, and everything compiles and uploads, but no hotspot or esp ssid shows up, ive tried to upload and recompile 3 times, and it succeeds but does not do anything afterwards

**Comment by luc-github** [comment]
as said you have a big flash, first time  spiff is formated and can take a long time 
when spiff is formated esp hotspot will show

**Comment by tnap1979** [comment]
https://www.amazon.ca/gp/product/B07KF119YB/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

**Comment by tnap1979** [comment]
aprox how long do i leave it ??
10min. ? 20?

**Comment by tnap1979** [comment]
its been 10min. since arduino ide said soft resetting
the device i have doesnt have a reset button, just a switch to go from uart mode to program mode
and there is still no esp wifi showing up in my phone or my tablet or laptop

**Comment by tnap1979** [comment]
there isnt even any flashing light either

**Comment by tnap1979** [comment]
so i just flashed the esp8266 blink sketch, and the led is blinking, so this tells me the device is functional...
but why does there not show any esp wifi hotspot...
this is a dilemma i have no idea how to solve

**Comment by luc-github** [comment]
enable debug mode and çheck what serial output said on serial monitor

**Comment by tnap1979** [comment]
also just flashed with the esp8266 wifi ap sketch
it does show up in wifi lists, in a matter of 2min max...
is there something im doing wrong here??
am i supposed to edit or configure anything in the sketches of esp3d before i upload to the unit ??
ive followed all the directions and it doesnt seem to work for me?
about ready to give up and just bin this thing

**Comment by tnap1979** [comment]
ok, ill try the debug mode now

**Comment by tnap1979** [comment]
heres the results of the debug

17:55:29.984 -> 
17:55:29.984 -> SDK:2.2.2-dev(38a443e)/Core:2.6.3=20603000/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-16-ge23a07e/BearSSL:89454af
17:55:34.047 -> mode : softAP(8e:aa:b5:0d:da:f9)
17:55:34.047 -> add if1
17:55:34.047 -> dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
17:55:34.047 -> bcn 100
17:55:34.187 -> bcn 0
17:55:34.187 -> del if1
17:55:34.187 -> usl
17:55:34.187 -> add if1
17:55:34.187 -> dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
17:55:34.187 -> bcn 100
17:55:42.689 -> 
17:55:42.689 ->  ets Jan  8 2013,rst cause:4, boot mode:(1,7)
17:55:42.689 -> 
17:55:42.689 -> wdt reset

**Comment by luc-github** [comment]
can you use core 2.5.2 , you are using 2.6.3
________________________________

**Comment by tnap1979** [comment]
It wont upload with 2.5 .2

https://drive.google.com/file/d/1CRySIPrWaEPLniC2nPoNOiYkG4KksvTc/view?usp=drivesdk

**Comment by luc-github** [comment]
cannot see the fille
________________________________

**Comment by luc-github** [comment]
looks like gpio0 is not set to gnd, it works with 2.5.2

**Comment by tnap1979** [comment]
How would I fix that up? I have no clue tbh

**Comment by luc-github** [comment]
unplug esp board then replug  and retry to flash, it happen sometime upload failed, just retry solve the problem

**Comment by luc-github** [comment]
,@tnap1979 any update?

**Comment by tnap1979** [comment]
it still fails to upload,
i even tried shorting gpio0 to gnd on the esp-01s

**Comment by luc-github** [comment]
how do you flash your esp01?

**Comment by tnap1979** [comment]
With a usb stick programmer..
I sent the amazon link to the device I use in a previous comment :-)
It's a programmer that has a switch to go from uart mode to program mode

**Comment by luc-github** [comment]
there is no reason you can flash With 2.6.3 and not 2.5 .2, are you able to flash again with 2.6.3?

**Comment by tnap1979** [comment]
I'll give it a shot again

**Comment by nlovrens** [comment]
Hi. I am having the same issue. Tried on two ESP01 boards. Both with version 2.6.3 and 2.5.2. On both version I have successfully flashed the board but there is an issue with AP signal broadcast. Wifi AP goes up for a brief second and then down again, after that broadcast randomly goes up-down, but there is no time to connect with the PC. I am using inSSIDer for wifi scan and I can see the signal (screenshot attached). 
![Capture](https://user-images.githubusercontent.com/20867277/79447640-745ee780-7fe0-11ea-8756-596b80d50a52.JPG)

I have tired WiFiAccessPoint example on the same board and it works normally.

**Comment by luc-github** [comment]
@nlovrens please open a new issue it is hard to help 2 different people on same thread
@tnap1979 has different symptoma than yours as he use a reworked ESP01-> using 128Mb flash and has issue to flash 2.5.2 core
On my side I have no problem with 2.6.3 neither 2.5.2 on reworked ESP01 512KB -> 4MB flash
so need to debug individually to find out your separate problem

**Comment by nlovrens** [comment]
ok, thank you. I will open new ticket

**Comment by luc-github** [comment]
@tnap1979 any update?

**Comment by tnap1979** [comment]
I gave up and moved onto getting klipper installed and running... to much
trouble for this little thing.. lol
Thanks for all the help tho

**Comment by luc-github** [comment]
ok happy printing then
