### ISSUE TITLE
FR100% still displayed when verbose turned off

### ISSUE THREAD

**Issue by jimhiggs** [luc-github/ESP8266#449]
Not sure if this is a bug or not. After first connecting ESP3D to my printer  I see the positions and FR100% continuously scrolling in the console/terminal window. Clicking off verbose stops the position statements but the FR100% reports keep on coming which is frustrating because it scrolls off screen other stuff I am trying to monitor/read

**Comment by luc-github** [comment]
what is your configuration when happen , how esp is connected ?
screenshot ?
some context would help

**Comment by luc-github** [comment]
I am guessing you use BTT TFT which poll and broadcast lot of data in recent versions
Web UI do not consider it is a verbose info - I have moved it to verbose info in latest web-ui 2.1, so it is now hiden when uncheck verbose in web ui

please check latest git : https://github.com/luc-github/ESP3D-WEBUI/tree/2.1

**Comment by jimhiggs** [comment]
Thanks luc-github. I am very new to github and I tried for an hour to work out how to merge the webui  repository with the latest esp3d and couldn't get it to compile so got some learning to do before progressing.

**Comment by luc-github** [comment]
read carefully the readme of each repository: ESP3D and ESP3D-WebUI, unless you do code modifications, you do not need to 'merge' / 'compile' anything
I rebuild the index.html.gz almost for each changes multi lang is at root of repository and splited languages are in splited language directories

if you use only ESP3D git, you need to type
`git submodule update --init` to sync ESP3D-WebUI repository

**Comment by jimhiggs** [comment]
Great thank you again.
