### ISSUE TITLE
PlatformIO Settings

### ISSUE THREAD

**Issue by ModMike** [luc-github/ESP8266#456]
Sorry about the dumb question, I haven't touched PlatformIO in 18 months.

Do I need to change the board ID to match my Wemos D1 Mini or leave as is?

Thanks!

**Comment by ModMike** [comment]
Never mind, bad USB cable!

**Comment by luc-github** [comment]
Wemos D1 Mini is standard esp8266  so the default settings I have set should work
no need to change

**Comment by ModMike** [comment]
Thanks, found the link and sent donation.

I uploaded ESP3d 2.1 and the blue light doesn’t flash and I don’t see it on network anymore.

**Comment by luc-github** [comment]
did you unplug replug after flash ?

**Comment by ModMike** [comment]
Sorry, it took awhile for network to see it, now it works perfect. Just need to upload Spiffs file. By the way, you show a logic level converter in the instructions but my board looks different. Do I still need it if my Fystec Cheetah board has a USB header with 3.3v?

**Comment by luc-github** [comment]
the logic converter is only necessary if you printer board is 5V based, if it is 3.3v on GPIO there is not need

**Comment by luc-github** [comment]
>Thanks, found the link and sent donation. 

@ModMike thank you, which link: paypal or sponsor ?

**Comment by ModMike** [comment]
I did PayPal but can sponsor your amazing work if you like. Certainly worth it.

Sorry for another dumb question. I need to upload the spiffs file to get web UI right? Where do I find it?

Sorry I slept 2 hours and can't think straight.

**Comment by luc-github** [comment]
Paypal ? -strange I should have been received it but do not see it - may be need time 
  
this one you need is https://github.com/luc-github/ESP3D-WEBUI/blob/2.1/index.html.gz

**Comment by ModMike** [comment]
Can you please check you account and let me know if you got it?

**Comment by luc-github** [comment]
Yes got it thank you ^_^

**Comment by ModMike** [comment]
Ok everything up and running. Please excuse my stupidity, I feel like I was drugged today.

**Comment by luc-github** [comment]
you need a rest ^_^

Ok my time to sleep then - have a good afternoon

**Comment by ModMike** [comment]
Salut mon ami!

**Comment by ModMike** [comment]
Plugged into board except need to figure out voltage issue. Right now powering each one from separate usb.

I don't see SD card but that's probably because of setup or 8.3 format. If I want to enable ESP3d-WebUI but want ESP3d to manage wifi do I just do the following in Marlin?:

`/#define WIFISUPPORT         // Marlin embedded WiFi managenent
#define ESP3D_WIFISUPPORT   // ESP3D Library WiFi management (https://github.com/luc-github/ESP3DLib)

#if EITHER(WIFISUPPORT, ESP3D_WIFISUPPORT)
  #define WEBSUPPORT          // Start a webserver (which may include auto-discovery)
  #define OTASUPPORT          // Support over-the-air firmware updates
  #define WIFI_CUSTOM_COMMAND // Accept feature config commands (e.g., WiFi ESP3D) from the host`

Why is this even needed if it talks to Marlin perfectly as is? It is already responding to commands with it off.

**Comment by luc-github** [comment]
no, Marlin settings you mention are for Marlin installed on ESP32 board and using ESP3DLib not ESP3D

check M20 is working this is what ESP3D WebUI use to list files so 8.3 format has no impact as Marlin only list 8.3 format with M20 and print commands

**Comment by luc-github** [comment]
@ModMike is it working now?

**Comment by ModMike** [comment]
It’s working perfectly! I just need to get the voltage issue sorted out. Right now it only works if I give it per form it’s own USB connection, which is 5V.

I tried taking power from the 3.3V pin on the board but it does not work. I am hesitant to use the 5V. The board is also different than the one you have, but the name is the same.

![Wemos D1 Mini front](https://user-images.githubusercontent.com/36581178/81092674-fa2ece00-8ece-11ea-8711-b1b99048f721.jpg)

![Wemos D1 Mini Back](https://user-images.githubusercontent.com/36581178/81092680-fe5aeb80-8ece-11ea-8b7d-117fee12af46.jpg)

I did measure the TX and RX pins on the controller and they are at 3.3 so all good there. If only I could power it off of 3.3V I would be good to go.

**Comment by ModMike** [comment]
Update: Got to work on 3.3v, had an intermittent connection.

This board is perfect!

**Comment by luc-github** [comment]
That is weird here they write it can be done https://www.reddit.com/r/esp8266/comments/7ywmeg/powering_wemos_d1_mini_with_lifepo4_33v/

**Comment by ModMike** [comment]
Check comment above your post.

**Comment by luc-github** [comment]
ok so I guess issue can be closed
^_^

**Comment by ModMike** [comment]
Yes sir, thank you for your patience. It's been a long week :-)
