### ISSUE TITLE
Printer doesn't communicate with ESP3D

### ISSUE THREAD

**Issue by Arthur75012** [luc-github/ESP8266#457]
Hello,

I'm using ESP3D on a ESP01 connected to a gt2560 board with marlin on it.

The commands works fine, I can do home and control the temp but it seems that the informations goes only in one way : from the ESP3D to the printer. The other way doesn't work, the printer doesn't send any info... I can't see or upload (even with 8.3 file format) files in the SD card, the graph temp stay empty and nothing appear on the command pannel.

I try M115 or M20 and nothing happens
![image](https://user-images.githubusercontent.com/64860026/81096193-53662400-8f06-11ea-834a-44205eb6d4c9.png)

**Comment by Arthur75012** [comment]
Also the printer panel stay empty too : 
![image](https://user-images.githubusercontent.com/64860026/81096610-f028c180-8f06-11ea-871a-9ba98bbbf949.png)

**Comment by luc-github** [comment]
looks like wiring issue check your TX on your printer  and RX on your ESP 
as you did not fill the issue template which give informations about your situation - I cannot  say more

**Comment by Arthur75012** [comment]
The wire seems to be ok y checked the continuity between the esp TX, RX and the FTDI pin on the board (the board doesn't have TX and RX pin). I even try to invert the TX RX cable but in this case nothing works...

I can't really understand how it can work fine from the ESP3D to the printer but not in the other way. If the wire were bad nothing would work right ?

Sorry i'm really a beginer so what info do you need ?

**Comment by luc-github** [comment]
when you open bug issue there is a template of info to fill.

* esp tx->printer rx = esp send commands
this part looks ok per your feedback

* printer tx -> esp rx = printer answer esp
this part seems not working

it is wire / connection  issue
be sure doing this if your serial is shared with usb that usb is not connected

**Comment by Arthur75012** [comment]
Ok I effectively had a bad wiring 

Everything works fine thank you !

**Comment by luc-github** [comment]
ok great, have fun :smile_cat:
