### ISSUE TITLE
[BUG] 8.3 ERROR

### ISSUE THREAD

**Issue by JartX** [luc-github/ESP8266#458]
<img width="2556" alt="Captura de pantalla 2020-05-09 a las 18 44 56" src="https://user-images.githubusercontent.com/8399211/81479717-45c1de80-9225-11ea-8f79-c822334be101.png">

I want to upload a file.gco but it always says it, i can read the sd files but i cant upload

**Comment by JartX** [comment]
<img width="1316" alt="Captura de pantalla 2020-05-09 a las 19 05 06" src="https://user-images.githubusercontent.com/8399211/81480150-08ab1b80-9228-11ea-9668-a7da738519d3.png">

Same message :(

**Comment by luc-github** [comment]
this is not a bug you need to use 8.3 name format because this is the only one supported by Marlin
8 chars for name + 3 chars for extension

the pinned issue explain that

**Comment by JartX** [comment]
<img width="1508" alt="Captura de pantalla 2020-05-09 a las 19 12 57" src="https://user-images.githubusercontent.com/8399211/81480305-26c54b80-9229-11ea-9c65-96319b7bf370.png">

Not Work :S

**Comment by luc-github** [comment]
I do not see the error message - so what is `not work?`

**Comment by JartX** [comment]
When I try to also upload that file, the error that I have put above it all appears, I have also tried for example ARMSS112.gco and it does not work either, it always gives me the error of 8.3

**Comment by luc-github** [comment]
fill the issue template to get support without any information it is not possible to help

**Comment by JartX** [comment]
Solved... macOS was adding a hidden extension .gcode after edit the name, many thanks for your help, and sorry for it
