### ISSUE TITLE
[FEATURE REQUEST] Add BME280/BMP280 support

### ISSUE THREAD

**Issue by nanogennari** [luc-github/ESP8266#464]
BME280 and BMP280 sensors are much more reliable than DHT11 and DHT22, it would be nice to have support.

**Comment by luc-github** [comment]
do you have a recommended library for esp32 and esp8266?

**Comment by nanogennari** [comment]
The library Adafruit_BME280 (https://github.com/adafruit/Adafruit_BME280_Library) is in the Arduino repositories and it is quite simple to implement.

**Comment by luc-github** [comment]
need also sensor library from adafruit...
________________________________

**Comment by luc-github** [comment]
this one looks more monolitic : https://github.com/MartinL1/BMP280_DEV

**Comment by luc-github** [comment]
I need to think how to do more generic sensor support/interface, there is also https://github.com/luc-github/ESP3D/issues/432
Current sensor  support is focused on DHT but would be better to make more  generic for communication with webUI - As sensor support is not yet done in webUi 3.0 there is some time to think - TBD

**Comment by luc-github** [comment]
Also I do not have any BMP280 device for the moment...

**Comment by nanogennari** [comment]
If you need i can test and debug any code for the BME/BMP sensor. The idea of generic sensor support is nice, i even tried to alter your code to add it myself but like you said the code is too focused on the DHT, anything i could do would be too jerryriged in place.

> this one looks more monolitic : https://github.com/MartinL1/BMP280_DEV

This library looks nice also, and it has some extra features. Although i use BMEs frequently, I'm not very intimate with programming for it, normally i use it with tasmota and extract the data via MQTT (mqtt support would also be nice, something like a simple json telemetry with printer and sensor status).

**Comment by luc-github** [comment]
I have ordered one BMP280 and one BME280 3.3V and will got them next week, I will prepare the code to support them and make output more generic for WebUI

**Comment by nanogennari** [comment]
Nice, looking forward to it...

**Comment by luc-github** [comment]
@nanogennari what sensor do you have BMP or BME ?
It seems I only got BMP sensors which do not have the humidity support

**Comment by luc-github** [comment]
Implemented in FW - now I will update webUI to display it in notification area
