### ISSUE TITLE
Printer do not connect 

### ISSUE THREAD

**Issue by ghost** [luc-github/ESP8266#465]
Hi, I have a board arduino mega2560 WIFI with an esp8266, on the arduino I have a board RAMPS1.6. ESP3D is working but he can't connect to the printer. I can send commands to the ESP.

No information give from the printer.
![image](https://user-images.githubusercontent.com/57861042/82726258-0b574780-9ce3-11ea-880c-ccf357b5c516.png)

I think the ESP FW is in version 2.1 same for the WEBUI

The frimware of the printer is Marlin 2.0

**Comment by luc-github** [comment]
please fill propely issue template
