### ISSUE TITLE
Using SD card from smoothiebord

### ISSUE THREAD

**Issue by sns5400** [luc-github/ESP8266#469]
After upload and change my rx/tx pins i can see rx and tx communication from printer to esp web interface. Temp information from head and bed is arriving i can move and home in X,Y,Z directions.
For the SD card i have a problem, must i do some special actions before i can read and write to the smoothiebord sd card ?

in the web interface it say:
![Screenshot from 2020-05-26 07-59-15](https://user-images.githubusercontent.com/13086722/82868829-96c41900-9f2d-11ea-81e0-237c0655e5a6.png)

**Comment by luc-github** [comment]
nothing you set smoothiware as target is should be enough

what version of esp3d and  what version of web ui?

**Comment by sns5400** [comment]
Do you mean i change in config.h
#define DEFAULT_PRIMARY_SD  2  --> 1
#define DEFAULT_SECONDARY_SD 1 --> 2

UI: 0.9.5 / FW: 2.1.0.b39

**Comment by luc-github** [comment]
*   do not change these settings in config.h they are not for configuration purpose
*  use UI which match the FW : FW 2.1 based must use UI 2.1 based, not such old one

**Comment by sns5400** [comment]
i thinks it work now, going to test
![Screenshot from 2020-05-27 10-42-20](https://user-images.githubusercontent.com/13086722/83000351-8170ec80-a00a-11ea-966f-9605d3bf39cd.png)

**Comment by luc-github** [comment]
great I close ticket then
