### ISSUE TITLE
unable to connect to access point

### ISSUE THREAD

**Issue by mike303625** [luc-github/ESP8266#471]
as above using node mcu 8266 compiled in visual studio and platformio no problems and no changes to code, uploaded to node mcu and can see access point in wifi network, all good so far
submit default password (12345678) to connect but get the unable to connect message??
has the default password changed??
thanks in advance

**Comment by luc-github** [comment]
try to reset board settings with [ESP444]RESET
AP password is still 12345678

**Comment by mike303625** [comment]
did a hard reset and reuploaded via arduino ide , I can connect now ? thanks
once I get it working I will try another board with platformio

**Comment by luc-github** [comment]
so issue can be closed ?

**Comment by mike303625** [comment]
yes thanks
