### ISSUE TITLE
Can not upload a file to SD card in a subdirectory

### ISSUE THREAD

**Issue by sns5400** [luc-github/ESP8266#472]
**Describe the bug**
I try to upload a file to a subdirectory on the SD card in my MKS smoothiebord.

I create a subdirectory with a capital letter in the name "Gcode". In the view i see only "gcode"

I try to upload a file to the SD / , this function is ok but very slow.
Remove the subdirectory "gcode" and recreate a subdir "gcode" = ok.
Change the view to the subdirectory by double click on the gcode subdirectory name = ok.
On top of the SD card view the path= /sd/gcode/  ok.
Then i try to upload a file with name "blokje.gco"  to my subdirectory "gcode" and i get a error:
"Upload failed"
"No SD card detected"

**To Reproduce**

**Expected behavior**

**Screenshots**

**ESP3D Firmware:**
- ESP core version: 2.0.1.b39
- Web UI Version:UI 2.1.b60  
- Wifi mode:STA fix ip adress  
- Any change done in FW 
 i change the RX and TX pin numbers to GPIO16 and GPIO17 of the ESP-WROOM_32 because have problems with default in config.h.

**Target Firmware:**
 - Name: MKS Smoothiebord
 - Version 1.3

**Board used (please complete the following information):**
 - MCU: ESP-WROOM-32
 - Bord: FireBeetle-ESP32 
 - Flash size: no info

**Comment by luc-github** [comment]
please screenshot the error

**Comment by sns5400** [comment]
Here are the screenshots:

![Screenshot from 2020-05-28 17-54-59](https://user-images.githubusercontent.com/13086722/83164456-89b15080-a10c-11ea-8e6d-b88b20510364.png)
![Screenshot from 2020-05-28 17-54-40](https://user-images.githubusercontent.com/13086722/83164477-8e760480-a10c-11ea-8493-c7851ea0f732.png)

**Comment by luc-github** [comment]
what Smoothieware answer if you type `ls sd/gcode/`

**Comment by sns5400** [comment]
![Screenshot from 2020-05-28 20-39-40](https://user-images.githubusercontent.com/13086722/83180293-82e20800-a123-11ea-9600-eb4537eb1d90.png)

**Comment by sns5400** [comment]
![Screenshot from 2020-05-28 20-41-59](https://user-images.githubusercontent.com/13086722/83180472-c3da1c80-a123-11ea-8ec9-a84b67aba888.png)

**Comment by luc-github** [comment]
As you can see smoothieware cannot open the subdirectory - I do not know why but it not linked to ESP3D

**Comment by luc-github** [comment]
try with another name of directory many be - name `gcode` could be the problem

**Comment by sns5400** [comment]
i try with the name test, same problem, is this a problem for arthur Wolf ?

**Comment by sns5400** [comment]
when i give a command pwd it give me the path to my subdirectory
![Screenshot from 2020-05-28 21-38-26](https://user-images.githubusercontent.com/13086722/83185699-a3ae5b80-a12b-11ea-86f4-7960a22284f9.png)

**Comment by luc-github** [comment]
does `ls /sd/gcode` is ok?

**Comment by sns5400** [comment]
Hello,
I copy on my pc 2 files on the sd card  1 in each directory
 in subdirectory "test" i put blok2.gco
in subdirectory "gcode" i put blok1.gco

Then i put the sd card back in my MKS smoothiebord and launch.
I have the follow result:
==  copy from screen  =========================================================
pwd
/
ls /sd/test/
Could not open directory /sd/test/
ls /sd/test
blok2.gco
ls /sd/gcode
blok1.gco

============================================================================
so this work normal

**Comment by luc-github** [comment]
seems syntax changed since implemeted - I will add the fix for the path in webUI

**Comment by sns5400** [comment]
![Screenshot from 2020-05-29 08-53-28](https://user-images.githubusercontent.com/13086722/83230377-ef8fed80-a189-11ea-94c0-78c7f827cd54.png)

i can even start the file for printing

**Comment by luc-github** [comment]
yes the sd check use the `ls sd/gcode`  command to check it can start upload but now this syntax seems no more working - looking at doc it seems it is `relative path` syntax but was ok when I did several years ago - need to change the check command by adding the `/` and will be back to normal I did not do such test since I implemented

**Comment by luc-github** [comment]
I do not have a smoothieware available right now 
can you confirm this version :
[index.html.gz](https://github.com/luc-github/ESP3D/files/4700233/index.html.gz)
fix the problem ?

**Comment by sns5400** [comment]
no good even worse, it double the sd/

File not found: /sd/sd/test/blok2.gco
ok
ls sd/
Could not open directory /sd/sd/

**Comment by luc-github** [comment]
that is weird I do not double anything but just add "/" in from of path and be sure last char of path is not "/"

what actions are you doing ?
On my side I refresh SD:
![image](https://user-images.githubusercontent.com/8822552/83245764-7c927100-a1a1-11ea-9e63-03ca0a11958a.png)

then I created gcode sub directory:
![image](https://user-images.githubusercontent.com/8822552/83245856-9df35d00-a1a1-11ea-8693-1cd1c81185bb.png)

then go to gcode sub directory  and upload small file:
![image](https://user-images.githubusercontent.com/8822552/83245987-c8451a80-a1a1-11ea-89c8-0421e4c81b9c.png)

I have also press print button:
![image](https://user-images.githubusercontent.com/8822552/83246094-eca0f700-a1a1-11ea-8e3c-3347cb65f32c.png)

This is what you described initially and It is working now

**Comment by sns5400** [comment]
i test again afthernoon bizar

**Comment by sns5400** [comment]
Hello, have tested this morning and have strange results. The double are disappeared bizarre anyway working with last version UI 2.1.b61 / FW 2.1.0.b39
When i ask ls in root there is no difference using / at end of command
When i do this for a subdirectory there is a difference
![Selection_008](https://user-images.githubusercontent.com/13086722/83321678-99867d00-a251-11ea-9237-61138cd0b588.png)
![Selection_009](https://user-images.githubusercontent.com/13086722/83321683-9e4b3100-a251-11ea-993f-c1a70aaa846b.png)

**Comment by luc-github** [comment]
@sns5400 I did not change smoothieware commands, typing them will always give same result because they are smoothieware firmware commands

I changed webUI so please use webui to try to upload and list directory - do not use the terminal, the terminal commands were to debug what happened

**Comment by sns5400** [comment]
ok sorry i have not understand your action correctly. Have just tested, the new web interface seems to work, the transfer speed is very low but that is an other problem.
![Selection_013](https://user-images.githubusercontent.com/13086722/83324531-1c193780-a266-11ea-8ed0-11203d3dd6a7.png)
![Selection_014](https://user-images.githubusercontent.com/13086722/83324535-1f142800-a266-11ea-80c2-bffb8cab9b54.png)

even refresh after uploading the file in a sub directory.
Thank you

**Comment by luc-github** [comment]
Great, thank you - I have updated webUI  git with the fix https://github.com/luc-github/ESP3D-WEBUI/commit/db672f36ae13fa95d7020f32c74ee932d87ea0fb
