### ISSUE TITLE
[FEATURE REQUEST]Add pre defined options in platformIO for flash size / type

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#478]
Current platformIO.ini is for 
ESP8266 4MB Flash
ESP32 4MB Flash SPIFFS
Add entries for easily compile without modify platformIO.ini
for :
 * ESP01
 * ESP8266 16MB
 * ESP32 16MB Fat
 * Rename firmware.bin to MksWifi.bin for MKS target per https://github.com/luc-github/ESP3D/issues/716
 * TBD 
Is there a need for another target ?

**Comment by DivingDuck** [comment]
Maybe ESP32-Cam?

**Comment by luc-github** [comment]
@DivingDuck for PSRAM ?

**Comment by DivingDuck** [comment]
Yes, but maybe I was misunderstanding and reading too fast (I was looking for a more specific setup for ESP32-Cam) .

**Comment by luc-github** [comment]
you can do lot of setup for esp32cam and they most  need to be done in configuration.h
Here it is more about platformIO and hardware config
the platformIO.ini is not really intuitive if you do not know what to fill for hardware - in arduino ide all possibilities are in menu when in platformIO.ini you need to type the right flag which has not always easy to find documentation

**Comment by luc-github** [comment]
using https://luc-github.github.io/#/config/features solve the issue |
So I close the ticket
