### ISSUE TITLE
Does anyone know how to flash esp3d into ESP-12S from MKS?

### ISSUE THREAD

**Issue by rosellonsito** [luc-github/ESP8266#482]
![IMG20200708181721](https://user-images.githubusercontent.com/27849682/86944064-84054c80-c147-11ea-9d66-cef692d938d5.jpg)
I've bought this wifi module and I cant even connect via Arduino...
Any help?
Thanks!

**Comment by luc-github** [comment]
https://github.com/luc-github/ESP3D/wiki/ESP8266-12E-F should work

**Comment by luc-github** [comment]
@rosellonsito did you managed to flash ?

**Comment by luc-github** [comment]
I guess yes
