### ISSUE TITLE
class HardwareSerial' has no member named 'pinMode'

### ISSUE THREAD

**Issue by davidhuang2003** [luc-github/ESP8266#484]
#define NUMREADINGS 25
int senseLimit = 1023;

int probePin = 5; //analog pin 5 is the antenna pin
int val = 0; //reading from probePin

//Pin Connections to LED graph
int LED1 = 11;
int LED2 = 10;
int LED3 = 9;
int LED4 = 8;
int LED5 = 7;
int LED6 = 6;
int LED7 = 5;
int LED8 = 4;
int LED9 = 3;
int LED10 = 2;
int readings[NUMREADINGS]; //Reads values from analong input
int index = 0;    //Index of current reading
int total =  0;   //Running Total
int average = 0;  //Final average of the probe reading

void setup()
{
  int pinMin = 2;
  int pinMax = 11;
  for (int i = pinMin; pinMin <= pinMax; i++)
  {
    pinMode(i, OUTPUT);
  }

  Serial.pinMode(9600); // Initiate serial connection with IDE for debugging

  for (int i = 0; i < NUMREADINGS; i++)
  {
    readings[i] = 0; // initialize all readings to 0
  }
}

void loop() 
{
  val = analogRead(probePin);  //Takes reading from probe 
}
Context: Making a very basic electromagnetic wave sensor from a book
I'm running into the error 'class HardwareSerial' has no member named 'pinMode' and I'm unsure what to do

**Comment by luc-github** [comment]
I think you are in wrong repo - this not related to ESP3D at all
