### ISSUE TITLE
How can I wipe the SPIFFS with a bin file?

### ISSUE THREAD

**Issue by rosellonsito** [luc-github/ESP8266#485]
I had the esp3d v2.1 and I saw the 3.0 version, so I updated first de webui to v3 to then upload the esp3d v3 and I cant do anything and if I try to downgrade I have the same SPIFFS, Is it possible to wipe it with a bin file? I upload the firmware to the mks wifi module with the sdcard. 
Any help? 
I can't downgrade the webui version because i dont have access to the main page
![Captura](https://user-images.githubusercontent.com/27849682/88393515-0afc2b00-cdbe-11ea-925c-2bd6b4cd43c7.JPG)

**Comment by luc-github** [comment]
use the maintenance page : `http://<yourIP>?forcefallback=yes`

![image](https://user-images.githubusercontent.com/8822552/88396956-8ca28780-cdc3-11ea-97d2-7b9876aede0d.png)

**Comment by rosellonsito** [comment]
Oh my god! Awesome, I didn't know that.
Thank you very much!
