### ISSUE TITLE
[BUG]SD card no refesh and uplod files

### ISSUE THREAD

**Issue by DrumClock** [luc-github/ESP8266#486]
Hi ,I have an ESP-01S WiFi module connected to the Touch Screen TFT 50 V3.0
However, I can't see any files on the SD card or upload to the card. 

The other panels Cntrols, Temperatures, Extruders and Commands work without problems.

![ess](https://user-images.githubusercontent.com/64655979/88656675-fa56f800-d0d0-11ea-863b-f1571890e688.png)

![ESP](https://user-images.githubusercontent.com/64655979/88656692-004cd900-d0d1-11ea-9863-e5570a0407cc.png)

![statu](https://user-images.githubusercontent.com/64655979/88657179-cc25e800-d0d1-11ea-82d7-cec808f5413f.png)

**Comment by luc-github** [comment]
1 - your FW version is very old and I guess you webUI is also very old as you did not fill the template information 
please update using latest git of each one

2 - Also check if M21 then M20 commands list the SD content in console command - to see if SD is accessible

3 - which SD card are you refering to : Printer SD or TFT SD ?

**Comment by DrumClock** [comment]
Hi,
1) how do I update the FW Wifi module?

2) reaction to M21 and M20:

**M21**
ok T:23.84 /0.00 B:23.91 /0.00 T0:23.84 /0.00 T1:23.44 /0.00 @:0 B@:0 @0:0 @1:0
echo:No SD card

**M20**
Begin file list
End file list
FR: 100%

3) The SD card is inserted in the TFT touch screen

**Comment by luc-github** [comment]
1 - please read the read me of the github
2 - M21 mount printer SD card and it says you have none, M20 list printer SD card and as you have none it does not show any
so it is normal
3 - if you want to list SD card of tft you must use `M20 SD:` instead but this only supported in latest git version of ESP3D and latest git version of ESP3D-WEBUI - so you need to update both
but you can list in console  to check is working
4 - the SD upload on TFT is not supported in BTT FW currently, you can only upload on Printer SD

**Comment by DrumClock** [comment]
**3- Hi, `M20 SD: `command is functional in the console.**

**M20 SD:**
Begin file list
T1_Valec.gcode
T0_Valec.gcode
DUAL_Valec.gcode
++ servo center ++ .gcode
End file list
X: 160.00 Y: 135.00 Z: 21.20 E: 0.00 Count X: 12800 Y: 10800 Z: 42400
FR: 100%

**4- Unfortunately, my board does not have an SD card**
Do you know when support for SD FTF upload will be available?

**Comment by luc-github** [comment]
3 - yes as you use TFT 50 - I was guessing you have latest FW which has my PR for TFT SD and TFT USB
but you still need to update your ESP with latest version of FW and webUI to get proper interface

4 - Sorry I have no idea - I do not think I will work on this by my self, also as ESP board is only connected by serial to TFT upload may be very slow compare to normal upload - I suggest you to put a WiFi SD if you need wifi upload - BTT do cheap ones but did not tested them - toshiba flash Air may be also an option but did not tested on TFT

**Comment by twinsenfan** [comment]
Hi there, 
I think I may have the same issue DrumClock had. I have a BTT SKR E3 Mini v2.0 with tft43 + ESP3D on a ESP01 board. The control board is running marlin bugfix-2.0.x.

All print control works as exptected but I am not able to upload. ESP M21 command returns "Card OK".

When you mentioned  the "SD upload on TFT is not supported in BTT FW currently", are you referring to the marlin firmware or the Tft firmware ?  

Strangely enough, I was able to upload the test.gco.txt (from this issue https://github.com/luc-github/ESP3D/issues/417) after changing the name to .gco. 



Thank you

**Comment by luc-github** [comment]
upload on sd tft is not supported by tft fw, Printer SD upload is implemented

**Comment by twinsenfan** [comment]
Can you let me know how to specify the printer SD to upload in the ESP3D UI ? Thank you.

**Comment by luc-github** [comment]
you select SD, the BTT SD upload button is not visible when BTT SD is selected

**Comment by twinsenfan** [comment]
Not sure I followed,  is "select SD" a button ? 

I see only button like "Progress" "Abort" "Upload" etc.

**Comment by luc-github** [comment]
if you have upload button it goes to Printer SD
