### ISSUE TITLE
Add page to upload, delete, download files

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#49]
to avoid to flash for ui configuration

**Comment by luc-github** [comment]
implemented https://github.com/luc-github/ESP8266/commit/80742c422a8333751753a72517c8b0a3b399e4db

still need to rewrite printer.tpl for 64K SPIFFS to be able to use it

**Comment by denmorru** [comment]
Is it possible to show file change datetime ?
![ffs_esp3d](https://cloud.githubusercontent.com/assets/22202569/24330658/76905e1e-122c-11e7-9f95-b8fcc8c0e4ba.jpg)

**Comment by luc-github** [comment]
could be, but unless you implement rtc clock or add   ntp client it is meaning less
