### ISSUE TITLE
[FEATURE REQUEST]Add support for alternate webserver library 

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#492]
* There is nice library for esp32 that seems more close in feature from esp8266 than current embedded esp32
https://github.com/fhessel/esp32_https_server

Seems even support async way and several clients - need to benchmark it but it may be the solution for the slow upload and file download in http way vs embedded esp32 webserver

Last but not least it supports HTTPS which is in future must be implemented in ESP3D 
https://techtutorialsx.com/2019/04/07/esp32-https-web-server/

for transition period  it even provide a wrapper : https://github.com/fhessel/esp32_https_server_compat, and add experimental support of esp32 websocket

It is actively supported so all is benefit ^_^

Need to do some bechmark but very promising 

* Add back AsyncWebServer is also in plan https://github.com/me-no-dev/ESPAsyncWebServer

Note: For esp8266, the https webserver is already supported (https://www.onetransistor.eu/2019/04/https-server-on-esp8266-nodemcu.html) but memory is more tight in esp8266 so need to test it can handle esp3D

**Comment by ETE-Design** [comment]
@luc-github  Have you testede this yet? Would be great to have faster file transfer...

**Comment by luc-github** [comment]
no I did not 
the goal of this is https - not sure the file transfer will be faster with this server as need to do benchmark as mentioned - or do you have insight ?

**Comment by luc-github** [comment]
the plan of this will be after 3.0 so may be 3.1

**Comment by luc-github** [comment]
\O/
  |  AsyncWebserver is back in game https://github.com/me-no-dev/ESPAsyncWebServer
 /\

**Comment by luc-github** [comment]
Additionnal update: SecureWebServer is coming in 2.0 esp32 core  😸 
  https://github.com/espressif/arduino-esp32/issues/3902#issuecomment-781258806

**Comment by luc-github** [comment]
additional potential library to bench for ESP32 https://github.com/khoih-prog/WiFiWebServer

**Comment by luc-github** [comment]
[ESP3D-TFT](https://github.com/luc-github/ESP3D-TFT) use light httpd and so far so good - did not tried the https but it is well supported, I have coded the multipart POST support so moving to idf when esp8266 is end of life will definitly the way to go

**Comment by luc-github** [comment]
This was open for a long time and no solution so far so let's close it
