### ISSUE TITLE
[BUG]ESP3D for grbl >> to much M-Codes send from Wifi-Modul

### ISSUE THREAD

**Issue by Wesie** [luc-github/ESP8266#494]
My settings of the wifi modul:
UI: 2.1b62 / FW: 2.1.0.c26

In setup <**grb**l> is selected

Hi,
so as mention some time ago, I rewrite the FW for the TFT35 to use the Display on a grbl Controller board for CNC milling.

Today I have insert a fix, that the M117 will not be send to the gbl controller, but the messages are still visible on the screen :) So as I want :) 👍 

During a little playing around, I've spend, that if I try to upload a file to the grbl controller ( SD-Card) - which is not available on the Woodpecker-board - 

--> M20 >> I must change more in the SW (You can ignore tis one)
 
After select a file to upload, I recognise that a M-codes are send :
15:00:31.664 -> M29   >>>>>  Upload to SD-Karte auf Controller Board - we haven't a SD-Card on a grbl board

grbl didn't know the commands and will be answer with an error or alarm. (https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands)
I catch this M-code and ignore them (don't send to grbl), but I believe, you want to have a feedback and the cmd's should not send out with selection of GRBL

**Comment by luc-github** [comment]
if you use BTT FW the command should not be M20 but `M20 SD:` or `M20 U:` and these commands do not go to GRBL

for ESP3D indeed M117 is sent when GRBL does not support them  - but you should be able to disable M117 ouput in webUI seetings,  this does not work ?

![image](https://user-images.githubusercontent.com/8822552/90980568-6d328200-e55c-11ea-8ac4-c829a4e45431.png)

**Comment by Wesie** [comment]
Hi,
thx for replay.
That I can disable the M117, I've seen. But the message on the info screen is a nice to have. So I use the M117, diplay the message on screen , but did not send them to grbl. This one I've change in the code of the BTT. It's works now like a charme.

If grbl selected, I have also the icon for the SD-Card (with should be located on the controller board) . But grbl has no internal SD. Only the BTT. The icon of BTT-SD and BTT-USB works fine. Only the icon for the internal SD should be not visible. If I press this one, a M20 message is passed through the BTT to the grbl:

![icon_internal_SD_GRBL](https://user-images.githubusercontent.com/9315139/90981417-2d21ce00-e561-11ea-9848-b95dd37429a1.JPG)

This M20 xxxxxxxx is not catched for internal use from the BTT  and a M20 alone is send out to the grbl board.

**Comment by luc-github** [comment]
Ok this part is in ESP3D-WEBUI not on ESP3D - I will remove this

**Comment by luc-github** [comment]
@Wesie please try this one and let me know if it fix your issue  -  I have also removed the create dir button which not work neither

[index.html.gz](https://github.com/luc-github/ESP3D/files/5114189/index.html.gz)

![image](https://user-images.githubusercontent.com/8822552/90982216-f69a8200-e565-11ea-85af-793079678ca7.png)

**Comment by Wesie** [comment]
It's works 👍 
The icon is no more visible. Thanks a lot for the fast fix.
Question ( I know its a feature request) 
On one side the GRBL Parameter could be requested. The $$ is send to the machinie. I haven't test in this moment how good the response will be parsed through ... I'll try this one later.
There is also one command in grbl >> "$# - View gcode parameters" , The answer is a list of parameter for Tool-lengh, probe parameter and so on..... 
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#---view-gcode-parameters
It is possible to add this command also into the Web-Gui?

**Comment by luc-github** [comment]
Ok I have pushed update to https://github.com/luc-github/ESP3D-WEBUI/commit/63103bd281f95755119c640c7145ca2153e7d4e9

Yes `$$` is well parsed - webUI is used on GRBL_ESP32 for a while now.

About `$#`
it display me :
```
[G54:0.000,0.000,0.000]
[G55:0.000,0.000,0.000]
[G56:0.000,0.000,0.000]
[G57:0.000,0.000,0.000]
[G58:0.000,0.000,0.000]
[G59:0.000,0.000,0.000]
[G28:0.000,0.000,0.000]
[G30:0.000,0.000,0.000]
[G92:0.000,0.000,0.000]
[TLO:0.000]
[PRB:0.000,0.000,0.000:0]
```

What would you expect webUI do with this output ? 

Sorry I am not very familiar with GRBL

**Comment by Wesie** [comment]
It's more or less for information of the current status. The org, explanation is more better as my english ;)
"
G-code parameters store the coordinate offset values for G54-G59 work coordinates, G28/G30 pre-defined positions, G92 coordinate offset, tool length offsets, and probing (not officially, but we added here anyway). Most of these parameters are directly written to EEPROM anytime they are changed and are persistent. Meaning that they will remain the same, regardless of power-down, until they are explicitly changed. The non-persistent parameters, which will are not retained when reset or power-cycled, are G92, G43.1 tool length offsets, and the G38.2 probing data.

G54-G59 work coordinates can be changed via the G10 L2 Px or G10 L20 Px command defined by the NIST gcode standard and the EMC2 (linuxcnc.org) standard. G28/G30 pre-defined positions can be changed via the G28.1 and the G30.1 commands, respectively.

When $# is called, Grbl will respond with the stored offsets from machine coordinates for each system as follows. 
TLO denotes tool length offset (for the default z-axis), and 
PRB denotes the coordinates of the last probing cycle, where the suffix :1 denotes if the last probe was successful and :0 as not successful.

G54-G59 It could be only one work coordinate system activ at one time. The CNC milling can control in  the area of the  Machine Position, but the program run in a normal case in the Work coordinate system.
E.g. if you probe the X,y and Z axis, this setting will be saved in one of the work coordinate system (e.g. G54). If you want to repeat the same program (e.g. easy program : Drill a hole) 
Execute the programm in G54 ( with Probing)
add the offset e.g. for X and store the new offset in G55. 
Go to 0 of G55  
Repeat the same program
......
G28 are the Homing point from machine (incl Offset, so that the endstops are not touched.
G30 is a temp. Movement of the Zeropoint (stored with G30.1)
G92 is also a not modal movement of the current working area
TLO = Toll lengh offset for Z-Axis
PRB = The coordinate of probing.

If you run into an error (e.g. soft coordinate limet reached) this kind of parameter are very useful to analyse the error. If there are some "bad" coordinates saved and the user is in the wrong working system (e.g. G57 instead of G54) an error comes earlier as you wish ;)

**Comment by luc-github** [comment]
So you can just use Macro button and use it to launch `$#` ?  or you need more `smart` macro ?

**Comment by Wesie** [comment]
A macro is enough. Also I can insert it into the send command frame
Thx for your assistance

**Comment by luc-github** [comment]
great I close issue then, looking forward the final result of your porting

**Comment by Wesie** [comment]
a snapshoot (short video) can be found here:
https://www.youtube.com/watch?v=HK6239mLWPc&t=321s


Am Mo., 24. Aug. 2020 um 00:07 Uhr schrieb Luc <notifications@github.com>:

**Comment by luc-github** [comment]
nice
