### ISSUE TITLE
Won't compile in VSCode>

### ISSUE THREAD

**Issue by Drzet** [luc-github/ESP8266#495]
Errors in ...
.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:271:12: error: 'isnan' has not been declared in 'std'
.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:270:12: error: 'isinf' has not been declared in 'std'

Visual Studio Code and platformIO latest versions, all libraries updated. Windows 10 x64
ESP3D version 2.1.1.1.

**Comment by luc-github** [comment]
for me everything is Ok 
![image](https://user-images.githubusercontent.com/8822552/91532543-c446a700-e90e-11ea-8781-ed0e58725384.png)

also the error described looks like package issue 

what dio you mean by `all libraries updated` ?

**Comment by Drzet** [comment]
It means I have clicked on "update project libraries" in platformIO

**Comment by luc-github** [comment]
Ok this feature has no impact in ESP3D project as libraries are no referenced but in libraries directory

so your problem is likely an installation problem in platformIO of esp8266 package - as Arduino.h is from esp8266 package itself

**Comment by Drzet** [comment]
No idea. I managed to compile the firmware in ArduinoIDE.

**Comment by luc-github** [comment]
Ok great - I close issue then as it is not duplicate

**Comment by sl1pkn07** [comment]
put this in the platformio.ini env section

~~~
platform_packages      = toolchain-xtensa@2.40802.200502
~~~

seems `2.100100.200706` version have problems

**Comment by sl1pkn07** [comment]
seems add `-std=gnu++11` in the build flags instead set the `platform_packages` option also fix the problem

**Comment by luc-github** [comment]
@sl1pkn07 indeed I got same issue when I was requested to update extension and PIO 
Thank you for the tips - it solved it
and now with latest update I also cannot select the target environement anymore from GUI.
It only build `default_envs` or all env...

So need to manualy change `default_envs = esp32dev` to `default_envs = esp8266` to build only one

**Comment by luc-github** [comment]
In 3.0 I have added custom tasks to build esp8266dev and esp32 separatly
Not sure it is the right way to do but it works....

```
{
			"type": "shell",
			"command": "platformio",
			"args": [
				"run",
				"--environment"
				"esp32dev"
			],
			"problemMatcher": [
				"$platformio"
			],
			"group": "build",
			"label": "PlatformIO: build (esp32dev)"
		},
		{
			"type": "shell",
			"command": "platformio",
			"args": [
				"run",
				"--environment"
				"esp8266dev"
			],
			"problemMatcher": [
				"$platformio"
			],
			"group": "build",
			"label": "PlatformIO: build (esp8266dev)"
		},
```

**Comment by sl1pkn07** [comment]
![Screenshot_20200911_162209](https://user-images.githubusercontent.com/462213/92936895-f3026880-f44a-11ea-9606-f9fb95768c5e.png)

without touch nothing in Code

![Screenshot_20200911_162251](https://user-images.githubusercontent.com/462213/92937028-1decbc80-f44b-11ea-952b-b24b43a257a2.png)

**Comment by luc-github** [comment]
I usually go to terminal tasks
![image](https://user-images.githubusercontent.com/8822552/92938820-5beae000-f44d-11ea-9969-916478374bde.png)

But once I go to platformIO button  like you showed - the menu is updated...
![image](https://user-images.githubusercontent.com/8822552/92938969-7cb33580-f44d-11ea-940d-e14d4328ca93.png)

I am not super familiar with platformIO, I never used this platformIO button on left side before 😅  - thank you so much for teaching me this @sl1pkn07  - again you solved a troublesome behavior  - thank you 😸 

I will remove the custom tasks then
