### ISSUE TITLE
WeMOS_Mega_2560_ESP2866_WIFI

### ISSUE THREAD

**Issue by jojoxyz** [luc-github/ESP8266#496]
My problem is communication. Printer makes 2 (Lines) commands and stops.
I've tried all possible configurations and always the same.
Does somebody has any idea?

WeMOS_Mega_2560_ESP2866_WIFI   ,   Ramps 1.4  ,  Repetier v 0.92

esp3d 2.1
Upload speed                   115200
CPU Frequency                   160 Mhz
Crystal Frequency                 26 Mhz
Flash Size                               4MB(FS:2MB OTA 1019KB
Flash Mode                           DIO
Flash Frequency                    40 MHz
Erase Flash                          All Flash Contents

**Comment by luc-github** [comment]
sorry can you give more details of your issue ?
what do you do ? and what happen ?

It is not clear

**Comment by jojoxyz** [comment]
Whenever I execute G28, everything goes ok, but then no command works anymore. Or if I drive manual it works with 1 or 2 movements and then no longer reacts. When I start printing, the printer starts to heat but does not start to press.
Once I reached the cold print - printer makes a command, (Line) then waits about 10 seconds and starts again with a command, (Line).

**Comment by luc-github** [comment]
Ok weird - more questions.
* What is your Printer FW ? 
* What is your ESP8266 board ?
* Wow did you wired esp to ramps ?

when you start print ESP3D does not do anything after so if printer heat but do not actually anything the problem is on printer side (FW or Slicer)
Fromt another point of view when heating most of printer FW reject any commands until temperature is reached 

* Please copy and past the `[ESP420]plain` output from terminal command

 * when commands stop working :
1 - does `[ESP420]plain` command still give out put ?
2 - what is the terminal output when sending `M115` ? 
3 - does your printer still  works from your printer menu ?

**Comment by jojoxyz** [comment]
Controller  MEGA+WiFi R3 ATmega2560+ESP8266, flash 32MB, USB-TTL CH340G, Micro-USB
https://robotdyn.com/mega-wifi-r3-atmega2560-esp8266-flash-32mb-usb-ttl-ch340g-micro-usb.html

FW     Repetier v 0.92


1-M115 no reaction


2-[ESP420]plain
Chip ID: 4462650
CPU Frequency: 160Mhz
Free memory: 35.97 KB
SDK: 2.2.2-dev(38a443e)
Flash Size: 4.00 MB
Available Size for update: 534.69 KB(Ok)
Available Size for SPIFFS: 1.86 MB
Baud rate: 250000
Sleep mode: Modem
Channel: 6
Phy Mode: 11g
Web port: 80
Data port: 8888
Hostname: MYESP
Active Mode: STA (MAC)
Connected to: NETWORK
Signal: 74%
IP Mode: Static
IP: 192.168.0.11
Gateway: 192.168.0.11
Mask: 255.255.255.0
DNS: (IP unset)
Disabled Mode: AP (MAC)
Captive portal: Enabled
SSDP: Enabled
NetBios: Enabled
mDNS: Enabled
Web Update: Enabled
Pin Recovery: Disabled
Authentication: Disabled
Target Firmware: Repetier
M117 output: Enabled
Notifications: Line
Serial output: Enabled
Web socket  output: Enabled
TCP output: Enabled
FW version: 2.1.0.b39 ESP8266/8586

3- yes

**Comment by luc-github** [comment]
what change did you do in repetier to make comunication working  between mega and esp?

does this happen using telnet client like putty and 8888 port ?

**Comment by jojoxyz** [comment]
but nothing works.
I made small progress with memory change and time setting in repetier host
actually everything is configured correctly but it just doesn't work.

**Comment by luc-github** [comment]
>actually everything is configured correctly .

then it should work

> but it just doesn't work

So it is not configured correctly

>I made small progress with memory change and time setting in repetier host

so you do not use webUI ? only repetier host and tcp 8888 port ?

also what change did you do in repetier to make comunication working between mega and esp? which serial port are you using  for ESP ?

**Comment by jojoxyz** [comment]
I tried standard 8888 and others but nothing. In mega bluetooth serial 3
web ui makes the same problems.

**Comment by luc-github** [comment]
what is baudrate on bt seriat 3

**Comment by jojoxyz** [comment]
115200
I also tried 250000
no effect

**Comment by luc-github** [comment]
by default in FW it is 115200 so esp need to be also 115200 - I guess you be sure both match ?

it may be a bug of repetier V0.92 - now repetier is 1.0.4 final did you tried it ?

**Comment by jojoxyz** [comment]
both values are the same. i am trying fw repetier 1.0.4 but with the same result

**Comment by luc-github** [comment]
well I have not clue what going on - I do not know this board 

Is the usb disconnected ? I see depending of switch the USB is also sused by ESP

**Comment by jojoxyz** [comment]
the problem is: if i separate ramps from mega it works. shows temperatour, loads fw config.

**Comment by luc-github** [comment]
so it is micro switch configuration problem ?

**Comment by jojoxyz** [comment]
ON | ON | ON | ON | OFF | OFF | OFF

all functions are ON

**Comment by jojoxyz** [comment]
problem is internal configuration in fw (pins), but no idea how icg can solve the problem

**Comment by luc-github** [comment]
what about on on off off off off off  off?

**Comment by jojoxyz** [comment]
no other configuration does not work. mega must have access to pins and wifi at the same time. that only works in my configuration. I tried it with blink led / server

**Comment by jojoxyz** [comment]
problem solved. tx3 pin 13, 14 connected at ramps on y min, y max.

I have defined the pins in fw as not used and ynim, ymax have defined other pins.

**Comment by luc-github** [comment]
great !
happy you found out
