### ISSUE TITLE
Control Tronxy

### ISSUE THREAD

**Issue by Wuckel01** [luc-github/ESP8266#504]
Hello,
it is possible to control the Tronxy firmware V1.4.1RC24m4 with the TronxyX5SA board  https://de.aliexpress.com/i/32920995172.html with the original firmware and an ESP8266 module.
I have the oginal module which only works directly with wlan and that is not exactly super stable.
I've already tried several settings in esp3d without success.

I have esp3d running on another printer with marlin and it's great.

**Comment by luc-github** [comment]
What M115 give as output? 
is that an esp01?

what works? and what does not?

**Comment by Wuckel01** [comment]
Thank you for your prompt reply
I did not get any interface connection. 
I've tested everything from 9800-25000
 
I couldn't run M115

**Comment by luc-github** [comment]
yes I know, I mean from serial

**Comment by Wuckel01** [comment]
Hello

if I control USB with Pronterface and the com connection with 115200bps and M115 I get an answer.

 

Connecting...

Printer is now online.

>>> M115 

SENDING:M115

ok CBD make it.Date:Jul 22 2019 Time:17:18:49

 

I can also control everything.

 

greeting

**Comment by luc-github** [comment]
well looks like M115 is not supported - do you know what kind of FW is it ?

**Comment by Wuckel01** [comment]
no is original from the manufacturer a firmware on it that is really great but the wlan module software and app is junk

**Comment by Wuckel01** [comment]
Hello

 

it must be based on

https://shop.cbd-3d.com/download/ but has been modified. this is the manufacturer side

https://tronxy.com/

**Comment by Wuckel01** [comment]
Hello

 

What I think is great about the original firmware is that if the power fails, I can continue printing at the last stand and that the print head can also be ausiert, which I have never managed with marin because the firmware is so big that it does not fit in the memory for this module.

therefore I wanted to keep the original firmware

**Comment by luc-github** [comment]
well it looks like an esp01 board so only serial connection - but I read here it is duet wifi https://de.aliexpress.com/item/32990868079.html

so I am confused - duet wifi does not use serial but spi

**Comment by Wuckel01** [comment]
Hello

 

I downloaded the original firmware from the original esp01 and copied it to a new one that works. I was able to establish a connection to cloonen with 115200.

 

there is a possibility if there is a duet wifi to use esp3d.

**Comment by luc-github** [comment]
If you can share the zip of the FW I may have a look, but as I do not have this tronxy board my in investigation will be limited

**Comment by Wuckel01** [comment]
Hello

yes send you the firmware to no thing

**Comment by luc-github** [comment]
I do not see the file, does M408 command give any output by serial?

**Comment by luc-github** [comment]
any update ?

**Comment by Wuckel01** [comment]
Hello

did not have time.

This morning I hung myself between the esp-01 original firmware tronxy and the paltinge and recorded the connection

 

I added sceen
 
if I switch on the wifi on the tronxy and switch it off it comes out with 115200bps
 
it looks like he would adjust the interface speed when activating it

 

regards

 

Sascha

 

 

Von: Luc [mailto:notifications@github.com] 
Gesendet: Samstag, 19. September 2020 08:31
An: luc-github/ESP3D <ESP3D@noreply.github.com>
Cc: Wuckel01 <super.wuckel@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [luc-github/ESP3D] Control Tronxy (#504)

 

any update ?

**Comment by Wuckel01** [comment]
Hello

 

when I send via USB Connect M408 that happens in the Sceenshot

 

 

Von: Luc [mailto:notifications@github.com] 
Gesendet: Samstag, 19. September 2020 08:31
An: luc-github/ESP3D <ESP3D@noreply.github.com>
Cc: Wuckel01 <super.wuckel@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [luc-github/ESP3D] Control Tronxy (#504)

 

any update ?

**Comment by luc-github** [comment]
when you use email to answer the files are not visible, please use github to attach files

**Comment by Wuckel01** [comment]
Hello

I thought that would get well, I'll hang it on

![tronxy M408](https://user-images.githubusercontent.com/34950859/93688559-f6d76000-fac6-11ea-980e-266bef099524.PNG)
![tronxy seriel](https://user-images.githubusercontent.com/34950859/93688565-fe970480-fac6-11ea-9e79-be938c44ebf2.PNG)

**Comment by luc-github** [comment]
are you sure your connection is correct? seems printer does not answer to M115 neither M408
and even no error if not supported

**Comment by Wuckel01** [comment]
Hello

So with the pronterface program I can drive home without any problems and also check the extruders.
![tronxy_test2](https://user-images.githubusercontent.com/34950859/93688998-ab26b580-faca-11ea-9aef-ed4c9261fd63.PNG)

**Comment by Wuckel01** [comment]
Hello

I'll make a screen when heating up
![tronxy_test3](https://user-images.githubusercontent.com/34950859/93689037-fc36a980-faca-11ea-9bea-c8ba2f464043.PNG)

**Comment by Wuckel01** [comment]
Hello

I entered the commands again that one M114 outputs a date, the other only says N: 0 as in the screen, so the printer reacts to it, only probably there are other M
commands.
![tronxy_test4](https://user-images.githubusercontent.com/34950859/93689175-45d3c400-facc-11ea-8036-9798ef255f20.PNG)

**Comment by Wuckel01** [comment]
I still have a gcode file
the configuration of the printer with M commands
I once heard a link to codes that work
http://tronxy-3d.org/posts/g-codes-and-m-codes-for-3d-printing-1-1.htm

this works out
M106 S255 ; set the fan to full speed
M140 S50 ; start heating the bed to 50 degrees Celsius
M114
![tronxy_test5](https://user-images.githubusercontent.com/34950859/93689409-90564000-face-11ea-86bd-f0d376648584.PNG)

**Comment by Wuckel01** [comment]
only once such an idea can you install a serial bit rate of 2250000 in esp3d?

**Comment by luc-github** [comment]
no this speed is far too high

I have no clue why esp is not comminicating with tronxy FW, and why even M115 is not giving printer capabilities by serial

the GCODE commands you linked are not for reprap duet  wifi as M408 is not supported, so I have no clue what your printer fw capabilities

sorry

**Comment by Wuckel01** [comment]
why does he ask when I turn on the wifi on the software
AT+UART_CUR=2250000,8,1,0,0
when reading it, it changes the interface
I rewritten esp3d and added the bitrate but does not work

**Comment by luc-github** [comment]
AT+UART_CUR=2250000,8,1,0,0
does not come from esp3d

**Comment by Wuckel01** [comment]
no that comes from the printer software on the esp8266-01 module when I switch on the wlan function in the firmware on the lcd

**Comment by HaernCalistinson** [comment]
Just for sake of clarity, it's Chitu firmware. Closed source, can't do anything with it. IMHO biggest mistake Tronxy ever made. Configured using gcode commands via a txt file on the sd card.

**Comment by luc-github** [comment]
The I guess there is nothing that I can do - 

according here https://www.thingiverse.com/groups/tronxy/forums/general/topic:45811 
you should may be give a try to Marlin : https://github.com/MarlinFirmware/Marlin/pull/15493

**Comment by luc-github** [comment]
I close issue then

**Comment by HaernCalistinson** [comment]
I will second your suggestion to move the printer to Marlin. While it requires a bit more tuning, it opens up the printer to all sorts of possibilities and solves a lot of the problems that the printer has. The X5SA users group on FB has some pretty easy guides.

**Comment by Wuckel01** [comment]
Hello

I've already had the Marlin firmware on it.
This is not an option for me because the printer with the original firmware is better.
Since Marlin only brings some functions if you switch on functions but the firmware is so big that it no longer fits on the board,
E.g. Autoleveling 6 points, save duckstand after a power failure, stop lifting your head in home and continue printing the deadline at most space, etc. what the original firmware can do.

if it doesn't work with the esp8266-01 on board then just different.

I have a different solution but I have to order hardware first esp3d host USB so I can plug the esp3d directly into it and externally with an additional 5 V supply. I already wrote a housing in 3d for 5v stepdown 12V Mosfet for LED light and control via esp32 with esp3d, only usb host shield is missing.
