### ISSUE TITLE
[BUG]<ESP3D-2.1 AUTHENTICATION_FEATURE>

### ISSUE THREAD

**Issue by vashilov** [luc-github/ESP8266#505]
If I enable AUTHENTICATION_FEATURE, I can not connect to default ESP3D AP.

If I use default Firmware, config ESP to connect to my Wifi network, it fine.
When I update Firmware from .bin (enable AUTHENTICATION_FEATURE) on web interface, ESP do not connect to my wifi.

P.S. AUTHENTICATION_FEATURE it is login and password to web interface?

**Screenshots**
![Снимок экрана от 2020-09-17 11-44-20](https://user-images.githubusercontent.com/71368470/93447640-4c4f1980-f8db-11ea-977f-d4130f251d83.png)
![Снимок экрана от 2020-09-17 11-44-40](https://user-images.githubusercontent.com/71368470/93447637-4b1dec80-f8db-11ea-81e6-c368b52335a9.png)

**ESP3D Firmware:**
SDK:  2.2.2-dev(38a443e)
Flash Size:  4.00 MB
FW version:  2.1.0.b39 ESP8266/8586
WebUI version:  2.1b65

**Comment by vashilov** [comment]
Sorry if I did something wrong.
But maybe it will be useful to someone.

**Comment by vashilov** [comment]
P.S. Discord https://discord.gg/h2pkaf not work.

**Comment by luc-github** [comment]
Yes Authentication Feature has no impact on wifi connection itself

Thank you for pointing out - new link  never ending is now https://discord.gg/Z4ujTwE

**Comment by vashilov** [comment]
But I dont connect to ESP on wifi and ESP not connect to my router.
It is only for me bug?
ESP3D dont work for me with AUTHENTICATION_FEATURE

**Comment by vashilov** [comment]
I only uncomment AUTHENTICATION_FEATURE

**Comment by luc-github** [comment]
as requested in template:
**ESP3D Firmware:**
- ESP core version: [2.5.2]
- Version:[e.g 2.1b4]
- Web UI Version:[e.g 2.1b14]  
- Wifi mode:[e.g. STA]  
- Flash method: [Arduino Ide / PlatformIO]
- Any change done in FW  

**Target Firmware:**
 - Name: [e.g. Marlin]
 - Version [e.g. 2.0]

**Board used (please complete the following information):**
 - MCU: [e.g. ESP32] 
 - Name:[e.g. NodeMCU2s] 
 - Flash size: [e.g. 4M: 2M/2M]

**Comment by vashilov** [comment]
ESP3D Firmware:

    ESP core version: 2.7.4 ???
    Version:2.1.0.b39
    Web UI Version:2.1b65
    Wifi mode:STA and CLIENT
    Flash method: Arduino Ide 1.8.9
    uncommet #define AUTHENTICATION_FEATURE

Target Firmware:

    Name: Marlin
    Version 2.0

Board used (please complete the following information):

    MCU: ESP8266EX
    Name:clone NodeMCU and clone Wemod D1 mini
    Flash size: 4M: 2M/2M

**Comment by vashilov** [comment]
Please send me bin file for ESP8266. I upload it on my ESP3D from web.

**Comment by luc-github** [comment]
I cannot reproduce your issue with same hardware
![image](https://user-images.githubusercontent.com/8822552/93459657-54f71e00-f8e2-11ea-9e4e-66f1e488fcd3.png)

Also you use old Fw - please use latest one from git

**Comment by vashilov** [comment]
I use FW from default branch 2.1.
Try now from master.

Thanks for answer.

**Comment by luc-github** [comment]
yes default branch is 2.1 is correct - but your wrote `Version:2.1.0.b39` so you use old version

**Comment by vashilov** [comment]
I download source from branch is 2.1.
![Снимок экрана от 2020-09-17 14-01-09](https://user-images.githubusercontent.com/71368470/93462659-55e27c80-f8ef-11ea-919f-2ea123ccc3ca.png)
![Screenshot_20200917-140712_Chrome](https://user-images.githubusercontent.com/71368470/93462676-5c70f400-f8ef-11ea-925f-4f4f03df6a16.jpg)


What I do wrong?

**Comment by vashilov** [comment]
You use ESP3D-2.1-devt ?
Now I use it.
AUTH enable and my phone dont connect to wifi
![Снимок экрана от 2020-09-17 14-27-51](https://user-images.githubusercontent.com/71368470/93464804-6f38f800-f8f2-11ea-947d-7c360fa2c0be.png)


AUTH comment
![Снимок экрана от 2020-09-17 14-29-53](https://user-images.githubusercontent.com/71368470/93464812-719b5200-f8f2-11ea-8f7f-194d0300ec05.png)
![Screenshot_20200917-143024_Chrome](https://user-images.githubusercontent.com/71368470/93464825-752ed900-f8f2-11ea-9d28-70c778cb91f6.jpg)

**Comment by vashilov** [comment]
Please send me bin file for ESP8266. I upload it on my ESP3D from web.

**Comment by vashilov** [comment]
maybe I need to fix something else?
For example, admin password and the like.

**Comment by luc-github** [comment]
No sorry I do not send binary on demand, if I start to do, every one will ask for it, and I have no reason and no time to server every one.

how come after flashing you do not have index.html anymore ?
and man you said you flash with Flash size: 4M: 2M/2M: but your UI show you use 3M for flash...

type and show the output of :
[ESP420]plain
[ESP800]
[ESP410]plain

**Comment by vashilov** [comment]
[ESP420]plain
Chip ID: 12554327
CPU Frequency: 160Mhz
Free memory: 36.51 KB
SDK: 2.2.2-dev(38a443e)
Flash Size: 4.00 MB
Available Size for update: 536.50 KB(Ok)
Available Size for SPIFFS: 2.81 MB
Baud rate: 115200
Sleep mode: Modem
Channel: 11
Phy Mode: 11g
Web port: 80
Data port: 8888
Hostname: MYESP
Active Mode: STA (A4:CF:12:BF:90:57)
Connected to: Cisco5
Signal: 66%
IP Mode: DHCP
IP: 192.168.10.138
Gateway: 192.168.10.1
Mask: 255.255.255.0
DNS: 10.5.0.3
Disabled Mode: AP (A6:CF:12:BF:90:57)
Captive portal: Enabled
SSDP: Enabled
NetBios: Disabled
mDNS: Enabled
Web Update: Enabled
Pin Recovery: Disabled
Authentication: Disabled
Target Firmware: Marlin
M117 output: Enabled
Notifications: Disabled
Serial output: Enabled
Web socket  output: Enabled
TCP output: Enabled
FW version: 2.1.1.b8 ESP8266/8586

[ESP800]
FW version:2.1.1.b8 # FW target:marlin # FW HW:Serial SD # primary sd:none # secondary sd:none # authentication:no # webcommunication:Sync:81:192.168.10.138 # hostname:MYESP

[ESP410]plain
Cisco5	78	Secure
ASUS-X	34	Secure
PulsPass	8	Secure

**Comment by vashilov** [comment]
>>how come after flashing you do not have index.html anymore ?

I try install FW many times. I have no index.html on screen, it is only cache.
But in brunch 2.1 FW version is 2.1.0.b39

Maybe i mistake))

**Comment by luc-github** [comment]
no, your branch version is not 2.1.0.b39 - it is 2.1.1.b8 as show in [ESP800] (which is correct) where do you see the 2.1.0.b39 ?

**Comment by vashilov** [comment]
I wrote

>>You use ESP3D-2.1-devt ?
Now I use it.

It ESP3D-2.1-devt branch.

**Comment by vashilov** [comment]
Now info from 2.1 brach
[ESP420]plain
Chip ID: 12554327
CPU Frequency: 160Mhz
Free memory: 36.35 KB
SDK: 2.2.2-dev(38a443e)
Flash Size: 4.00 MB
Available Size for update: 535.87 KB(Ok)
Available Size for SPIFFS: 1.86 MB
Baud rate: 115200
Sleep mode: Modem
Channel: 11
Phy Mode: 11g
Web port: 80
Data port: 8888
Hostname: MYESP
Active Mode: STA (A4:CF:12:BF:90:57)
Connected to: Cisco5
Signal: 72%
IP Mode: DHCP
IP: 192.168.10.138
Gateway: 192.168.10.1
Mask: 255.255.255.0
DNS: 10.5.0.3
Disabled Mode: AP (A6:CF:12:BF:90:57)
Captive portal: Enabled
SSDP: Enabled
NetBios: Enabled
mDNS: Enabled
Web Update: Enabled
Pin Recovery: Disabled
Authentication: Disabled
Target Firmware: Marlin
M117 output: Enabled
Notifications: Disabled
Serial output: Enabled
Web socket  output: Enabled
TCP output: Enabled
FW version: 2.1.0.b39 ESP8266/8586
[ESP800]
FW version:2.1.0.b39 # FW target:marlin # FW HW:Serial SD # primary sd:none # secondary sd:none # authentication:no # webcommunication:Sync:81:192.168.10.138 # hostname:MYESP
[ESP410]plain
Cisco5	76	Secure
PulsPass	20	Secure
ASUS-X	34	Secure

**Comment by vashilov** [comment]
Ok.
If I edit anywhith in config.h, example comment //#define DIRECT_PIN_FEATURE
I can not connect ti wifi ((

**Comment by luc-github** [comment]
Sorry man but what are you doing exactly ? you looks changing branch version all the time
I think you mess up your source code and changed more code than what you describe - AUTHENTICATION_FEATURE and DIRECT_PIN_FEATURE have nothing related to WiFi neither WiFi Connection at boot time - so changing them have 0 impact on wifi connection 

1 - I suggest you to clean / delete all code 
2 - to download latest code from my repository branch 2.1
3 - change and do not copy from else where the AUTHENTICATION_FEATURE
4 - reflash using 4M with 2M SPIFFS
5 - do a [ESP444]RESET
6 - [ESP100]<your SSID>
7 -  [ESP101]<your SSID password>
8 - [ESP103]STA
9 - [ESP104]DHCP
10 - [ESP444]RESTART

**Comment by vashilov** [comment]
>>you looks changing branch version all the time

I use 2.1 (2.1.0.b39).
You say me, it is old, I try use ESP3D-2.1-devt.

>>I suggest you to clean / delete all code

I already try it many times((


I do from 1 to 10:
1-4 ok
5-10 -> Incorrect Cmd
(if //#define AUTHENTICATION_FEATURE 5-10 is Ok)

But [ESP420]plain is Ok

**Comment by vashilov** [comment]
Any idea?
If it just for me close disput.

Any people enable #define AUTHENTICATION_FEATURE?

**Comment by luc-github** [comment]
`I use 2.1 (2.1.0.b39).` is not latest 2.1 branch version 
when enable #define AUTHENTICATION_FEATURE you need to provide admin password 

5 - [ESP444]RESET pwd=admin
6 - [ESP100] pwd=admin
7 - [ESP101] pwd=admin
8 - [ESP103]STA pwd=admin
9 - [ESP104]DHCP pwd=admin
10 - [ESP444]RESTART pwd=admin

**Comment by vashilov** [comment]
Oh ok.
I mean AUTHENTICATION_FEATURE is password from web, no from cmd((
I wrote
>>P.S. AUTHENTICATION_FEATURE it is login and password to web interface?

ESP3D have password for WEB or no?

Wifi dont work any way for me!

![Снимок экрана от 2020-09-17 16-27-44](https://user-images.githubusercontent.com/71368470/93476830-e6768800-f902-11ea-9cbe-26280a7d5410.png)

![Снимок экрана от 2020-09-17 16-28-31](https://user-images.githubusercontent.com/71368470/93476842-ea0a0f00-f902-11ea-9c6a-6da365f46479.png)

**Comment by vashilov** [comment]
I can edit ESP name, password, mode -> wifi work
If I comment or uncomment #define -> wiifi not connect
Maybe is problem of my two ESP.

P.S. 2.1.0.b39 is latest version download from default 2.1 branch))  https://github.com/luc-github/ESP3D-WEBUI/tree/2.1
P.P.S. I don know about "Tags". I need download from https://github.com/luc-github/ESP3D/tree/v2.1.1.1?

**Comment by vashilov** [comment]
When ESP restarted I can connect to it for few miliseconds.
![Снимок экрана от 2020-09-17 16-54-49](https://user-images.githubusercontent.com/71368470/93480819-8bdf2b00-f906-11ea-90b0-5cbc6002e374.png)

**Comment by luc-github** [comment]
1 - you are not using correct source : https://github.com/luc-github/ESP3D/blob/2.1/esp3d/config.h#L22
2 - `I can edit ESP name, password, mode` where are you doing that ? you can only edit ESP Name in config.h

**Comment by vashilov** [comment]
DEFAULT_AP_SSID
DEFAULT_ADMIN_PWD
DEFAULT_WIFI_MODE

**Comment by vashilov** [comment]
If I open esp3d folder
In config.h I see #define FW_VERSION "2.1.1.b8"

If I click Download
![Снимок экрана от 2020-09-17 17-04-13](https://user-images.githubusercontent.com/71368470/93481943-d44b1880-f907-11ea-80c8-b545bec914bb.png)

I have 2.1.0.b39.
???

Git clone fine work.

**Comment by vashilov** [comment]
ESP3D have password for WEB or only cmd?

**Comment by luc-github** [comment]
DEFAULT_AP_SSID is for ESP3D AP mode not for Station mode
DEFAULT_ADMIN_PWD is for Authentication feature  (web - telnet - serial) not for AP neither STA mode

So your credential are wrong for sure and also you need to do a [ESP444]RESET to apply them or they are not

so if your version is 2.1.0.b39 it means the flash did not succeed  because it should be 2.1.1.b8 or you never closed arduino ide when you updated code to "2.1.1.b8 and ide still use old cache

**Comment by luc-github** [comment]
also these define are after the important line :
`//Do not Edit after this line //////////////////////////////////////////////`

**Comment by vashilov** [comment]
On 2.1.1.b8 AUTHENTICATION_FEATURE no work.
I update FW. And cmd use password.

![Снимок экрана от 2020-09-17 17-12-32](https://user-images.githubusercontent.com/71368470/93482988-fbeeb080-f908-11ea-8c40-ec634739ce9e.png)


>>DEFAULT_AP_SSID is for ESP3D AP mode not for Station mode
DEFAULT_ADMIN_PWD is for Authentication feature (web - telnet - serial) not for AP neither STA mode

I understand that.

**Comment by vashilov** [comment]
>>//Do not Edit after this line

I understand that.
It for experement only!!

**Comment by vashilov** [comment]
Please download zip file version 2.1 from web site.

What version you have in zip?

If I use git clone, I have 2.1.1.b8.
If download zip 2.1.0((

**Comment by vashilov** [comment]
I tried using Visual Studio whith Platformio. All work fine.

Sorry man!!!

But try download zip file version 2.1 from web site.

**Comment by luc-github** [comment]
![image](https://user-images.githubusercontent.com/8822552/93569694-33556f80-f992-11ea-97c4-f1369a2c6a99.png)

**Comment by vashilov** [comment]
Yes. I do this.
But not correct files inside.

My friend download zip, in him zip old FW too.

**Comment by vashilov** [comment]
On mobile too.

![Screenshot_20200918-103952_Chrome.jpg](https://user-images.githubusercontent.com/71368470/93570492-c1822380-f99b-11ea-8d34-170e830067c6.jpg)
![Screenshot_20200918-104051_Cx File Explorer.jpg](https://user-images.githubusercontent.com/71368470/93570374-94357580-f99b-11ea-914c-4b18d5055eaa.jpg)
![Screenshot_20200918-104102_Cx File Explorer.jpg](https://user-images.githubusercontent.com/71368470/93570511-c941c800-f99b-11ea-8e6a-19a6f06a65b5.jpg)

**Comment by luc-github** [comment]
Yes I have reproduced it - looks like github website link to release instead of git - weird...

**Comment by luc-github** [comment]
I have workaround the git issue I think
* I did a formal release for 2.1.1 - actually was time for it
* I have created a 2.1.x branch and set it as default - now the download link seems ok:  I did a change in readme then downloaded again and change was reflected in new download.

I have no idea why github mess up like this...
