### ISSUE TITLE
ESP01 version is working please feedback

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#51]
I use it from now but - feedback/suggestion of improvement are always welcome

**Comment by luc-github** [comment]
OK some improvement are already on going but need new staging to be released so I won't push to github now but here is a preview:
Now FM display space - that was really missing especially for 64K SPIFFS to see what can be done / or not
![image](https://cloud.githubusercontent.com/assets/8822552/10666044/d3a6d5e4-7901-11e5-8741-2b271502183d.png)

**Comment by luc-github** [comment]
please use : https://github.com/luc-github/ESP8266/releases/tag/v0.4-beta.1

**Comment by luc-github** [comment]
due to ESP01 with 1M flash this is no need anymore
I close issue as now seems ok fr current release issue is more related to GIT version vs Stable version

**Comment by denmorru** [comment]
Simply stated already in documentation, that ESP3D firmware needs 1M flash memory or more. https://github.com/luc-github/ESP3D/wiki
