### ISSUE TITLE
[Question]<how to upload marlin and esp3d in one modul esp32>

### ISSUE THREAD

**Issue by liwajaya** [luc-github/ESP8266#511]
how do i combine marlin and esp3d in one esp32 module i will use esp32 like have [Maplerain](https://github.com/maplerainresearch/MRR_ESPA) or grbl have
[Bdring](https://github.com/bdring/Grbl_Esp32/blob/main/Grbl_Esp32/src/Machines/3axis_v4.h) without additional board.  I am not clear in the order of how to upload ... is Marlin uploaded first, then uploads esp3d like that?  or vice versa.  I hope anyone can help

**Comment by luc-github** [comment]
Marlin installed in ESP32 board use [ESP3DLib](https://github.com/luc-github/ESP3DLib) you need to configure it in Configuration_adv.h

https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/Configuration_adv.h#L3391-L3410


GRBL_esp32 integrate the ESP3D code inside FW not as lib like marlin but it may change in future

**Comment by luc-github** [comment]
I think issue can be closed now
