### ISSUE TITLE
Cannot access html pages after flashing

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#54]
Moved to another thread for better following

**Comment by TRoager** [comment]
i just got this issue with the newest pre-release: Error opening : /home.tpl

:/

**Comment by luc-github** [comment]
this is normal you need to copy files to SPIFFS place 
the tools copy the content from data

**Comment by luc-github** [comment]
I have put link in readme but may be need to highlight:


you need to get the tool from this link : http://arduino.esp8266.com/versions/1.6.5-1160-gef26c5f/doc/reference.html#file-system

**Comment by luc-github** [comment]
the file must be put under windows here :
<My document directory>\Arduino\tools\ESP8266FS\tool\esp8266fs.jar

let me know if you have issues

**Comment by TRoager** [comment]
I have been messing with it this morning. and it seems like im getting this error: 


Uploading 3125248 bytes from C:\Users\tr\AppData\Local\Temp\build201004763003836653.tmp/esp8266.spiffs.bin to flash at 0x00100000
......warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_DATA) failed
warning: espcomm_send_command: wrong direction/command: 0x01 0x03, expected 0x01 0x04

**Comment by luc-github** [comment]
what esp do you use? what os ?

be sure you are in upload mode like for flashing and no arduino terminal is open

**Comment by TRoager** [comment]
Im using ESP12 and ESP12E, both giving same error with freshly installed Arduino 1.6.5 and Staging release. I can upload the firmware just fine just not the SPIFF, the terminal are closed, it looks like its about to flash for a few sec, liek you can see a few dots and then the error :(

**Comment by luc-github** [comment]
weird
what setting do you use to flash ?

generic 4M (1M SPIFFS)

**Comment by TRoager** [comment]
![error](https://cloud.githubusercontent.com/assets/1173155/10709181/d885a42e-7a22-11e5-9e65-3f3b403137f6.png)

This is my error :/ and looks like the upload info is correct, but please correct me if im wrong :/

**Comment by luc-github** [comment]
flashing SPIFFS should work even without my FW it is not related

you have 4M flash I guess, but issue looks more communication issue, and actually if you put GPIO 0 to GND should be ok

I am outside now, so not really helpful sorry

**Comment by TRoager** [comment]
Hmm i will try and look at my setup to see if somethings wrong, just wierd because i can compile and upload just fine :/

**Comment by luc-github** [comment]
after flashing fw you need to unplug replug esp to be in upload mode again

**Comment by TRoager** [comment]
I did

2015-10-24 7:54 GMT+02:00 Luc <notifications@github.com>:

**Comment by luc-github** [comment]
my understanding is: it is same tool which flash fw than flash spiffs image, just location change

and your error look like tool cannot start communication

**Comment by TRoager** [comment]
like you said communication failure. i changed my RS232 cable and now it seem to work :)
i had a FTDI adabter board from ebay, it seems like its not good enough :/

**Comment by luc-github** [comment]
good ^_^
