### ISSUE TITLE
[Question] NodeMCU ESP32 Dev / CR-10 v.3 (Marlin 2.0) Do i have the correct setup?

### ISSUE THREAD

**Issue by 10bn** [luc-github/ESP8266#551]
![C6A550CB-4568-4B41-9B55-0B2E1C161C70_1_105_c](https://user-images.githubusercontent.com/46263124/103490221-9c1a0800-4e1a-11eb-89e1-6dac97b16e09.jpeg)
![89C9BC75-31CD-424E-9951-87433094AAEE_1_105_c](https://user-images.githubusercontent.com/46263124/103490230-adfbab00-4e1a-11eb-9875-d4dca18c7a8a.jpeg)
![](https://images-na.ssl-images-amazon.com/images/I/615Z1%2BqY6SL._AC_SL1000_.jpg)

ESP3D Firmware:

ESP core version: latest
Web UI Version: latest
Flash method: Platform IO -> Generic Options default_envs: esp32dev
Any change done in FW: no

Target Firmware:

Name: Marlin
Version 2.0.7.5_NIC

I couldn't mange to control the printer via the webinterface of ESP3D.

Is the following setup correct? 

I connected the NodeMCU as follows:

Printer FW Marlin 2.0 = NodeMCU ESP3D

GND = GND
RX = TX
TX = RX
5V = 5V

Am I missing any essential steps to get the setup working?

**Comment by luc-github** [comment]
be sure Baud rate is same between esp3d and board
also you may try to invert rx/tx 
be sure usb is not connected on nodemcu neither board

I see it special connector for tft if so may be the port is not enabled in Marlin ?

**Comment by luc-github** [comment]
@jaddel any update?

**Comment by 10bn** [comment]
Hi, thanks for the suggestion. I'm currently busy and will look into it again when my silent fans arrive so i don't need to open the PSU twice.

**Comment by luc-github** [comment]
I will move topic to discussion instead of bug tracker when feature is back

**Comment by luc-github** [comment]
As transfer to discussion seems still not back I close issue
