### ISSUE TITLE
[Question] ESP32-CAM

### ISSUE THREAD

**Issue by DangerD1024** [luc-github/ESP8266#558]
How can i access camera after flashing firmware?
On camera tab it asks to specify ip address

**Comment by luc-github** [comment]
use the webUI 3.0 check https://github.com/luc-github/ESP3D-WEBUI/issues/123

panel  ESP32 /snap and refresh = 0.2

**Comment by DangerD1024** [comment]
Sorry, do you have compiled index.html.gz ?
![image](https://user-images.githubusercontent.com/4560434/104478954-8dc2ad80-55cb-11eb-8e53-2374214da672.png)

**Comment by luc-github** [comment]
yes as writen in webUI read me https://github.com/luc-github/ESP3D-WEBUI/tree/3.0/dist/printer/production

**Comment by DangerD1024** [comment]
Uploaded version 3.0 with uncomented camera
![image](https://user-images.githubusercontent.com/4560434/104482799-09265e00-55d0-11eb-8732-e30966c2d44e.png)
![image](https://user-images.githubusercontent.com/4560434/104482921-32df8500-55d0-11eb-8484-93d0912bc565.png)
Still can't find it =)

**Comment by luc-github** [comment]
did you check the link and the comment above https://github.com/luc-github/ESP3D/issues/558#issuecomment-759550894 ? there are pictures

**Comment by luc-github** [comment]
@DangerD1024 did you solved your issue ?

**Comment by DangerD1024** [comment]
Works, thank you. Will start soldering resistors =) Would be great to update wiki, so dummys like me will not ask that again =)

**Comment by luc-github** [comment]
feel free to contribute ^_^
