### ISSUE TITLE
[BUG] Impossible to upload gco file on SD card.

### ISSUE THREAD

**Issue by RegisVy** [luc-github/ESP8266#560]
**Describe the bug**
Impossible to upload gco file on SD card.

**To Reproduce**
1. in the web UI in the SD File interface, clic on "Upload"
2. Choose a file (i.e. Test1.gco)
3. The status bar indicates 100% uploaded very quickly and the printer bed and nozzle start to heat
4. When the target temperature is reach, "upload failed" and this message appears
"Error:Line Number is not Last Line Number+1, Last Line: 8
Resend: 9
ok
Deletion failed (read-only), File: Test1.gco.
ok"
And "Error(3) File write failed" pop up message appears.

**Expected behavior**

**Screenshots**

**ESP3D Firmware:**
- ESP core version: [2.1.1]
- Version:[2.1.1.b8 ESP8266/8586]
- Web UI Version:[2.1b57]  
- Wifi mode:[STA]  
- Flash method: [PlatformIO]   

**Target Firmware:**
 - Name: Marlin
 - Version: Marlin 2.0.7.2
    
**Board used (please complete the following information):**
 - MCU: [ESP32] 
 - Name:[e.g. NodeMCU2s] 
 - Flash size: [1.00 MB]
In platformio.ini : 
build_flags = 
    -Wl,-Teagle.flash.1m256.ld

**Additional context**
- The Test1.gco file is very simple (1KB) ;
- I am able to move the nozzle and the bed through all axes from the web UI ;
- I am able to command the temperature from the WebUI.
- I am a noob/beginner  sorry for that.

[TestFile_ErrorMsgScreenShot.zip](https://github.com/luc-github/ESP3D/files/5816795/TestFile_ErrorMsgScreenShot.zip)
[Configuration.zip](https://github.com/luc-github/ESP3D/files/5816828/Configuration.zip)

**Comment by luc-github** [comment]
do you have autotemp in Marlin enabled?

**Comment by RegisVy** [comment]
Sorry, I forget to say hello in my first post,

Yes, the AUTOTEMP is enable in the configuration_adv.h of Marlin, here is a screenshot :
![image](https://user-images.githubusercontent.com/77460847/104698661-003da580-5712-11eb-91fb-464c8173b54a.png)

**Comment by luc-github** [comment]
so that the problem - you must not have any message on going during upload - Marlin do not stop autosend when using M28/M29 - disable auto send  (I forget the GCODE) and check no message is ongoing to ESP by checking the terminal in web UI  - if any message take a screen
if no message then you can do upload

**Comment by RegisVy** [comment]
Thank you for you answer, I tested the following : M155 S0 to desable temperature autoreport : 

Marlin doc : 
![image](https://user-images.githubusercontent.com/77460847/104745800-c17a1080-574e-11eb-8443-b9489c75861c.png)

I typed M155 S0 : 
![image](https://user-images.githubusercontent.com/77460847/104745885-db1b5800-574e-11eb-93eb-65838cdb7347.png)

But, at the upload, I still have the same error message : 
![image](https://user-images.githubusercontent.com/77460847/104745939-eb333780-574e-11eb-9844-3c312b52d967.png)

And the same information in the web ui terminal : 
![image](https://user-images.githubusercontent.com/77460847/104745993-fc7c4400-574e-11eb-8c06-b0a9751e4c8d.png)

I am suprised to still see some information about temperature in the terminal since I sent the command M155 S0.

Question : 
1) Did you want I typed this command (M155 S0) or you were thinking about something else?
2) Do you want me to desable in marlin firmware directly the AUTO_REPORT_TEMPERATURES ?
![image](https://user-images.githubusercontent.com/77460847/104746381-7dd3d680-574f-11eb-98ad-33f69eb5d571.png)


Thank you in advance

**Comment by luc-github** [comment]
are you uploading when you are heating ?
I see the temperature message from Marlin, and I see Marlin say it is busy processing

**Comment by RegisVy** [comment]
At the moment I start to upload, the printer starts to heat at the temperature defined in the Test1.gco .
It behavs like if it start to run the .gco file before the file finish to upload (it is exactly this behavior, if I change the temperature defined in the file and try to upload, the target temperature will be updated and the printer will start to heat even if the file is not uploaded)

**Comment by luc-github** [comment]
it means the command M28 is  not taken in account and the fw take each command as a command instead of save to sd

can you enter the following commands in webui terminal and give me the output :
```
M20
M28 test1.gco
M117 nothing
M29
```

**Comment by RegisVy** [comment]
Ok, 

M20
Begin file list
PIN.GCO 552870
XYZCAL.GCO 334725
LEAN_XY.G 2144156
LEAN_XY.GCO 2144156
TEMPPC2.GCO 4658543
TEMPPC3.GCO 4658543
TEMPPC4.GCO 4658518
TEMPPC1.GCO 4668324
TEMPPC5.GCO 5023636
BGPLA.GCO 14563903
BGPC.GCO 14641945
End file list
ok

M28 Test1.gco
echo:Now fresh file: Test1.gco
open failed, File: Test1.gco.
ok

M117 nothing
ok

M29
ok

**Comment by luc-github** [comment]
as you can see Marlin cannot open the file - so upload is failing 
check if your SD is not on read only - and be sure it is 4GB SD formated with https://www.sdcard.org/downloads/formatter/eula_windows/index.html

**Comment by RegisVy** [comment]
Ok I will try this and let you know, thank you.

**Comment by RegisVy** [comment]
How can I check if the SD card is in read only mode? because when I connect the sd card to my pc I am able to add file with no issue...

**Comment by luc-github** [comment]
if you can add file so it means it is not in read only 😸

**Comment by RegisVy** [comment]
Ok good, so I will try to format the SD card with the link you sent me.

And here is a very short presentation with screenshots I just took to be sure you have all the informations you need.
[Behavior.pdf](https://github.com/luc-github/ESP3D/files/5822459/Behavior.pdf)

**Comment by RegisVy** [comment]
It is exactly the same behavior after formating the SD card :(

**Comment by luc-github** [comment]
well as you can see it is Marlin side - not EP3D 
what size is the SD card ?

**Comment by RegisVy** [comment]
Yes, I guess so. It is an 8GB
![image](https://user-images.githubusercontent.com/77460847/104767853-204e8280-576d-11eb-9440-d14eebe4eef0.png)

**Comment by luc-github** [comment]
try overwrite format - not quick format
and try another SD if still fail

as long as `M28 test1.gco` is failing upload will failed

**Comment by RegisVy** [comment]
I am doing the overwrite.

Ok but, by just typing this command, does the system find were the test1.gco code is located on my laptop?

**Comment by RegisVy** [comment]
It is still the same with the overwrite option

**Comment by luc-github** [comment]
well I have no idea sorry - just change SD

**Comment by RegisVy** [comment]
no problem, so from your point of view, it doesn't come from ESP3D, nether from Marlin but it comes from the SD card directly? 

With another SD card I have a different issue : 
![image](https://user-images.githubusercontent.com/77460847/104770404-cf408d80-5770-11eb-864e-444b02570805.png)

**Comment by RegisVy** [comment]
I confirm the instructions I give to the printer are working (ie set the X position) so the connection is OK

**Comment by luc-github** [comment]
M28 test1.gco failing is SD card issue - Marlin support it 
The `No connection` is another issue and without details it is hard to answer - but it means esp board do not communicate with webUI so it is different than SD access

**Comment by RegisVy** [comment]
Ok thank you, I will ask the Marlin support (I guess there is a Marlin support), thank you for your time. If they find the issue, Iwill update this post.

**Comment by luc-github** [comment]
Thank you

**Comment by RegisVy** [comment]
I just found the issue, in Marlin installation, in the configuration_adv.h, the define SDCARD_READONLY was not commented : 
![image](https://user-images.githubusercontent.com/77460847/104774413-ec785a80-5776-11eb-8d6e-6587083bfcaa.png)

Thank you for you help!!

**Comment by luc-github** [comment]
I did  not know this option - thank you for sharing 
I guess issue can be closed then ^_^
