### ISSUE TITLE
The index.html upload rejected with the latest develoption esp3d(v3.0.0.a84)

### ISSUE THREAD

**Issue by yu3000** [luc-github/ESP8266#561]
my board is nodemcu-32 v1.2(2768)

The esp3d release version v2.0.1 is ok for me,but the latest develoption esp3d has some problems to upload index.html.tar to board.

The hints is:
Update failed(5) : upload rejected.

Expect your help,thanks very much.

**Comment by luc-github** [comment]
1 - it does not support tar files
2 - Error 5 means not enough space - you do not have enough space on FS to upload

**Comment by yu3000** [comment]
thank you very much

**Comment by luc-github** [comment]
I close issue then

**Comment by yu3000** [comment]
This is the output from 192.168.0.1:
Status: Upload failed, / does not exists!  |  Total space: 1023.69 MB  |  Used space: 1023.69 MB  |  Occupation: 
 2%

This is the output from ardunio:

Chip is ESP32D0WDQ5 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: e8:68:e7:22:a6:b4
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 8192 bytes to 47...
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 2259.9 kbit/s)...
Hash of data verified.
Compressed 15856 bytes to 10276...
Wrote 15856 bytes (10276 compressed) at 0x00001000 in 0.1 seconds (effective 862.9 kbit/s)...
Hash of data verified.
Compressed 1128832 bytes to 645104...
Wrote 1128832 bytes (645104 compressed) at 0x00010000 in 11.1 seconds (effective 810.1 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 682.7 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

I don't know if the board is really no enough space?

**Comment by luc-github** [comment]
what board is it ?

**Comment by yu3000** [comment]
nodemcu-32 v1.2 
ESP32-S

**Comment by luc-github** [comment]
what settings do you use in IDE to flash ?

**Comment by yu3000** [comment]
ESP32-Ardunio->nodemcu-32S

**Comment by luc-github** [comment]
all settings please

**Comment by yu3000** [comment]
upload speed  921600
flash frequency 80MHZ

**Comment by luc-github** [comment]
take screenshoot of all settings in ide like this
![image](https://user-images.githubusercontent.com/8822552/104808116-5844dc80-57e4-11eb-9ae3-3bde7370d887.png)

**Comment by luc-github** [comment]
and if you use 80HZ which not correct setting so I suspect you also use another wrong settings

**Comment by yu3000** [comment]
sorry，I can't see the image,but I will attach a screenshoot

**Comment by yu3000** [comment]
![Uploading 截屏2021-01-16下午5.19.57.png…]()

**Comment by yu3000** [comment]
<img width="399" alt="截屏2021-01-16下午5 19 57" src="https://user-images.githubusercontent.com/13162624/104808249-cc7b8200-57dc-11eb-86c2-9d6ebf983fac.png">

**Comment by yu3000** [comment]
For the nodemcu-32S,it's has only two choice ,80 or 40 MHZ,I will change to 40MHZ to try it

**Comment by luc-github** [comment]
what ? no this is not the Flash Frequency the problem

**Comment by yu3000** [comment]
Use the same settings,it's ok with the ESP3D 2.0

**Comment by luc-github** [comment]
- use generic esp8266 board not NodeMCU
- CPU 160MHz
- Flash 4M with 2M for FS
- Flash Mode DOUT

Do not change others default settings but port

![image](https://user-images.githubusercontent.com/8822552/104808347-e4a3cf00-57e5-11eb-9ca9-311271e34aeb.png)

**Comment by luc-github** [comment]
I just realize you are using ESP32 board ?

**Comment by yu3000** [comment]
ok,I will try your given settings,thanks,
wait my feedback:)

**Comment by luc-github** [comment]
my settings are for nodeMCU esp8266 your log show you are compiling for ESP32 
what is your board exactly ?

**Comment by yu3000** [comment]
Yes, It's ESP32 board,so could I use the setttings of 8266

**Comment by luc-github** [comment]
no

**Comment by yu3000** [comment]
Detecting chip type... ESP32
Chip is ESP32D0WDQ5 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme
None
MAC: e8:68:e7:22:a6:b4
Uploading stub...
Running stub...
Stub running...
Warning: ESP32 has no Chip ID. Reading MAC instead.
MAC: e8:68:e7:22:a6:b4
Hard resetting via RTS pin...

**Comment by yu3000** [comment]
so the problem is not coused by the settings?

**Comment by luc-github** [comment]
yes could, use these settings as I do not know what nodeMCU use as FS and do not want to check the board.txt

![image](https://user-images.githubusercontent.com/8822552/104808783-c7bccb00-57e8-11eb-8425-8da73432f22d.png)
