### ISSUE TITLE
ESP3D No connection Error

### ISSUE THREAD

**Issue by Btoz25** [luc-github/ESP8266#570]
Hi everyone, i can't upload anything from SD files 

Gives this error:

![error](https://user-images.githubusercontent.com/56264973/106143994-9ea31f80-6184-11eb-8fa2-ec76ed57f9c7.jpg)

MY ESP3D FW and UI versions:

![fwandui](https://user-images.githubusercontent.com/56264973/106144218-f3df3100-6184-11eb-8170-b8eb5ccf1810.jpg)

Thank you for giving a time

**Comment by luc-github** [comment]
Which SD ?
What printer board ?
What printer Firmware ?
What `M20` give as output ?
What `[ESP420]plain ` give as output ?

**Comment by luc-github** [comment]
Any update ?

**Comment by luc-github** [comment]
I see no update but what I can see is :
1 -  it is a very old FW
2 - this FW seems to be the BTT FW  for esp3d so I guess it is used on TFT or SKR which is Marlin and there were several change since the fw was done - so back to 1 too old for latest Marlin 2.X
