### ISSUE TITLE
[QUESTION] Support for current Creality Silent boards V4.2.x

### ISSUE THREAD

**Issue by TzOk83** [luc-github/ESP8266#591]
Are there any plans for supporting the Creality Silent 32-bit boards, like v4.2.7?

**Comment by luc-github** [comment]
what do you mean ?
https://github.com/luc-github/ESP3D/discussions/557 which link to  https://github.com/luc-github/ESP3D/issues/524#issuecomment-745163565

**Comment by TzOk83** [comment]
What I mean is mainly the Wiki Page for that board doesn't exist, So I didn't know if it is possible to connect to it at all. #524 somehow answers my question, but official documentation/Wiki doesn't mention that boards at all, so I understand it is not officially tested/recommended.

**Comment by luc-github** [comment]
I do not have all boards - board for wiki is done by users sharing their configuration - if not in wiki, it just means no one did or share the configuration yet, it may not mean it is not possible, it is just not documented yet

**Comment by Legsmaniac** [comment]
@TzOk83 I'm using Creality 4.2.7 with ESP3D v3.0 so if you're wanting to know if the 4.2.7 board works with ESP3D then yes, it does.
