### ISSUE TITLE
[Question] best way to connect from smart watch

### ISSUE THREAD

**Issue by drunkscientist** [luc-github/ESP8266#595]
so im writing an app for the TTGO-watch, as discussed [here](https://github.com/sharandac/My-TTGO-Watch/issues/164), and im trying to decide the best way to get data from the printer to the watch. opening a telnet connection might be fine while the user is staring at their wrist, but for basic status updates im wondering if it would be more efficient to use the webUI somehow? just have the watch pull data from a url whenever the display turns on(is there an api?)? websockets? im very new to the 'networking' part of programming so im quite unsure. my first goal is get some connection and display the printers status on the watch, eventually i would like to be able to send custom serial commands, possibly leverage the macros from the webUI

**Comment by luc-github** [comment]
in 2.1 the telnet is the way to go for remote app
in 3.0 you can also use websocket

Currently only file upload need http which is not necessary fo you if just monitoring/control
