### ISSUE TITLE
ESP01S module does not generate WIFI hotpot

### ISSUE THREAD

**Issue by JosemiZubi** [luc-github/ESP8266#604]
After generating the firmware and uploading it to the module, I look for the network generated by the ESP01s module but it does not exist. I'm not doing something basic but I cannot know what I am doing wrong.

ESP3D Firmware: 2.1.1 ESP3D for ESP8266
- ESP01s
- Flash method: PlatformIO
    
Thanks in advance!!!

![Flash](https://user-images.githubusercontent.com/33072159/112906741-f6122d00-90ec-11eb-93ed-8b95282d5b72.jpg)

**Comment by JosemiZubi** [comment]
Hi:

Using Arduino IDE for generating the firmware, the module works, it's OK

Thanks.

**Comment by luc-github** [comment]
you are not using platformio to flash , screenshot show another application
you should use DOUT for spi not QIO

**Comment by JosemiZubi** [comment]
Hi, Thank you very much for the reply.

  Then, I must also use platformio to flash. How should i do it?: NodeMCU ESP8266, Arduino extensión...What is't the best way?. Thanks on avance.

**Comment by luc-github** [comment]
you just connect your board select the esp8266 and click upload and monitor
com detection is automatic and all settings are ready
![image](https://user-images.githubusercontent.com/8822552/112986136-6bb7e080-9161-11eb-861d-e8d54e2db404.png)

I have just updated th platformio.ini as I have noticed the flash method was not using the nodemcu one so you may need to update lastest git

**Comment by JosemiZubi** [comment]
Hi:

O.K. I will use thids method. Thanks you for your support and your grear job!

**Comment by luc-github** [comment]
is it ok now ? if yes please close issue

**Comment by JosemiZubi** [comment]
It'so o.k. I clóse the issue. Thanks.
