### ISSUE TITLE
Ok I effectively had a bad wiring / A10 GT2560 Geeetech

### ISSUE THREAD

**Issue by petervflocke** [luc-github/ESP8266#608]
@Arthur75012 in https://github.com/luc-github/ESP3D/issues/457#issuecomment-624222855_
mentioned that he successfully wired GT2560, can some one provide the wiring?
Was it connected to J7 Uart interface with RXD3/TXD3 or into the connection between uC and U3/CH430 using RXD0/TXD0?

Any suggestion is very much welcome!

**Comment by Arthur75012** [comment]
Hello
This is my wiring : I had to weld 2 wires on theses tow resistors (see pictures) to get the rx/tx connection
![IMG_20210405_125535](https://user-images.githubusercontent.com/64860026/113567380-cee8bd80-960e-11eb-964a-736c0b65297f.jpg)

**Comment by petervflocke** [comment]
Ok, so you use the  connection between uC and U3/CH430 using RXD0/TXD0.
OK, many thanks for responding.
