### ISSUE TITLE
[FEATURE REQUEST] MKS Nano V3 SD onboard 

### ISSUE THREAD

**Issue by Lino77** [luc-github/ESP8266#614]
it is possible to access the onboard sd card directly via spi, the MKS Nano V3 has spi and serial
https://github.com/makerbase-mks/MKS-Robin-Nano-V3.X

**Comment by luc-github** [comment]
not from ESP3D , also unlike Reprap, Marlin does not allows to share spi between ESP board and MKS Board

**Comment by luc-github** [comment]
at least not currently - and not soon I think

**Comment by Lino77** [comment]
OKay THX
