### ISSUE TITLE
[Question] How to communicate ESP3D and MKSTFT_Marlin_Touch through the wifi port?

### ISSUE THREAD

**Issue by tomasbaldi** [luc-github/ESP8266#622]
Hello, for several days I have been trying to communicate with my MKS TFT 28, through the wifi port. I understand that you have already solved it.

Is there a protocol in which I can communicate to request the temperature? Or should I just send a gcode over the UART in plain text?

Thanks you!!!

**Comment by luc-github** [comment]
just enable mks serial before flashing esp3d 3.0, and use 115200 for baudrate

then send  M105 to get temperatures
