### ISSUE TITLE
[Question]Error after updateing MKS wi-fi esp12e

### ISSUE THREAD

**Issue by themacboy** [luc-github/ESP8266#628]
Good morning,

I just compiled Esp3d to install in my Mks ribin wi-fi module, and all looks right, but after uploading the index.html.gz i get this error:

![image](https://user-images.githubusercontent.com/8063711/117313226-fccb5700-ae85-11eb-9492-843a6b6fd21a.png)

Compiling word fine, my configurationis (and I know it worked for other people):
![image](https://user-images.githubusercontent.com/8063711/117314006-ac082e00-ae86-11eb-8b33-65311fa895f2.png)

![image](https://user-images.githubusercontent.com/8063711/117314198-ce01b080-ae86-11eb-87fd-bc745fd3823f.png)

Not sure what im doing wrong or how to check it

**Comment by luc-github** [comment]
I need ESP3D FW version and webUI version you are using

**Comment by themacboy** [comment]
I have downloaded v.3 version:
https://github.com/luc-github/ESP3D/tree/3.0

and webUI this file, form 2.1:

https://github.com/luc-github/ESP3D-WEBUI/blob/2.1/index.html.gz

No sure if there is a v.3 html

**Comment by luc-github** [comment]
so this is your problem - the read me is pretty clear:
![image](https://user-images.githubusercontent.com/8822552/117338344-bf26f800-ae9e-11eb-9737-d09609329679.png)

And the first boot embedded page menu also link to webUI 3.0

**Comment by themacboy** [comment]
lol sorry. I will test in next 3 hours and close it

**Comment by themacboy** [comment]
Solved, your were right.

I only needed additional help from other user, due filesystem wasn't removed after update and error continues. The member told me to install original Mks bin to reset all the chip, and later reinstall Esp3d, and worjed fine. 

Thx all

**Comment by luc-github** [comment]
use the embedded  maintenance page
`htttp://yourip?forcefallback=yes`

**Comment by themacboy** [comment]
> use the embedded maintenance page
> `htttp://yourip?forcefallback=yes`

Thx, nice to know

**Comment by luc-github** [comment]
@themacboy what request?

**Comment by themacboy** [comment]
LoL wrong github jajaja sorry
