### ISSUE TITLE
[QUESTION] Question about DEFAULT_IP_VALUE

### ISSUE THREAD

**Issue by trengtor** [luc-github/ESP8266#642]
As I understand it, DEFAULT_IP_VALUE describes the IP address for the gateway in AP mode.
But in network client mode, this is the client's address.
How to specify the gateway separate IP address for the network client mode?

**Comment by luc-github** [comment]
Do not change DEFAULT_IP_VALUE it is a default value for setup 
use webUI or direct commands to change IP https://github.com/luc-github/ESP3D/wiki/Direct-ESP3D-commands

**Comment by trengtor** [comment]
> Do not change DEFAULT_IP_VALUE it is a default value for setup
> use webUI or direct commands to change IP https://github.com/luc-github/ESP3D/wiki/Direct-ESP3D-commands

I use DEFAULT_IP_VALUE as a static IP-addres for ESP in LAN client mode.

**Comment by luc-github** [comment]
I move this thread to discussions as it is not an issue
