### ISSUE TITLE
wron wiring on https://github.com/luc-github/ESP3D/wiki/Smoothieboard

### ISSUE THREAD

**Issue by ProfMarte** [luc-github/ESP8266#644]
Hello,
looking about how to connect ESP-12 or ESP-01 to the smoothieboard I went over 
https://github.com/luc-github/ESP3D/wiki/Smoothieboard
I found that with JP5 all would be fine with TX0 and RX0 but wondering, that there should be a level conversion between ESP-xy and µC, while the µC on smoothieboard also works with 3V3. So looking in the schematic 
https://smoothieware.org/smoothieboard-schematic
there you can see, that it is like I suggested. 
By simply switch JP5 Pin 3 with SJ1 to 3V3 all will be fine with JP5 supporting an ESP01 or ESP12 directly with 3V3 and the correct 3V3 level with RX_0 and TX_0 from the LPC1769. So there is definitely no need for any level translators nor any 3V3 voltage regulators as requested 
here
https://github.com/luc-github/ESP3D/wiki/ESP8266-01 and 
https://github.com/luc-github/ESP3D/wiki/ESP8266-12E-F and
https://github.com/luc-github/ESP3D/wiki/ESP-32-CAM with RX using two resistors
also
https://github.com/luc-github/ESP3D/wiki/D1-mini there is no need for level converter

Am I wrong or why these Resistors / level-conversion?  

Regards
Marte

**Comment by luc-github** [comment]
did you checked the wiki ? it has entry for smoothieware board

**Comment by luc-github** [comment]
you do not need any level converter if you use 3.3v board / power supply, not all boards are 3.3v, several boards like mega ramps ard 5v and need logic shifter / diode / resistor
As you mentioned smoothie board do not need any power conversion and it is well mentioned in wiki for smoothieware - use 3,3V not 5V

**Comment by luc-github** [comment]
why https://github.com/luc-github/ESP3D/wiki/Smoothieboard is wrong ? picture come from smoothieware itself
