### ISSUE TITLE
[QUESTION]MKS Nano Robin

### ISSUE THREAD

**Issue by iNDeX999** [luc-github/ESP8266#646]
Hi,

i have flashed ESP3D to my MKS WIFI  (MKS NANO V3 / TS35)
(Firmware: https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware.git)

#define MOTHERBOARD BOARD_MKS_ROBIN_NANO_V3
#define TFT_LVGL_UI
#define MKS_WIFI_MODULE

ESP3D FW_VERSION "2.1.1.b10" with and without MKS_TFT_FEATURE compiled

But i cannot connect to the printer in the ESP3D Gui

Did i misse something?

**Comment by luc-github** [comment]
the ESP3D 2.X branch emulate the hk wifi device of MKS which use AT commands and is not for MKS Nano but MKS TFT
to use ESP3D on MKS Nano you need to use the ESP3D 3.0 branch and enable MKS Serial protocol in configuration.h and also read https://github.com/luc-github/ESP3D/discussions/620
