### ISSUE TITLE
Why is my esp3d only working on the TTL adapter?

### ISSUE THREAD

**Issue by niekjuuhh** [luc-github/ESP8266#650]
Hi reader,

I was wondering if someone could help me out with the following problem:

I am running esp3d on my esp8266-01s chip. The problem is that the chip only starts the wifi when its connected with the ttl adapter. When i plug exactly the same chip on my skr 1.4 turbo the esp8266 is not starting the signal.

Please help me out

Regrads

**Comment by luc-github** [comment]
is your ESP01S from BTT or from another supplier?
looks same as https://github.com/luc-github/ESP3D/issues/598

**Comment by niekjuuhh** [comment]
> is your ESP01S from BTT or from another supplier?
> looks same as #598

Thanks luc for your reply, Thats working fine now. The next problem i have is that the printer is not communicating with the webserver.

Hardwareserial.h already has been set to the right configurations because thats a standard of platformio now.

Do i need to add #define LPC_PINCFG_UART3_P4_28 somewere? Inside the configuration.h file it isn't working.

Please help me out.

**Comment by luc-github** [comment]
this pure marlin configuration which Change quite often, did you checked https://youtu.be/NGgzw-XayEo or Marlin github issue tracker ?

**Comment by luc-github** [comment]
be sure baudrate are identical in Marlin and ESP3D and serial port configuration is same as video

**Comment by niekjuuhh** [comment]
> this pure marlin configuration which Change quite often, did you checked https://youtu.be/NGgzw-XayEo or Marlin github issue tracker ?

I followed the video, changed everything like him. But for some reason the printer is not connected to the webserver :(


`      #if defined(LPC_PINCFG_UART3_P4_28)
        PinCfg.Funcnum = 3;
        PinCfg.Portnum = 4;
        PinCfg.Pinnum = 28;
        PINSEL_ConfigPin(&PinCfg);
        PinCfg.Pinnum = 29;
        PINSEL_ConfigPin(&PinCfg);
      #elif defined(LPC_PINCFG_UART3_P0_25)
        PinCfg.Funcnum = 3;
        PinCfg.Portnum = 0;
        PinCfg.Pinnum = 25;
        PINSEL_ConfigPin(&PinCfg);
        PinCfg.Pinnum = 26;
        PINSEL_ConfigPin(&PinCfg);
      #else
        PinCfg.Funcnum = 2;
        PinCfg.Portnum = 0;
        PinCfg.Pinnum = 0;
        PINSEL_ConfigPin(&PinCfg);
        PinCfg.Pinnum = 1;
        PINSEL_ConfigPin(&PinCfg);
      #endif
      CLKPWR_SetPCLKDiv(CLKPWR_PCLKSEL_UART3, CLKPWR_PCLKSEL_CCLK_DIV_1);
    } `

Is it possible that i have to define LPC_PINCFG_UART3_P4_28?

**Comment by niekjuuhh** [comment]
> be sure baudrate are identical in Marlin and ESP3D and serial port configuration is same as video

Both are 250000!

**Comment by luc-github** [comment]
share your configuration.h of Marlin to see if something pop up - but I cannot be sure I can help
