### ISSUE TITLE
[BUG] Notifications cannot be sent when on ESP32

### ISSUE THREAD

**Issue by MarSoft** [luc-github/ESP8266#653]
**Describe the bug**
Sending notifications works fine on my ESP8266 board. But after I switched to ESP32, it stopped working.
After enabling debug messages and adding some additional logs to `WiFiClientSecure` library, I found that we do not `setCACert()` for the `WiFiClientSecure` library, and don't `setInsecure` - there is a call to `setInsecure` but only for ESP8266.
As a result, the library tries to setup secure SSL connection without a CA certificate and fails.
According to the [`Secure` example](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/examples/WiFiClientSecure/WiFiClientSecure.ino) and [library docs](https://github.com/espressif/arduino-esp32/tree/master/libraries/WiFiClientSecure), we should *either* provide CA cert *or* call `setInsecure`.

So I think it is a bug that `setInsecure` is disabled on ESP32.

**To Reproduce**
1. Build ESP3D for ESP32 platform and install it
2. Configure notifications
3. Notifications are not sent

**Expected behavior**
Notification sending should work.

**ESP3D Firmware:**
- ESP core version: I don't know
- Version: 3.0
- Web UI Version: n/a
- Wifi mode: STA
- Flash method: PlatformIO
- Any change done in FW: none, then enabled logging

**Board used (please complete the following information):**
 - MCU: ESP32
 - Name: ESP32CAM
 - Flash size: 4M

**Comment by luc-github** [comment]
this is linked to esp32 core version in 1.x it was not necessary, it seems now in 2.x setInsecure is mandatory like esp8266 
Thank you
