### ISSUE TITLE
[BUG] Upload index.html.gz not possible on ESP32

### ISSUE THREAD

**Issue by ReneHezser** [luc-github/ESP8266#659]
**Describe the bug**
Uploading the web ui compressed file is not possible on a ESP32. The browser shows an error **Upload failed (3): File write failed.**
I am using a Wemos D1 Mini ESP32 https://docs.platformio.org/en/latest/boards/espressif32/wemos_d1_mini32.html

**Expected behavior**
After flashing, uploading the index.html.gz is possible

**Screenshots**
The Wemos D1 mini ESP32 has 4MB of Ram. Using min_spiffs.csv for the partition layout prevents uploading the web ui file.
![image](https://user-images.githubusercontent.com/5988767/127769331-14d63752-5e44-449d-b610-e63f590ecb9e.png)
When putting the index.html into the data folder, the Filesystem Image could not be created.

**Solution**
Change the partition layout to *default.csv*
```
[env:esp32wemos_d1_mini]
platform = espressif32
;theboard
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
monitor_flags = --echo
monitor_filters = send_on_enter, colorize, esp32_exception_decoder
; None
build_flags = -DCORE_DEBUG_LEVEL=0
board_build.partitions = default.csv
upload_speed = 921600
lib_ignore = 
    ESPAsyncTCP
```

**Comment by luc-github** [comment]
it is not a bug  it is a known, limitation if  Bluetooth on esp32 is enabled it need min_spiffs.csv to fit the flash
on 2.1 webUI you can use lighter version by removing all languages but the one you need https://github.com/luc-github/ESP3D-WEBUI/tree/2.1/languages

That said it is right that in 2.1 there is no bluetooth module so it may not necessary to limit the flash size like this,  I have updated ini file accordingly - thank you for raising it
