### ISSUE TITLE
ESP3D 3.0 Out of order.

### ISSUE THREAD

**Issue by AntoszHUN** [luc-github/ESP8266#660]
ESP3D V3.0 fails VSC compilation. He writes an error all the time.

![01](https://user-images.githubusercontent.com/45710979/127773760-f0cbb030-0465-41ec-b2f1-6a38dc75bffb.jpg)
![02](https://user-images.githubusercontent.com/45710979/127773761-515a18d7-abea-4d04-a678-b64daf90a21c.jpg)

**Comment by luc-github** [comment]
it looks like a PlatformIO issue - check you platformIO installation, also be sure you have git installed - I saw some problem with PIO when git is not installed under windows and PIO not always request the installation

**Comment by AntoszHUN** [comment]
> 
> 
> it looks like a PlatformIO issue - check you platformIO installation, also be sure you have git installed - I saw some problem with PIO when git is not installed under windows and PIO not always request the installation

PlatformIO IDE is installed. But what is a git?

**Comment by luc-github** [comment]
https://git-scm.com/download/win

**Comment by AntoszHUN** [comment]
Another mistake.
![03](https://user-images.githubusercontent.com/45710979/127774272-db0a07e2-39a9-437f-9ec3-363612bbc3c1.jpg)

**Comment by luc-github** [comment]
just tested and it is ok on my side
![image](https://user-images.githubusercontent.com/8822552/127774292-305f7866-3c04-4a67-b971-4c30ce2f2162.png)

be sure you do a clean before building and of course use ESP32Cam env

**Comment by AntoszHUN** [comment]
> 
> 
> just tested and it is ok on my side
> ![image](https://user-images.githubusercontent.com/8822552/127774292-305f7866-3c04-4a67-b971-4c30ce2f2162.png)
> 
> be sure you do a clean before building and of course use ESP32Cam env

esp32dev ran flawlessly. But esp32cam doesn't want to be good.

**Comment by luc-github** [comment]
what are 
`[ESP800]`
and 
`[ESP420]plain` 

output ?

**Comment by AntoszHUN** [comment]
I had to rewrite the board. board = esp32cam is now good. : D

**Comment by AntoszHUN** [comment]
Good. I just can't see the wifi network.

**Comment by luc-github** [comment]
![image](https://user-images.githubusercontent.com/8822552/127777216-fc34afbd-1ffb-447c-9e86-5aca00b18dee.png)

it is a gif so quality is not great but real ui is ok 
![camera](https://user-images.githubusercontent.com/8822552/127777318-98e4cd3c-a804-4bce-a222-eff0c8c33734.gif)

Note : I just flashed using the espcam env without modifying like you did

**Comment by luc-github** [comment]
One bug is new : in AP mode wifi scan is not working anymore ..., it was before...
 I need to check if API changed in latest ESP32 core - or if it is a bug in core 
 EDIT: fixed...my mistake, one line was missing...

**Comment by AntoszHUN** [comment]
> 
> 
> One bug is new : in AP mode wifi scan is not working anymore ..., it was before...
> I need to check if API changed in latest ESP32 core - or if it is a bug in core
> EDIT: fixed...my mistake, one line was missing...

All right. I download and test.

**Comment by AntoszHUN** [comment]
I can't upload to it.
![04](https://user-images.githubusercontent.com/45710979/127780803-ba013c13-145e-44cb-857a-8e8761ac59b6.jpg)

**Comment by luc-github** [comment]
you changed the partition size - so Filesystem is corrupted: you do not have 1GB = 1023MB of Flash
you need to format 
open terminal tab by clicking it and type `[ESP710]FORMAT` then refresh

**Comment by AntoszHUN** [comment]
> 
> 
> you changed the partition size - so Filesystem is corrupted: you do not have 1GB = 1023MB of Flash
> you need to format
> open terminal tab by clicking it and type `[ESP710]FORMAT` then refresh

And I didn't rewrite anything.

**Comment by AntoszHUN** [comment]
I formatted and reinstalled. I get the same thing in the picture.

**Comment by luc-github** [comment]
you do not need to reinstall, just Format using esp command and eventualy restart board but refresh should enough, after flash size should be some kb
share ui  fs size after proceed

**Comment by AntoszHUN** [comment]
> 
> 
> you do not need to reinstall, just Format using esp command and eventualy restart board but refresh should enough, after flash size should be some kb
> share ui fs size after proceed

You don't want to format me with the ESP command.

**Comment by luc-github** [comment]
1 Type [ESP710]FORMAT
2 Refresh , if size is still incorrect Restart board

**Comment by AntoszHUN** [comment]
> 1 Type [ESP710]FORMAT
> 2 Refresh , if size is still incorrect Restart board

Where could i write it?

**Comment by luc-github** [comment]
like I told you before

![image](https://user-images.githubusercontent.com/8822552/127782296-c33b6917-8269-4d33-b26b-400b6b6a90f7.png)

**Comment by AntoszHUN** [comment]
> 
> 
> like I told you before
> 
> ![image](https://user-images.githubusercontent.com/8822552/127782296-c33b6917-8269-4d33-b26b-400b6b6a90f7.png)

Oh my stupid. Thanks! It worked. What files do I need to do now? just so I don't spoil it.

**Comment by luc-github** [comment]
![image](https://user-images.githubusercontent.com/8822552/127782672-5ab14e1f-d1fc-4cdd-a347-beb253a77b71.png)
https://github.com/luc-github/ESP3D-WEBUI/blob/3.0/dist/printer/production/index.html.gz

**Comment by AntoszHUN** [comment]
Thanks for all the help! It worked! Thank you for your perseverance!
