### ISSUE TITLE
[Question] Connecting ESP32 to the MKS TFT24 

### ISSUE THREAD

**Issue by primus192** [luc-github/ESP8266#667]
Hi. I have got printer with MKS GEN L board. My printer have MKS TFT24 touchscreen connected to AUX1 port. As i am concerned, this is the only usable serial port on the board and if i wanted to use esp3d i need to disconnect the touchscreen... However my TFT24 touchscreen have WiFi port on the back. Can i connect my ESP32 Devkit v1 to this WiFi port and somehow route the esp3d to mainboard via this connector? Can you give me any advice how to do this? Thanks!

**Comment by luc-github** [comment]
you cannot use same serial port for esp board and TFT, both are doing queries and the data flow willl be merged inconsistantly
Connecting ESP32 Devkit v1 to TFT WIFI port will work for moniitoring but unlikly for file upload - the file upload need super clean signal due to usage of very high baud rate, and with esp 32 devkit connected by cable will will have some EMI noise for sure that will corrupt high baud rate transfert

**Comment by primus192** [comment]
Okay, so what type of connection this issue covers? #523

**Comment by luc-github** [comment]
MKS WIFI devices connected with MKS WIFI module

**Comment by primus192** [comment]
So i cant upload esp3d on the module shown on the photo? 
![400px_wifi_10_01](https://user-images.githubusercontent.com/89576620/132827935-cf61810e-0abf-4023-8f59-f14da1ef9804.jpg)

**Comment by luc-github** [comment]
this one is not an esp32 dev kit, it is MKS WIFI module, so it works (file upload)

In all ESP moduleS  the esp3d FW can be loaded

**Comment by primus192** [comment]
Ok i see it is esp8266, so my esp32 should work if i correctly connect it. Will give it a try, thanks.

**Comment by luc-github** [comment]
no that is my point - put esp3d on it is not the issue
file upload / transfer may not work due to your connection having emi noise, but it may also work if you are lucky

**Comment by primus192** [comment]
I will try to connect it with shielded cable and will send you feedback/screenshots, thanks :)

**Comment by primus192** [comment]
#define COMMUNICATION_PROTOCOL MKS_SERIAL
This is needed?

**Comment by luc-github** [comment]
```
This is needed to uncomment it?

//MKS_SERIAL Mks protocol
```
no this the value to put as reference
read this : https://github.com/luc-github/ESP3D/discussions/620

**Comment by primus192** [comment]
Got a problem with uploading webui, it says file upload failed(13)

**Comment by luc-github** [comment]
It means size error 
can you do a screenshot of page with error ?

**Comment by primus192** [comment]
![image](https://user-images.githubusercontent.com/89576620/132846736-33f28497-dafd-4492-9ba9-0bc896d469a8.png)

**Comment by luc-github** [comment]
I think you FS is corrupted  - you should not have 95.60KB used space if nothing on FS
go to Terminal tab and click on it
type `[ESP710]FORMAT` wait for format done  then refresh page and try upload again

**Comment by primus192** [comment]
![image](https://user-images.githubusercontent.com/89576620/132847412-03de319c-2f5b-499e-8847-8a64f0b989fe.png)
Still failing

**Comment by primus192** [comment]
![image](https://user-images.githubusercontent.com/89576620/132847478-001ad967-6a39-4d93-a91c-b2823a22d53e.png)
I tried to push this file manually via VSCODE to the esp32 it works but when i click od ESP3D white screen appears and nothing is shown

**Comment by luc-github** [comment]
I am confused what board did you flashed ?

**Comment by primus192** [comment]
Esp32 Devkit V1

**Comment by luc-github** [comment]
what env did you selected in VS CODE ?

**Comment by primus192** [comment]
I just manually uploaded index.html.gz to the spiffs, because i couldnt do it via 192.168.0.1

**Comment by luc-github** [comment]
This is not my question - what env did you selected in VS Code for flashing your ESP32 ?

**Comment by primus192** [comment]
I flashed my esp32 via Arduino IDE

**Comment by luc-github** [comment]
what settings did you used  to flash in arduino then

**Comment by primus192** [comment]
Ok i selected wrong board, it is working now

**Comment by primus192** [comment]
![image](https://user-images.githubusercontent.com/89576620/132857359-387b54d6-4b16-41f4-bd23-69baca64d67b.png)
I need to connect it to the printer in order to see control panel?

**Comment by luc-github** [comment]
You need to define the target FW - it is Marlin in your case, and also you need to enable TFT SD and TFT USB in settings

**Comment by primus192** [comment]
![image](https://user-images.githubusercontent.com/89576620/132901486-39da47f7-26f5-4ea4-bd55-66e1672ed653.png)
Its working.. Thanks ;)

**Comment by luc-github** [comment]
Good I move this to discussion area then
