### ISSUE TITLE
I can't find/connect to a printer 

### ISSUE THREAD

**Issue by ManoelVictor9** [luc-github/ESP8266#669]
I'm trying for days connecting my printer in esp3d, however, on the esp3d local website, I can't find or connect the printer in printer configurations, I tried changing the serial port, but nothing changed.

![imagem_2021-09-17_093834](https://user-images.githubusercontent.com/90870002/133783778-8515c55c-d865-4828-a611-c03fc634ba6b.png)

esp 8266 Firmware: 
ESP3D
version 2.1.1
Wifi mode: Client Station
Flash Method: PlatformIO
UI Version: 2.1b57

(NodeMCU)
LoLin
NodeMCU V3
Flash Size: 4M: 2M/2M

Board ( MKS SGEN_L V2.0 ) Firmware: 
Marlin
Version: 2.0

![image](https://user-images.githubusercontent.com/90870002/133784605-d1a65d64-17e1-4180-b5b4-f56d07a2015c.png)

**Comment by luc-github** [comment]
please check the template as bot say
you do not provide any information to allow to allow to help you

**Comment by ManoelVictor9** [comment]
> please check the template as bot say
> you do not provide any information to allow to allow to help you

Done, I put more informations and pictures.

**Comment by luc-github** [comment]
Ok here what come to mind that need to check
* is only Printer configuration that does not respond or all commands ?
if not only here more check:
* Did you set proper port com for ESP board in Marlin configuration?
* do you use same baud rate between Marlin and ESP
* are you sure you did not put Rx->Rx and Tx->Tx instead of Rx->Tx and Tx-.Rx ?

*if only printer config is not working 
* what is the M503 output ?

**Comment by ManoelVictor9** [comment]
> Ok here what come to mind that need to check
> 
> * is only Printer configuration that does not respond or all commands ?
>   if not only here more check:
> * Did you set proper port com for ESP board in Marlin configuration?
> * do you use same baud rate between Marlin and ESP
> * are you sure you did not put Rx->Rx and Tx->Tx instead of Rx->Tx and Tx-.Rx ?
> 
> *if only printer config is not working
> 
> * what is the M503 output ?

I think the connections are plugged-in property and the Marlin configuration too, but I can't get any information from the printer sensors or use any command on the ESP3D website to the MKS board, so the MKS board and esp8266 are working separately, so I realized that the problem is in the transmition, but the question is where
That's the configuration of esp in platformio
![image](https://user-images.githubusercontent.com/90870002/133837609-dd71cea6-f6bb-49a6-9f07-129f1a9c1807.png)

**Comment by luc-github** [comment]
you do not need to change anything in platformIO if you use the latest git version - the git version has everything setup for esp8266
https://github.com/luc-github/ESP3D/blob/2.1.x/platformio.ini#L39-L64

**Comment by ManoelVictor9** [comment]
> you do not need to change anything in platformIO if you use the latest git version - the git version has everything setup for esp8266
> https://github.com/luc-github/ESP3D/blob/2.1.x/platformio.ini#L39-L64

Thanks, however I tried with this configuration and It didn't work. :/ I'll Join in ESP3D Discord with the developers and try to figure out why this is happening.

**Comment by ManoelVictor9** [comment]
> you do not need to change anything in platformIO if you use the latest git version - the git version has everything setup for esp8266
> https://github.com/luc-github/ESP3D/blob/2.1.x/platformio.ini#L39-L64

Thanks, however I tried with this configuration and It didn't work. :/ I'll Join in ESP3D Discord with the developers and try to figure out why this is happening.

**Comment by ManoelVictor9** [comment]
> you do not need to change anything in platformIO if you use the latest git version - the git version has everything setup for esp8266
> https://github.com/luc-github/ESP3D/blob/2.1.x/platformio.ini#L39-L64

Thanks, however I tried with this configuration and It didn't work. :/ I'll Join in ESP3D Discord with the developers and try to figure out why this is happening.

**Comment by luc-github** [comment]
developers?
I suggest you the check  I have  listed

**Comment by DivingDuck** [comment]
... and even better he should check what pins he try to connect.

**Comment by luc-github** [comment]
@ManoelVictor9 Any update?
