### ISSUE TITLE
[FEATURE REQUEST]<Direct SD upload, I see that you have written a part. >

### ISSUE THREAD

**Issue by xiaoyaoking** [luc-github/ESP8266#670]
Direct SD upload, I see that you have written a part. Do you have a plan to complete this function?

ESP8266 I test that I can read and write. It's messy to write my own code. I still hope I can use what you wrote.

My English is not good. I hope you can understand it.

![00001](https://user-images.githubusercontent.com/11435237/133914347-31d64201-73ff-491e-b8f3-4003aeacd800.jpg)
![0002](https://user-images.githubusercontent.com/11435237/133916694-19202327-8f06-4d0e-9cdc-afefae8407e6.jpg)
![0003](https://user-images.githubusercontent.com/11435237/133916696-4bd19933-a43b-48f5-81ab-7e5f023ded21.jpg)

**Comment by luc-github** [comment]
Direct SD upload is implemented in 3.0 so I do not understand your feature request

**Comment by xiaoyaoking** [comment]
> Direct SD upload is implemented in 3.0 so I do not understand your feature request

i 'm sorry... I don't see 3.0. I'm using 2.1

**Comment by luc-github** [comment]
https://github.com/luc-github/ESP3D/tree/3.0
