### ISSUE TITLE
[FEATURE REQUEST]Tuya compatibility?

### ISSUE THREAD

**Issue by DvoraNoob** [luc-github/ESP8266#672]
I don't know if it has compatibility, but could I add a connectivity option with a tuya socket?

**Comment by luc-github** [comment]
tuya xompatibility? do you have link to the modele you are refering to?

**Comment by DvoraNoob** [comment]
> tuya xompatibility? do you have link to the modele you are refering to?

Like this https://plugins.octoprint.org/plugins/tuyasmartplug/ with any smart switch
I don't know if is possible.

**Comment by Legsmaniac** [comment]
Easy to add your own with V3.0 by creating your own custom panel. 
I've done this for my Sonoff switch controlled via Home Assistant.

**Comment by DvoraNoob** [comment]
> Easy to add your own with V3.0 by creating your own custom panel.
> I've done this for my Sonoff switch controlled via Home Assistant.

I tried, but doesn't work. 
I don't know what ip I put in the box

**Comment by luc-github** [comment]
Looks like tuya use MQTT so it will be possible when https://github.com/luc-github/ESP3D/discussions/549#discussioncomment-292960 is implemented
