### ISSUE TITLE
[Question]<How to set up GPIO for Ethernet>

### ISSUE THREAD

**Issue by liu2-3zhi** [luc-github/ESP8266#678]
I want to configure Ethernet, but I don't find any config in pins.h.

**Comment by luc-github** [comment]
On which board ?

**Comment by liu2-3zhi** [comment]
I want to know the default GPIO port, and then draw the board by myself.

**Comment by luc-github** [comment]
which mcu ?

**Comment by liu2-3zhi** [comment]
ESP32  with LAN8720A-CP-TR

**Comment by luc-github** [comment]
ESP32 ?  - ESP 8266 ?

**Comment by liu2-3zhi** [comment]
esp32

**Comment by luc-github** [comment]
I have only tested the olimex :
https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware
https://github.com/espressif/arduino-esp32/blob/master/variants/esp32-poe/pins_arduino.h

**Comment by liu2-3zhi** [comment]
So, which file is the GPIO port set in? I did not find pins_arduino.h at https://github.com/luc-github/ESP3D.

**Comment by luc-github** [comment]
nowhere because I just used the board as it is , same as sample code :
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/ETH_LAN8720/ETH_LAN8720.ino

**Comment by luc-github** [comment]
https://github.com/OLIMEX/ESP32-POE/blob/master/HARDWARE/ESP32-PoE-hardware-revision-D/ESP32-PoE_Rev_D.pdf
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/ETH.h

If you need let me know - I did not added any config in pins.h as I did not needed

**Comment by liu2-3zhi** [comment]
Thanks, I understand, it should be connected like this
GPIO23-MDC

GPIO18-MDIO

GPIO17 CLK_IN

GPIO21-TX_EN

GPIO19-TX0

GPIO22 TX1

GPIO25-RX0

GPIO26-RX1

GPIO27-CRS_DRV

**Comment by liu2-3zhi** [comment]
But I still suggesr you to add relevant config in pin.h

**Comment by luc-github** [comment]
PR is welcome - you are the one who can check it easily

**Comment by liu2-3zhi** [comment]
> PR is welcome - you are the one who can check it easily

sorry, English is'n the official language in my country,so I poor with English.I can't understand what you say.

**Comment by luc-github** [comment]
what is your language and country ?

**Comment by liu2-3zhi** [comment]
> what is your language and country ?

Chinese ,China
I'm just a junior high school student.

**Comment by liu2-3zhi** [comment]
I first started contacting ESP3D just because I wanted to DIY a 3D printer of my own

**Comment by luc-github** [comment]
没问题，你可以 push code to github, 因为你可以很容易看看行不行

**Comment by liu2-3zhi** [comment]
Unfortunately, I still don't know much about editing and modifying C+ for the time being.

**Comment by luc-github** [comment]
学习,实践,没有其他的办法
加油

**Comment by liu2-3zhi** [comment]
> 学习,实践,没有其他的办法 加油

Can I add you to Telegram?

**Comment by luc-github** [comment]
I do not use telegram, I just setup for notification setup, you can join esp3d discord server https://discord.gg/95fWFMEn
