### ISSUE TITLE
[Question]<About ROTARY ENCODER>

### ISSUE THREAD

**Issue by liu2-3zhi** [luc-github/ESP8266#679]
//INPUT_DEVICE: allow input
//ROTARY_ENCODER        1
#define INPUT_DEVICE ROTARY_ENCODER

How to connect ROTARY ENCODER to ESP32? I did not find any configuration in pins.h

**Comment by luc-github** [comment]
It is planned but not yet implemented

**Comment by liu2-3zhi** [comment]
OK, thanks
