### ISSUE TITLE
How to setting Arduino IDE for esp8266-01 with blue color

### ISSUE THREAD

**Issue by alifasya** [luc-github/ESP8266#680]
I have 2 esp2866 modules, the black one and the blue one, the black one can be flashed with an Arduino Ide like the setup instructions in #443, but the instructions didn't work for flashing the blue esp8266.
What is the setting for the blue esp8266??

thank you

**Comment by luc-github** [comment]
the blue is 512KB flash size - right ? - it is not more supported sorry 
check https://github.com/luc-github/ESP3D/discussions/331

**Comment by alifasya** [comment]
ok thank for information
