### ISSUE TITLE
[Question] ESP3D/8266 Cannot pass data to Marlin based BTT E3 RRF 1.1

### ISSUE THREAD

**Issue by Cowbite** [luc-github/ESP8266#682]
What is your question ?
BTT E3 RRF 1.1 + ESP3D/8266 is installed on a Marlin based Ender 3.
I can access the ESP3D interface, view the IP, and view the printer dashboard but I cannot actually control anything or view any data from the printer.
How do you initialize the interface between the ESP and the firmware/printer?

**Comment by luc-github** [comment]
the communication must be configured in Marlin, when on RRF FW the communication is done via SPI, with Marlin the communication is done by serial, so you need to see how  to configure the serial port in Marlin for this board.
I do not have/ know this board unfortunatly

**Comment by luc-github** [comment]
solved by user https://github.com/luc-github/ESP3D/discussions/684
