### ISSUE TITLE
[Question]<ESP32CAM FATFS ERROR>

### ISSUE THREAD

**Issue by liqijian101** [luc-github/ESP8266#685]
HI,I test the  ESP32CAM FATFS ,but the web ui can't read the spiffs ,
Filesystem error,Total space:0B   ,Used Space:0.
how can i fix the error.

**Comment by luc-github** [comment]
Format the FS [ESP710]FORMAT

**Comment by liqijian101** [comment]
> Format the FS [ESP710]FORMAT
thanks,luc.
I have tried this . but it could not work.
I also have tried to change the partition table. I add the fat table, and  the size is larger than 1M.
How can i make the fat work.
the flash size of my esp32cam  is 4M

**Comment by luc-github** [comment]
do you use platformIO or Arduino ?

**Comment by liqijian101** [comment]
I use platformIO.

**Comment by luc-github** [comment]
so you  use the esp32cam env I provide?
you mention SPIFFS and FATFS which one did you set in configuration.h?

**Comment by liqijian101** [comment]
yes  ,I use the esp32cam env  and set fatfs in configuration.h

**Comment by luc-github** [comment]
ok so it won't work like this, you need to change the partition in platformio to use `board_build.partitions = default_ffat.csv`

Using FATFS is more for 8MB/16MB flash, for 4MB Flash like esp32cam I suggest more LittleFS

**Comment by liqijian101** [comment]
I understand.  I test littlefs ,the upload speed is about 270KB/s  ，so i what to use the fatfs to improve the speed

**Comment by liqijian101** [comment]
thanks, i use the  default_ffat.csv,it worked.
but when i upload the  index.html.gz, there is another error that file upload failed error(13).
This error code means that the file size is inconsistent

**Comment by luc-github** [comment]
Hmm yes it may be a a bug with FATFS  - TBH it has been long time I did not tested it as I use only littleFS on ESP32, I will check tomorrow, I suspect the when doing file stat  on fatFS it get 0 - it happened on littleFS after latest update of idf sdk

I will check and fix it tomorrow as it is late here now

**Comment by luc-github** [comment]
Ok I just fixed it v107

**Comment by liqijian101** [comment]
thanks, there is another problem that the web ui can not find sd card.
I test the ffat because I want to improve the upload speed.

**Comment by luc-github** [comment]
ffat is for flash not for SDCard
esp32cam need to set SDIO and directsd in configuration.h for SDCard

that said - what kind of file upload do you want to improve ?

**Comment by liqijian101** [comment]
i what to improve the upload  speed of  gcode. 
can I select the file system of sd card ？
now my upload speed is 250KB/s.

**Comment by luc-github** [comment]
but how your printer/cnc access esp32cam file ? esp3d does not stream gcode

**Comment by liqijian101** [comment]
i use the  analog switch chip to change signal.
so i just upload gcode to the sd.

**Comment by luc-github** [comment]
upload to esp32cam SD is not my question, it is working, that is for sure.

My question is how you printer access the SD reader  of esp32 card?

**Comment by liqijian101** [comment]
actually  I use the shared sd . when I upload gcode , the swhich chip  select to access the esp3d   ,else to access the printer

**Comment by luc-github** [comment]
Ho so you are not using esp32CAM SD acrd but external SD to put switch in between - right ?

**Comment by liqijian101** [comment]
yes ,I designed a pcb to  connect  esp32cam and printer.

**Comment by luc-github** [comment]
Ok

**Comment by liqijian101** [comment]
can you improve the upload speed?
I find another product ,that upload speed can reach to 1M.

**Comment by liqijian101** [comment]
to more people use the esp3d，
I can shared my pcb sch and layouts to your project.
in china ,it is very easy  to make a pcb ,even for free.

**Comment by luc-github** [comment]
which product  can reach 1M ?

**Comment by liqijian101** [comment]
fly3d
you can search in `TaoBao.`
![Uploading Screenshot_20211030_085235_com.taobao.taobao.jpg…]()

**Comment by luc-github** [comment]
Do they use esp32 ?

**Comment by liqijian101** [comment]
yes, they use esp32
![Screenshot_20211030_085235_com taobao taobao](https://user-images.githubusercontent.com/16173343/139515065-ff95be2a-70bf-47f0-a360-4e6caf242113.jpg)

**Comment by luc-github** [comment]
That is claim did you checked if you can have same ?
 what firmware do they use ?

**Comment by liqijian101** [comment]
i don't have one .but I think it's almost really.

**Comment by Legsmaniac** [comment]
Wow!  This discussion has filled my inbox tonight/this morning.

@luc-github This is the card I believe he's talking about which helps explain it better since it is in English and not Chinese.
[https://www.jayuk.org/product/fly-esp32-wifi-module-for-skr-pro-gtr-fly-407zg-and-fly-cdyv2/?v=79cba1185463](https://www.jayuk.org/product/fly-esp32-wifi-module-for-skr-pro-gtr-fly-407zg-and-fly-cdyv2/?v=79cba1185463)

@liqijian101 You say you don't have one, I'd suggest you get one and try it.  It appears it is this card that promises the upload speeds of 1.7M therefore has nothing to do with Luc's code.  I'm not sure why you're asking Luc to improve the upload speed when this is down to the card in question.  Are you using an SKR Pro mainboard then?

**Comment by luc-github** [comment]
1 - As far I know and per my test esp8266 web upload is faster than esp32 - yes it is weird, but it is the current situation using both latest code from arduino
2 - the fastest I know using esp8266 is RRF and it use RRF Firmware with special SPIdriver for ESP8266 and high speed SD and it reach 800KB, I never had time to dig in - to port it for ESP3D yet
3 - 1.7Mb/s is 1.7Mbits/sec => which is 200KBytes/sec which is consistent to what you have today 
4 - I am prety sure they use my FW as it looks a clone of http://www.panucatt.com/product_p/wb8266.htm but using ESP32 instead of ESP8266, it use multiplexer and I have opened the code in ESP3D v3, the original speed was 280KB/s per @royco tests, so again speeds are consistent

**Comment by luc-github** [comment]
I am ok to improve - but I need some directions / tracks  / references

**Comment by liqijian101** [comment]
I confirmed the speed  of the fly3d is MB/s,not Mb/s.
I get the information from the fly3d user.
but their firmware is not open.

**Comment by luc-github** [comment]
Well I do not have this board - I cannot buy on taobao, and without code source... I do not see how to reach the same 1.2MB web upload

**Comment by liqijian101** [comment]
hi luc , i  find out that the fly3d used  the rrf.
their printer's board must use rrf

**Comment by luc-github** [comment]
@liqijian101 is that this board ? https://www.bilibili.com/video/BV1QQ4y197m5/?p=2&spm_id_from=pageDriver

I will try to order some boards thanks @Legsmaniac link and see what are the performances and usages

Edit: ok on link the site they do not sell to Taiwan - I need another way to order them

Edit2: Found it on aliexpress: https://www.aliexpress.com/item/1005003077964768.html

The sources for RRF are here https://github.com/gloomyandy/DuetWiFiSocketServer they are not closed actually

**Comment by liqijian101** [comment]
the link of video is my board  that  used esp3d.  
you found my bilibili video.

**Comment by luc-github** [comment]
haha ok :P but the bord is yours ?

**Comment by liqijian101** [comment]
I can buy the fly3d wifi board from Tao Bao, and send to you .  But you need a stm32f407 printer board or skr boad , and install fly3d rrf firmware.

**Comment by luc-github** [comment]
I have some boards for this from BTT - they send me some
It has been a long time I must check the rrf code - the gloomyandy repo is very very active - I even missed they already ported the rrf FW to esp32 - I will check what they used - especially for web server which is slow on esp32 - but if they did have improved version of web server it really worth to try

**Comment by liqijian101** [comment]
the board on bilibili is mine. I make that board.
after several days ，I will launch another esp3d module that use esp32cam

**Comment by luc-github** [comment]
Ok sorry I have not have been really focus on github last couple of month, I was more focusing on my moving, now my pets are finally arrived and we are almost settled, I can focus more on coding

**Comment by Anion-anion** [comment]
Luc! My plan to write pictures to the sd and upload them to the browser to make the files on the printer's sd card correspond to the pictures on the esp32 sd card. Tell me how to upload a file to the browser from the sd card (it loads easily from the esp, but I don't understand how from the sd card)

**Comment by luc-github** [comment]
just put /SD/  on path 
`http://your ip/SD/filename.gco`
