### ISSUE TITLE
[Question]<File upload is very slow>

### ISSUE THREAD

**Issue by mahdiEng** [luc-github/ESP8266#687]
I want to upload this file wich is 11mb but after 5 minutes it still has only one percent complete
![Capture](https://user-images.githubusercontent.com/76478183/139805072-0eb8e423-ec32-4b97-bd26-cad2d305e659.PNG)
.

**Comment by luc-github** [comment]
yes https://github.com/luc-github/ESP3D/discussions/535

**Comment by mahdiEng** [comment]
thanks.
