### ISSUE TITLE
Cannot compile project if using latest https://github.com/esp8266/Arduino

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#7]
this is due to string management different than in sandeep's module
if remove all macro F() and all PROGMEM it can compile and ESP is working properly

need to see how to handle this

**Comment by TRoager** [comment]
Ill follow here because i get the same error something about hasarg..

**Comment by luc-github** [comment]
does removing F() and PROGMEM worked for you also ?

what is hasarg?

**Comment by luc-github** [comment]
F() was not doing anything before 
should be same for PROGMEM but I did not checked -  looking a http://www.arduino.cc/en/Reference/PROGMEM 
it can be read directly

**Comment by TRoager** [comment]
![screen shot 05-23-15 at 07 38 pm](https://cloud.githubusercontent.com/assets/1173155/7785158/548e42b0-0183-11e5-98ef-4c5ebf351924.PNG)

**Comment by TRoager** [comment]
Dunno if that was the same problem you guys have. But heres my compile error, without editing anything :/

**Comment by luc-github** [comment]
nope you is looks like typo issue should be ```hasArg``` not ```hasarg```

for the ```onNotFound``` it may due to version of ESP8266 you use - do you use the download from board manager ? did you use sandeep version before ?

**Comment by TRoager** [comment]
i used https://github.com/sandeepmistry/esp8266-Arduino , and changed hasarg to hasArg and everything compiles fine now. Now ill try and upload it :)

**Comment by luc-github** [comment]
the  0.0.5 worked fine for me but I wanted to use the board manager version because all update will come by this one,  I think sandeep won t maintain his repo anymore as no need

**Comment by luc-github** [comment]
fixed with https://github.com/luc-github/ESP8266/commit/f48e419e0ff81413954debcb219540a543689ee1

Using properly PROGMEM allows to save 4k of memory currently almost 22K after first page displayed
