### ISSUE TITLE
[FEATURE REQUEST]Setup Mode

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#715]
As now more people want to use AP mode instead of Client Mode there are some issues raised, because current AP mode is actually made for setup and not for full usage, it will be quickly overloaded, indeed current AP mode is made to catch every query / requests and handle them which lead to trouble if intensive bandwith is used.

So I will add a new mode : Setup mode, and modify the  current AP mode, here the feature list of each mode for reference

Mode | Setup (Access point) | AP  (Access point)| STA (Client)
------|-------------------------|--------------------|-----------
Usage| Setup only | Normal | Normal
Captive Portal | Yes | No | No
mDNS | No | No | Yes
SSDP | No | No | Yes
Gateway | Yes (Self) | No |  Yes  (AP)
DNS | Yes (self) | No | Yes (AP)
 
If Client mode failed it should go to Setup mode.

I will add this in ESP3D 3.0 / ESP3DLib 2.0
 
 Feedback are welcome

**Comment by luc-github** [comment]
Here the workflow of wifi mode according boot process 
![WiFI setup](https://user-images.githubusercontent.com/8822552/152675181-353838dc-1e4b-4adc-8ee6-d73595da06a9.png)

**Comment by ETE-Design** [comment]
Will it also be possible to change between the modes with "Direct ESP3D Commands" like Reset to "Setup" if you get a new AP.

**Comment by luc-github** [comment]
Yes it is implemented - but I did not updated wiki yet
```
[ESP104](State) - display/set sta fallback mode which can be BT, SETUP, OFF
[ESP110](State) - display/set radio state which can be BT, WIFI-STA, WIFI-AP, WIFI-SETUP, ETH-STA, OFF
```

EDIT: Wiki updated https://raw.githubusercontent.com/wiki/luc-github/ESP3D/docs/Commands3.txt

**Comment by ETE-Design** [comment]
@luc-github Is [ESP104] SETUP and [ESP110] WIFI-SETUP almost the same? Only thing that [ESP104] SETUP have is a Fallback if it can't connect?
