### ISSUE TITLE
[FEATURE REQUEST]<MKS Flash Mode>

### ISSUE THREAD

**Issue by ETE-Design** [luc-github/ESP8266#716]
Can you somehow find a way to make MKSWifi.Bin, so when you compile the ESP3D you could choose to make it MKS Compatible. That way you only need to copy the MKSWifi.Bin to an SD-Card, insert it in your 3D Printer and turn it on... Then it will upload the firmware to the MKS Wifi Board.
The Source for the Original MKS Wifi Firmware is out there, so mabye you can find the right way to compile it that way.

**Comment by luc-github** [comment]
So you just want the building process rename **firmware.bin** to **MksWifi.bin**
I have checked https://github.com/makerbase-mks/MKS-WIFI
step 6:
```
6 If you connect the wifi module to PC, you can use the upload function of Arduino to flash the firmware;
 if not, you can directly copy the ".bin" file to the sd card, insert to the MKS robin series 
or TFT series board, it can automatically update the wifi firmware. 
** Hint: to export the "*.bin" file, you can click the Sketch > Export compiled Binary on Arduino, the ".bin"
 file will be exported to the project directory, 

remember rename the file to "MksWifi.bin" before copy it to sdcard.

```

Currently I use same method ^_^

That said on platformio - a python script could be added at the end of the compilation process - it can be added in list of https://github.com/luc-github/ESP3D/issues/478

**Comment by ETE-Design** [comment]
@luc-github Would be great to add, cause will then make it really easy for MKS People to use ESP3D

**Comment by ETE-Design** [comment]
@luc-github Will you add this "feature" :-)
