### ISSUE TITLE
ANET A8 WITH WIFI

### ISSUE THREAD

**Issue by Leociao06** [luc-github/ESP8266#718]
hi everyone, I have a rather particular question:
I am a beginner so I apologize in advance if it is an obvious or stupid question.
So, I recently bought an ANET A8 3d printer and was looking to add wifi control to it. I have motherboard v 1.7 and so I followed this photo to connect the TX and RX (https://user-images.githubusercontent.com/51383186/59010169-9d471580-8830-11e9-97a9-ba0b46776449.jpg). I have an esp8266 to which I flashed a code that creates in it a tcp / ip server (basically a terminal over wifi) in this way I can read and write data to and from the rx and tx pins of the esp8266. I connected the pin rx (ANET) to the tx (ESP8266) and the tx (ANET) with the rx (ESP8266). Not needing power, I only connected the ground coming from my Anet with the ground of the esp8266 to "activate" the serial communication. Through all this procedure, once the printer is turned on, I am able to receive the serial data that the printer sends but I cannot send the G-CODES to it. Please tell me what am I wrong.
I await an answer as soon as possible

**Comment by luc-github** [comment]
I push question to discussion
