### ISSUE TITLE
[BUG]Error compiling : hwcrypto/sha.h: No such file or directory

### ISSUE THREAD

**Issue by X3msnake** [luc-github/ESP8266#722]
**Describe the bug**
exit status 1
Error compiling for board AI Thinker ESP32-CAM.

ResolveLibrary(hwcrypto/sha.h)
  -> candidates: []C:\Users\Utilizador\Documents\Arduino\libraries\arduinoWebSockets\src\WebSockets.cpp:42:10: fatal error: hwcrypto/sha.h: No such file or directory
 #include <hwcrypto/sha.h>

**To Reproduce**

Followed the instruction on the page, copied the libraries and at uploading it gives me the above error

AI-Thinker ESP32-CAM, Arduino IDE 1.8.19 - Windows 10

**Comment by luc-github** [comment]
what version of the esp32 core are you using ?

**Comment by X3msnake** [comment]
2.0.2 i think, should i use a older version?

![image](https://user-images.githubusercontent.com/11083514/155171033-407cb5e5-d9e4-4fc1-959a-1bd02a882cc7.png)

**Comment by luc-github** [comment]
2.0.2 is correct it use idf 4.4

**Comment by luc-github** [comment]
so I am guessing you do not use the proper websocket arduino library version - you use the one present in repository of 2.1 whhich is 2.1.0 for core 1.X 
the one I have put in 3.0 is for core 4.X it is version 2.3.5 https://github.com/luc-github/ESP3D/tree/3.0/libraries/arduinoWebSockets-2.3.5
https://github.com/luc-github/ESP3D/blob/3.0/libraries/arduinoWebSockets-2.3.5/src/WebSockets.cpp#L44-L48

you must match librairies versions present in each branch

**Comment by X3msnake** [comment]
Ok, i'll try compiling 3.0 with the libraries you mentioned installed now

**Comment by X3msnake** [comment]
It worked, thanks. sent you a token of my appreciation for the project via paypal. Best regards


![image](https://user-images.githubusercontent.com/11083514/155177023-c27620ac-69ba-42f3-9d1b-19b04a8b98b2.png)

**Comment by luc-github** [comment]
@X3msnake thank you ^_^
