### ISSUE TITLE
[Question]<ESP32-CAM SD card, cannot see any files>

### ISSUE THREAD

**Issue by X3msnake** [luc-github/ESP8266#723]
Greetings Masters

Finally managed to install version 2.1.1 after battelling with the libraries, ended up uninstalling and resetting the arduino IDE and starting all from scratch folling the instrutions.

Now the UI is working and it is connecting to the board. however i am using ESP32-CAM and was hoping i could use the SD card it has.

Is there any special config one must do to use the card on this hardware?

**Comment by luc-github** [comment]
esp32 camera is supported in ESP3D 3.0
Direct SD card connection is supported in 3.0 but streaming GCode is not yet implemented so SD usage is currently limited to configuration file storage.

**Comment by X3msnake** [comment]
Oh :|

In that case I cannot use it untill then. Was hoping i could use it as a GRBL streamer since the board on my 3018 Vevor CNC machine farm do not have any native SD card support like on the 3DPrinters

Any ETA on the implementation of streaming from SD card for the ESP32-CAM?

**Comment by luc-github** [comment]
No sorry but you can check update here : https://github.com/luc-github/ESP3D/issues/243

**Comment by X3msnake** [comment]
Ok Master i've subscribed to alerts on that issue i'll keep an eye out for your updates on it, untill then i guess i'll have to invest in some old fashion grbl offline controllers or build some from scratch like on [this git](https://github.com/cguerrero1205/LCD_GRBL) and keep swapping sd cards for prodution.

Wish i could help speed things up but i'm crap at coding :( 
Best wishes, keep up the great work
