### ISSUE TITLE
[Question]<build error>

### ISSUE THREAD

**Issue by Enzo-Enz** [luc-github/ESP8266#727]
What is your question ?
Hi 
when I click build I get this error while I have been installed git client
is there any way to solve the error?

![Screenshot (6)](https://user-images.githubusercontent.com/75531691/156588955-84880801-fbf2-402a-bfd8-aeaa1cff35c0.png)

**Comment by luc-github** [comment]
the message explain how to solve it
you need git client and message even give you where to dowload

**Comment by Enzo-Enz** [comment]
> the message explain how to solve it you need git client and message even give you where to dowload

as you can see in my start menu I already installed it!

**Comment by Enzo-Enz** [comment]
sorry I restart my computer and It fixed!
