### ISSUE TITLE
[Question] settings for flashing ESP32 version with flash download tools 3.6.7 

### ISSUE THREAD

**Issue by digant73** [luc-github/ESP8266#730]
I compiled ESP3D for my ESP32 dev board (WROOM32) using `env:esp32dev` as the target in platformio.ini. I'm using "flash download tools 3.6.7" to flash the created files `firmware.bin` and `partitions.bin` but I need the proper settings to use (e.g. base address for files, SPI Mode (is it QIO?), Flash size (my board is 32Mbit) etc...). Is it possible to provide them?

**Comment by luc-github** [comment]
why not use platformio to flash ?

never used this flash tool

**Comment by digant73** [comment]
Yes, at the end I used platformio. It seems not all the binaries (they are 4) are created in case I want/need to use another tool for flashing.

Something not related to this problem. In BTT TFT fw I added the support to M28 and M29 also for writing to the TFT's SD and USB. The commands are:

```
M28 SD:<file path>
or
M28 S <file path>

```
for writing to SD.

```
M28 U:<file path>
or
M28 U <file path>

```
for writing to USB.

`M29 
`
for stopping the write.

Those commands are compatible with M28/M29 you already implemented for mainboard (although line number and checksum will be simply not taken into account).
My PR should be merged in the next days. I already tested it with ESP3D and it properly works. On BTT fw I also fixed the issue with M28/M29 towards mainboard (the commands between M28 and M29 were also processed by BTT fw causing a lot of beeps and errors.

**Comment by luc-github** [comment]
I think it would be easier to get the upload info/missing binaries by using arduino ide and esp32 tools directory of esp32 package

It is great you did such PR, ignoring check sum should not be a problem if serial connection is ok. 
Did you check the reliability and speed ?

**Comment by digant73** [comment]
yes, the reliability was ok. I set 500000 as serial speed. BTT fw allows also a speed of 1000000 (as in Marlin fw) but ESP3D allows a maximum of 921600. If 1000000 could be configurable also in ESP3D it should be better (I would try and use that speed)

**Comment by luc-github** [comment]
Yes because these speed are not well supported : https://github.com/luc-github/ESP3D/issues/350#issuecomment-511133797
you can also see that even it looks correct, it may not if you do not proper comparaison, - serial can corrupt data if too fast
https://github.com/luc-github/ESP3D/issues/296#issuecomment-460858342 which may not pop up to eyes as GCODE is text file
so final resul may be hazardous

**Comment by digant73** [comment]
understood, thanks!
