### ISSUE TITLE
[FEATURE REQUEST] M28/M29 support on BTT TFF FW

### ISSUE THREAD

**Issue by digant73** [luc-github/ESP8266#731]
Hi

As already anticipated some days ago, M28/M29 are now also supported by the official BTT TFT fw. On it's README.MD I reported a table with all the commands currently supported by TFT fw (see section `Printing from Host`).
It should be nice if M28/M29 could be now supported by ESP3D fw. Basically it is simply needed to send M28 SD:<file_path> or M28 U:<file_path> to start the write. M29 to stop the write. ESP3D can send all the commands to write on file using checksum (as currently done on onboard SD). Line number and checksum will be simply removed/ignored by TFT fw (because not currently supported).
Furthermore, the writing on onboard SD is now fixed (previously TFT fw was also processing the received commands causing the write failure and a lot of beeps on TFT).

**Comment by luc-github** [comment]
Thank you I will see what need to be done, did you do some evaluation to see what is the transfer speed ?
is that same as current M28/M29 protocol ? which is around 0.4Kb/s

**Comment by digant73** [comment]
I tested it on a ESP-01S and ESP-12S both connected to TFT at 500000b/s with no issue

**Comment by luc-github** [comment]
humm I guess you are mean baud rate

I mean effective data transfer rate=> 1MB file take how long to be transfered?

**Comment by digant73** [comment]
Made some measurements.
A file of 1,106,458 bytes uploaded in 27:30 minutes -> 1,053KB/s of transfer rate.
Same rate for small files (e.g. 120KB -> 0,99KB/s).

**Comment by luc-github** [comment]
Ok so very slow ^_^ faster because not checking the checksum integrity but still slow like hell
The M28/M29 transfer protocol is currently supported in ESP3D 2.1X and webUI 2.1 so I guess it is just a modification of webUI to tell him to allow upload on BTT TFT using the SD: U: filename prefix 

I am currently on 3.0 so I need to find time for this

**Comment by luc-github** [comment]
You may be interrested on this https://github.com/luc-github/ESP3D/issues/575
MKS protocol allow up to 100KB/s

**Comment by digant73** [comment]
yes, it is needed only to add support to M28 SD:<file_path> (for TFT SD), M28 U:<file_path> (for TFT USB)

**Comment by digant73** [comment]
> You may be interrested on this #575 MKS protocol allow up to 100KB/s

interesting. But are you working to add it in the ESP3D fw? TFT seems not involved in that.
I have an MKS WiFi module (ESP12S) connected to a MKS TFT and an ESP01S connected to a BTT TFT.

**Comment by luc-github** [comment]
Yes this is the plan and as mentioned need to integrate in other FW 
>adding a daughter library / Serial protocol accross FW (Repetier / Marlin / Smoothieware/ TBD...)

Which include TFT of course

I have discussed with BTT already and one issue is some BTT boards not always connect IO2 pin but only IO0 pin which make mimic of MKS protocol challenging

**Comment by digant73** [comment]
ok. I have a BTT TFT35 V3 and MKS TFT28 V4 eventually just to make some testing.
As far as I see, the MKS Wifi module has IO0 and IO1 while esp01s (on BTT TFT) has IO0 and IO2. Do you know if BTT TFT35 V3 is one of the TFT that could support MKS protocol? is there a lib implementing MKS protocol I could have a look?

**Comment by ETE-Design** [comment]
@digant73 Would be very interesting if the BTT TFT35 V3 could be implemented with MKS Protocol :-)

**Comment by luc-github** [comment]
ESP3D V3 do not support M28/M29 protocol because too slow and subject to error in real environement, so this implementation won't happen - sorry
