### ISSUE TITLE
[FEATURE REQUEST] ESP32 Camera

### ISSUE THREAD

**Issue by GamerClassN7** [luc-github/ESP8266#732]
**Describe the solution you'd like**
Ablility to prewiev Live Camera feed on ES32

**Additional context**
Bord i have
https://www.conrad.cz/p/joy-it-sbc-esp32-cam-1-ks-2332111?&vat=true&gclid=CjwKCAjwrfCRBhAXEiwAnkmKmfYhBGEvs2KkKWiUQZHUWTAjbH57NOLzI3dMgZrkWGAOAHwqfV1ZvhoCbtkQAvD_BwE

**Comment by luc-github** [comment]
it is implemented in 3.0 https://github.com/luc-github/ESP3D-WEBUI/issues/123#issuecomment-718693756

**Comment by GamerClassN7** [comment]
Oh Nice :) when it will be released ?

**Comment by luc-github** [comment]
when it will be released...no idea as still working on ESP3D 3.0 / ESP3DLib 3.0 / WebUI 3.0 and not done yet
That said you can use the git version and try
