### ISSUE TITLE
[V3 Test] Configuration Matrix

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#741]
Here my testing configurations matrix for reference, any other hardware feel free to feedback I can add :
I will add features tested after the first test, also I have ordered some ESP32 with ESP01 form factor, I will add them in test list also when received.

Printer Board | Firmware | ESP | Status | Notes 
---|---|---|---|---
BTT SKR PRO V1.2 | Marlin 2.0.9.3 | ESP01<br>ESP32-C3(ESP01 form factor) |![](https://img.shields.io/badge/Ok-green)  | No display
BTT SKR V1.3 | Marlin 2.0.9.3| Panucatt Wifi Backpack | ![](https://img.shields.io/badge/Ok-green) | Display GLCD 128X64
Ramp/Mega | Repetier 1.0.4 |  SD Card Reader/Nodemcu |  ![](https://img.shields.io/badge/Ok-green) | No display
MKS Robin Nano V2.0 | Marlin 2.0.9.3 | ESP12 |  ![](https://img.shields.io/badge/Ok-orange)<br> Limitations due to MKS Marlin code | MKS Serial Protocol <br> Display MKSTS35 V2.0
BTT Octopus 1.1 | Marlin 2.0.9.3 | ESP32Cam | ![](https://img.shields.io/badge/Delay-orange) |
Re-ARM /Ramps | Smoothieware Aug 15, 2021 | Panucatt Wifi Backpack |![](https://img.shields.io/badge/Ok-green) | Viki2 Display<br>Boot delay to 24000 to see the IP<br>No issue when cold start unlike AZMZ
AZSMZ mini 2.1 (2015) | Smoothieware Aug 15, 2021 | ESP01 <br>ESP32-C3(ESP01 form factor) |  ![](https://img.shields.io/badge/Ok-green)  | Set boot delay to 24000 to see the IP<br>Need hard reset when doing cold start
 

TFT are used with Marlin Flashed boards   
TFT| Firmware | ESP | Connected Board | Status | Notes
---|---|---|---|---|---
BTT TFT35-E3 V3 | Vx.x.27 | ESP01 <br>ESP32-C3(ESP01 form factor) | BTT SKR V1.3 | ![](https://img.shields.io/badge/Ok-green) |  Boot delay to 100
BTT TFT70 V3 | Vx.x.27 | ESP01 <br>ESP32-C3(ESP01 form factor) | BTT SKR V1.3 | ![](https://img.shields.io/badge/Ok-green) | Boot delay to 100
MKS TFT35 v1.0| TBD | ESP12 | BTT Octopus 1.1 |![](https://img.shields.io/badge/Delay-orange)  | MKS Serial Protocol  
MKS TFT70 V1.1| V1.0.7 |ESP12 | BTT Octopus 1.1 |  ![](https://img.shields.io/badge/Testing-orange)  tested as standalone until get 24V PS | MKS Serial Protocol

### BTT SKR PRO V1.2 / ESP01 & ESP32-C3
Temperatures | Positions | Terminal | Printer settings | M115 | SD List | Long Name | SD Upload | SD Download | Create Dir | Delete Dir | Delete File | USB List | USB Upload | USB Download
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) <br> if enabled <br>if working  |![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey) |![](https://img.shields.io/badge/NA-grey) | ![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/NA-grey)| ![](https://img.shields.io/badge/NA-grey)| ![](https://img.shields.io/badge/NA-grey)
 
### BTT SKR V1.3 / Panucatt WifiBackPack
Temperatures | Positions | Terminal | Printer settings | M115 | SD List | Long Name |SD Upload | SD Download  | Create Dir | Delete Dir | Delete File  | USB List | USB Upload | USB Download
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) <br> if enabled <br>if working  |![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green) |![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/NA-grey)| ![](https://img.shields.io/badge/NA-grey)| ![](https://img.shields.io/badge/NA-grey)

### MKS Robin Nano V2.0 / ESP12 
Temperatures | Positions | Terminal | Printer settings | M115 | SD List | Long Name |SD Upload | SD Download  | Create Dir | Delete Dir | Delete File  | USB List | USB Upload | USB Download
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
![](https://img.shields.io/badge/Ok-green)<br>custom output|![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/Ok-green)<br>custom output|![](https://img.shields.io/badge/Ok-green)<br>* custom output<br>* subdir are not accessible|![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey)   

### Ramp/Mega / Nodemcu
Temperatures | Positions | Terminal | Printer settings | M115 | SD List | Long Name |SD Upload | SD Download  | Create Dir | Delete Dir | Delete File  | USB List | USB Upload | USB Download
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green)| ![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green) <br>https://github.com/repetier/Repetier-Firmware/pull/1084|![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/Yes-green)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey)

### AZSMZ mini 2.1 (2015) / ESP01 & ESP32-C3
Temperatures | Positions | Terminal | Printer settings | M115 | SD_List | SD_Ext List | Long Name |SD Upload | SD Download  | Create Dir | Delete Dir | Delete File  | USB List | USB Upload | USB Download
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green)| ![](https://img.shields.io/badge/Ok-green)| ![](https://img.shields.io/badge/Ok-green)| ![](https://img.shields.io/badge/Ok-green) <br>no space allowed|![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/Ok-green) <br>only on SD|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey)

### Re-ARM /Ramps  / Panucatt WifiBackPack
Temperatures | Positions | Terminal | Printer settings | M115 | SD_List | SD_Ext List | Long Name |SD Upload | SD Download  | Create Dir | Delete Dir | Delete File  | USB List | USB Upload | USB Download
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green)   |![](https://img.shields.io/badge/Ok-green) <br>no space allowed|![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green) |![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/NA-grey)| ![](https://img.shields.io/badge/NA-grey)| ![](https://img.shields.io/badge/NA-grey)

### MKS TFT70 V1.1 / MKS WiFi 
Temperatures | Positions | Terminal | Printer settings | M115 | SD_List | SD_Ext List | Long Name |SD Upload | SD Download  | Create Dir | Delete Dir | Delete File  | USB List | USB Upload | USB Download
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Testing-orange) | ![](https://img.shields.io/badge/Testing-orange) | ![](https://img.shields.io/badge/Ok-green)<br>custom output | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/NA-grey)   |![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/NA-grey) |![](https://img.shields.io/badge/No-red) | ![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/No-red) | ![](https://img.shields.io/badge/Ok-green)| ![](https://img.shields.io/badge/Ok-green)| ![](https://img.shields.io/badge/NA-grey)

### BTT TFT70 V3 /  ESP01 & ESP32-C3 
Temperatures | Positions | Terminal | Printer settings | M115 | SD_List | SD_Ext List | Long Name |SD Upload | SD Download  | Create Dir | Delete Dir | Delete File  | USB List | USB Upload | USB Download
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/NA-grey)   |![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey) |![](https://img.shields.io/badge/No-red) | ![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green)| ![](https://img.shields.io/badge/NA-grey)| ![](https://img.shields.io/badge/NA-grey)

### BTT TFT35-E3 V3 /  ESP01 & ESP32-C3 
Temperatures | Positions | Terminal | Printer settings | M115 | SD_List | SD_Ext List | Long Name |SD Upload | SD Download  | Create Dir | Delete Dir | Delete File  | USB List | USB Upload | USB Download
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/NA-grey)   |![](https://img.shields.io/badge/Ok-green)|![](https://img.shields.io/badge/NA-grey)|![](https://img.shields.io/badge/NA-grey) |![](https://img.shields.io/badge/No-red) | ![](https://img.shields.io/badge/No-red)|![](https://img.shields.io/badge/Ok-green) | ![](https://img.shields.io/badge/Ok-green)| ![](https://img.shields.io/badge/NA-grey)| ![](https://img.shields.io/badge/NA-grey)

**Comment by luc-github** [comment]
Not just need to test , need also to setup each config - it will be a long week ...

**Comment by luc-github** [comment]
Ok My Azteeg Mini is dead - the SD card reader was unsoldered and I destroy all trying to fix it - too small for my fat toes... 😿 
So I remove it from matrix

**Comment by luc-github** [comment]
I would like to test more repetier e.g V2 but I currently have not supported board in hand: https://github.com/repetier/Repetier-Firmware/tree/dev2

**Comment by luc-github** [comment]
I did not noticed the Cheetah board need a 24V power supply - which I do not have currently - I will go to buy one next week
My MKS TFT32L32 is dead (Murphy Law) - I have ordered an MKS 35 - so test will be updated

**Comment by luc-github** [comment]
For some reason my Cheetah board is actually not functionnal so I need to switch corresponding tests to another one, also I did not put  ESP32-S2 (which is mono core like C3) neither ESP32-S3 (dual core like ESP32), so will add one test for each

**Comment by luc-github** [comment]
I have ordered a MKS 3.5 to replace the damaged 3.2, and a BTT Octopus 1.1 to replace the cheetah that is not working.

I still need to order BTT esp32/esp7 modules for the octopus as I saw the ESP SPI pins are connected to Octopus SPI SD so it may me a good oportunity to add direct sd upload on this board => TBC
I will continue testing after the print status is implemented in refactoring webUI

**Comment by luc-github** [comment]
I have some delay but still doing tests - ESP32Cam is now working again as well as authentication - I am now working on embedded display which also need a refactoring

**Comment by A7F** [comment]
Hi, I managed to install successfully ESP3D on my SKR Mini E3 v1.2 (TMC2209) board by plugging a D1 Mini straight onto the TFT headers. I did not install a TFT touchscreen display anyway, I'm fine with the stock Ender 3 screen, and everything is working perfect: I can provide the wiring diagram if needed, just let me know.

Thank you! :)

**Comment by luc-github** [comment]
@A7F you can do PR with all informations to this file https://github.com/luc-github/ESP3D/blob/2.1.x/wiki/hardware-connection.md
it will update the wiki

**Comment by luc-github** [comment]
May be add this table result to esp3d.io could be a good reference to complete the hardware section

**Comment by luc-github** [comment]
each esp hardware has been added to esp3d.io and almost each printer board are described in how to connect
the board with dedicated connectors will be added later
