### ISSUE TITLE
[FEATURE REQUEST]translate files use spi dma mode

### ISSUE THREAD

**Issue by liqijian101** [luc-github/ESP8266#742]
hi luc , when we translate files use spi, can we use the dma mode.

**Comment by luc-github** [comment]
for what purpose ?
the speed ?
I just use what is available, here something I have found about it:
 https://github.com/greiman/SdFat-beta/issues/30

**Comment by luc-github** [comment]
@liqijian101 any feedback on my question ?

**Comment by liqijian101** [comment]
I read the link you provided to me, and I think the analysis is reasonable. I'll give up using DMA to improve the transmission speed for the time being.
