### ISSUE TITLE
[FEATURE REQUEST] bug template enhancement

### ISSUE THREAD

**Issue by atsju** [luc-github/ESP8266#750]
**Is your feature request related to a problem? Please describe.**
While opening a bug I tried to get requested infos but it has been unclear for me (as a new user) what  was neededd

**Describe the solution you'd like**

this is the bug template
```
**ESP3D Firmware:**
- ESP core version: [2.5.2]
- Version:[e.g 2.1b4]
- Web UI Version:[e.g 2.1b14]  
- Wifi mode:[e.g. STA]  
- Flash method: [Arduino Ide / PlatformIO]
- Any change done in FW
 
 tips: to get ESP3D informations type `[ESP420]plain`    
       to get WebUI version check your menu header    
```

- ~~move tips up as it will be read before the filling~~ done in #751  
- ~~Use the format ([html comment](https://stackoverflow.com/questions/46734820/hidden-markdown-text-on-github)) `<!--Invisible line -->` to show lines during template filling that will not show in rendering~~ done in #751  
- make template items correspond to what `[ESP420]plain` returns

**Describe alternatives you've considered**

**Additional context**

**Comment by luc-github** [comment]
@atsju can this issue be closed as all PR are now merged ?

**Comment by atsju** [comment]
Please could you modify the template as I mentionned in #751 ? I recommend using same wording/order/info in version requested by github as it the one given by serial of ESP (and/or add some comme t like "can be found at top right of web page"). I remember opening my first issue here I was a bit confused. 
I think it could help users but I don't have the knowledge to do it. For you it will be 10 minutes work.

**Comment by luc-github** [comment]
do you mean 
 feature request template using :
 ```
ESP core version: [e.g. 2.5.2]
Version:[e.g. 2.1b4]
Web UI Version:[e.g. 2.1b14]
Wifi mode:[e.g. STA/AP]
Flash method: [Arduino Ide / PlatformIO]
Any change done in FW:
```

**Comment by atsju** [comment]
yes.
I know it might be clear for you (and it becomes each day clearer for me) but as a new user I was very confused.

**Comment by luc-github** [comment]
Feature request is a request of feature, it  is not related to any version / any setting / any code, so all these are not necessary details, what is important is the target of the request - that why these informations you mention are not present in template

**Comment by atsju** [comment]
sorry if I haven't been clear. Could you modify this file :https://github.com/luc-github/ESP3D/blob/2.1.x/.github/ISSUE_TEMPLATE/bug-report---problem.md

it's the bug report file, not the feature request. The information are needed but unclear (for new users)

**Comment by luc-github** [comment]
Hi Sorry what is unclear ?  - it mostly ask for version ... I even give example of version for reference
the only possible issue could be 
`ESP core version: [e.g. 2.5.2]`
because this is for Arduino IDE and infrmation is in Board manager, for platformio if they use the provided env , core version is not necessary if they provide the version of ESP3D FW they are  using
