### ISSUE TITLE
Index.html.gz connection failed

### ISSUE THREAD

**Issue by aacorvalan** [luc-github/ESP8266#758]
Hello, 

**Describe the bug**
in version 3.0 of esp3d when index.html.gz is loaded from https://github.com/luc-github/ESP3D-WEBUI/blob/2.1/languages/es/index.html.gz it indicates connection failed, however in 2.1 it works.

**To Reproduce**
Load index.html.gz

**Expected behavior**
connection failed

**Screenshots**
![Captura de pantalla 2022-05-18 19:49:41](https://user-images.githubusercontent.com/84159494/169169413-4d6b1f9d-bf4f-4705-aa10-bc3069cf2713.png)
![Captura de pantalla 2022-05-18 19:50:12](https://user-images.githubusercontent.com/84159494/169169433-77b73a70-b764-43db-9e39-66610061a305.png)

**Firmware**
ESP3D 3.0 alpha stage

**Software upload**
Visual studio code

**Board used**
MCU:ESP8266 lolin
Flash size: 4m2m

[configuration.h.txt](https://github.com/luc-github/ESP3D/files/8721402/configuration.h.txt)
[platformio.ini.txt](https://github.com/luc-github/ESP3D/files/8721407/platformio.ini.txt)

**Comment by aacorvalan** [comment]
Im edited, thanks

**Comment by luc-github** [comment]
>in version 3.0 of esp3d when index.html.gz is loaded from https://github.com/luc-github/ESP3D-WEBUI/blob/2.1/languages/es/index.html.gz it indicates connection failed,

yes as mentioned in readme :
![image](https://user-images.githubusercontent.com/8822552/169174281-f751ff0d-b8d3-4324-9286-2209668cd9aa.png)

you must use webui 3.0 not 2.1

**Comment by aacorvalan** [comment]
Uploading the version from https://github.com/luc-github/ESP3D-WEBUI/blob/3.0/dist/printer/production/index.html.gz I get...
![Captura de pantalla 2022-05-18 21:30:37](https://user-images.githubusercontent.com/84159494/169177510-a5ac022f-a62e-45a1-aa0d-8378ccde2169.png)

**Comment by luc-github** [comment]
go back to http://192.168.1.111?forcefailsafe=yes and delete `preferences.json` the file is also incompatible - this has been fixed in rewrite that I will merge soon

**Comment by aacorvalan** [comment]
In version 2 preferences.json is created, in version 3 as I did not enter ESP3D it could not be created
![Captura de pantalla 2022-05-18 21:44:12](https://user-images.githubusercontent.com/84159494/169178613-7e2600db-c6ce-4ec9-aa46-576fb2b45b5f.png)

**Comment by luc-github** [comment]
yes it is not an issue, it will be created when you will save it, there is a default one in memory

**Comment by aacorvalan** [comment]
1 I load the index
2 Login to http://192.168.1.111/?forcefailsafe=yes
3 The page can no longer be loaded to remove the index

**Comment by luc-github** [comment]
Sorry I do not understand
why do you try to log to failsafe page once you uploaded index.html.gz?
if you try to go to failsafe page be sure you use proper ip of your device

**Comment by aacorvalan** [comment]
When I upload index I cant reload 192.168.1.111/?forcefailsafe=yes
![Captura de pantalla 2022-05-18 22:22:06](https://user-images.githubusercontent.com/84159494/169182015-29e2c2d2-9cbb-4beb-8229-e2d1df60ae7d.png)
Now I can't go back

**Comment by luc-github** [comment]
Failsafe is part of FW not in index.html.gz you may do a typo when typing or FW is not started
you should be able to access anytime when FW is started 

What do have when loading page ?

**Comment by aacorvalan** [comment]
I don't know why I can no access it, it has already happened to me and I have to reload ESP3d. First I can't load GCO files to my TFT SD, later I found that I can't access that SD. I think that it would solve everything by placing an ESPcam with SD and the ESP3d 2 version

**Comment by aacorvalan** [comment]
With version 3, when I upload index I can't access the firmware in any way

**Comment by luc-github** [comment]
what does it mean : you cannot access ?
what your browser show ? any error ?

**Comment by aacorvalan** [comment]
I can't access, just loading the firmware again. 

"Error (SyntaxError: Unexpected token < in JSON at position 0)

Parsing preferences error, file is incorrect"

**Comment by luc-github** [comment]
I will check later today , if no preferences.json it should not have issue

**Comment by aacorvalan** [comment]
I thank you very much for your time. I will try to load it in ESP32-cam to put the SD, since I cannot access SD tft on my Artillery genius pro

**Comment by luc-github** [comment]
I suspect FS is corrupted , need format

**Comment by aacorvalan** [comment]
The firmware in MCU:ESP8266 lolin
Flash size: 4m2m
[configuration.h.txt](https://github.com/luc-github/ESP3D/files/8722932/configuration.h.txt)
[platformio.ini.txt](https://github.com/luc-github/ESP3D/files/8722933/platformio.ini.txt)

**Comment by luc-github** [comment]
need [ESP710]FORMAT

**Comment by aacorvalan** [comment]
I don't remember if this is from v2 or v3, now i print from pendrive for send command. Now see 2.2.1

{"chip_id":"7724577","cpu":"160","freemem":"35.84 KB","SDK":"2.2.1(cfd48f3)","flash_size":"4.00 MB","update_size":"534.09 KB","spiffs_size":"1.86 MB","baud_rate":"115200","sleep_mode":"Modem","channel":"1","phy_mode":"11n","web_port":"80","data_port":"8888","hostname":"esp3d","active_mode":"STA (80:7D:3A:75:DE:21)","connected_ssid":"Mi router","connected_signal":"100%","ip_mode":"DHCP","ip":"192.168.1.111","gw":"192.168.1.1","msk":"255.255.255.0","dns":"192.168.5.1","disabled_mode":"AP (82:7D:3A:75:DE:21)","captive_portal":"Enabled","ssdp":"Enabled","netbios":"Disabled","mdns":"Enabled","web_update":"Enabled","pin recovery":"Disabled","autentication":"Disabled","target_fw":"Marlin","M117_output":"Enabled","Notifications":"Disabled","Serial_output":"Enabled","Websocket_output":"Enabled","TCP_output":"Enabled","fw":"2.1.2 ESP8266/8586"}

**Comment by aacorvalan** [comment]
In esp32-cam it works, I don't know why in nodemcu it doesn't. Does not read the sd in slot esp32cam, format in FAT32 4Gb and other 16Gb
![a](https://user-images.githubusercontent.com/84159494/169202025-aa01a906-2eab-4555-93be-58e125c551af.png)

**Comment by luc-github** [comment]
did you configure the FW to support SD card of the ESp32cam ? - it is an SDIO card
But what do you want to do with this SD card ?
Esp32cam SD card cannot be seen by printer, so any file uploaded on it, won't be accessible for Printer

About esp8266 I suspect a FS corruption and you need to erase whole card or use the terminal and type [ESP710]FORMAT and restart bord when format is done

**Comment by aacorvalan** [comment]
I need to load GCO file and print from ESP3d to not use pendrive or SD in TFT, also resume printing due to lack of electricity. In SDIO not upload files

**Comment by aacorvalan** [comment]
Is it possible to load Gco or Gcode to Esp-cam memory and print from Esp3d?

**Comment by luc-github** [comment]
ESP3D does not stream GCODE file yet

**Comment by luc-github** [comment]
I close issue as invalid
