### ISSUE TITLE
[Question]How to power the board using USB adapter

### ISSUE THREAD

**Issue by griffinmt** [luc-github/ESP8266#759]
I have my esp-01s loaded with ESP3D and I can connect to it while plugged into USB programming adapter. But I need to connect it to my Ender 3 Pro using a 4.2.7 board and that will be via its USB micro port. But then the esp-01s gets no power. How do I supply the 5 volts needed while letting the data pass across in a serial mode?

**Comment by luc-github** [comment]
did you read the wiki ? the board is same as this one no ?  https://github.com/luc-github/ESP3D/wiki/Creality-CR-10-Ender-3
