### ISSUE TITLE
Won't detect SD card

### ISSUE THREAD

**Issue by jwinfieldnz** [luc-github/ESP8266#807]
SD card is not detected

The ESP32CAM SD card doesn't seem to be detected too often. I have used a few cards from 8 to 32GB FAT and exFAT format but doesn't seem to detect the card at all. Maybe I have the SD card settings wrong, It does work on some occasions. 

Arduino debug provides 
```
E (84334) sdmmc_sd: sdmmc_check_scr: send_scr returned 0xffffffff
E (84334) vfs_fat_sdmmc: sdmmc_card_init failed (0xffffffff).
M21
```
Maybe a faulty card reader?

![image](https://user-images.githubusercontent.com/110659176/188230966-a634c81b-78cb-4ad4-97b7-b89a98c5f835.png)

![image](https://user-images.githubusercontent.com/110659176/188230991-35f40c91-1626-410f-98e4-ca407a4f4010.png)

-Marlin
- MCU: ESP32CAM

**Comment by luc-github** [comment]
yes looks hardware/driver issue, 
can you share your configuration.h
Did you do any change in FW? 
what version of esp32 core do you use in arduino?

**Comment by jwinfieldnz** [comment]
Sorry. You can close this. I just tried a camera sketch and fails with that also.

**Comment by luc-github** [comment]
yes looks hardware/driver issue, 
can you share your cofiguration.h
Did you do any change in FW? 
what version of esp32 core do you use in arduino?

**Comment by luc-github** [comment]
try older core/ latest esp32 core git., there was some issue with sdmmc driver on some version

**Comment by liqijian101** [comment]
My esp32s3 has the same problem. Some cards can not be detected, and another 16g card is identified as 2G.

Can you recommend a suitable version

**Comment by luc-github** [comment]
normaly latest git should be ok as well as 2.0.4 as well as version  currently used in esp3d V3 platformio

be sure also your card is formated using https://www.sdcard.org/downloads/formatter/

on my esp32cam the 16GB is well detected :
![image](https://user-images.githubusercontent.com/8822552/188270297-843478ea-87d8-40e4-9459-795b5525ae00.png)

**Comment by luc-github** [comment]
I close issue then
