### ISSUE TITLE
[FEATURE REQUEST]<Add pin setting function in sdio mode >

### ISSUE THREAD

**Issue by liqijian101** [luc-github/ESP8266#808]
hi luc 
I suggest to add sdio pin resetting function  to esp usb_sdio.c file.
 examples, SDMMC.setPins(int clk, int cmd, int d0, int d1, int d2, int d3);

**Comment by luc-github** [comment]
why?  can you elaborate ?

**Comment by liqijian101** [comment]
ESP32 can connect the SDIO function to any pin, but the ESP3d program has no code to set the pin.

**Comment by luc-github** [comment]
I see - will add it , thank you for the suggestion

**Comment by luc-github** [comment]
Fixed - configurator has also been updated
![image](https://user-images.githubusercontent.com/8822552/188771985-e953fc5f-28c2-4b23-801f-738fab1943d2.png)
