### ISSUE TITLE
new adapter compatible with esp8266 web server

### ISSUE THREAD

**Issue by c128** [luc-github/ESP8266#81]
i make adapter for ramps-fd with esp8266 
you can check this link
https://youtu.be/O2B4Pwn_iRE
https://workspace.circuitmaker.com/Projects/01636514-CB2E-4307-A534-94C8A66E75D4
http://forums.reprap.org/read.php?359,613142,623110#msg-623110

for non commercial use you can make and test

**Comment by luc-github** [comment]
Thanks for sharing
