### ISSUE TITLE
[FEATURE REQUEST] Print progress status

### ISSUE THREAD

**Issue by Caian** [luc-github/ESP8266#820]
**Is your feature request related to a problem? Please describe.**

To check the printing progress it is necessary to click the progress button on the SD pane, wait for the M27 response and manually calculate a percentage from the byte numbers returned in the response.

**Describe the solution you'd like**

A periodical update of the progress (maybe with `M27 SXX`?) with an automatically calculated percentage or a progress bar. It would be nice as well to have an elapsed time counter and an estimation of the time left.

**Describe alternatives you've considered**

A sufficient approach would be to just parse the M27 response on the command log and print a percentage along with it. I believe it would be a front-end-only modification.

**Additional context**

None

**Comment by luc-github** [comment]
What version are you  using ?
It is already implemented in V3: https://github.com/luc-github/ESP3D-WEBUI/issues/239

**Comment by Caian** [comment]
I'm using ESP3DLib 1.0.11 as part of the firmware bundle that is shipped with MKS TinyBee, including the gz for the index page. Can I just upload a newer interface?

**Comment by luc-github** [comment]
No to use ESP3D-WebUI  3.0 : https://github.com/luc-github/ESP3D-WEBUI/tree/3.0
you need to use ESP3DLib V3 https://github.com/luc-github/ESP3DLib/tree/3.0, which only available in this version of Marlin as still in devt : https://github.com/luc-github/Marlin/tree/ESP3D-V3-2.1.x

**Comment by Caian** [comment]
Could you backport at least some form of percentage string to the 2x branch?

**Comment by luc-github** [comment]
no plan so far , I am already busy with v3 
there are old pr for progression but they were not integrated because they only worked on Marlin and UI was broken on some configuration

why not try the V3 ?

**Comment by Caian** [comment]
I'll see if I can get the latest development branch to compile for the MKS TinyBee so I can test V3...

**Comment by luc-github** [comment]
use the Marlin link I gave above - it is already setup for tinybee
