### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mkeyno** [luc-github/ESP8266#83]
hi @luc-github , thanks for sharing the code , I put your codes in Arduino 1.6.7  and face the following error , also why do you use ptl format instead the html,  
br

`
sketch\wifi.cpp: In member function 'bool WIFI_CONFIG::Setup()':

wifi.cpp:161: error: 'sleep_type' was not declared in this scope

     wifi_set_sleep_type ((sleep_type)bflag);

                           ^

wifi.cpp:181: error: 'phy_mode' was not declared in this scope

         wifi_set_phy_mode((phy_mode)bflag);

                            ^

wifi.cpp:217: error: 'phy_mode' was not declared in this scope

         wifi_set_phy_mode((phy_mode)bflag);

                            ^

exit status 1
'sleep_type' was not declared in this scope

`

**Comment by luc-github** [comment]
there are several difference between ESP core 2.0.0 and 2.1.0
master is for 2.1.0 when 0.5.1 is for 2.0.0
It is mentioned in readme
```
Development version:
Arduino ide 1.6.5 with stable 2.1.0 from ESP8266 : Build Status
Stable version:
Arduino ide 1.6.5 with stable 2.0.0 from ESP8266, please use https://github.com/luc-github/ESP8266/releases/tag/v0.5.1
```

I use .tpl extension for dynamic content (referring to template) check keywords in https://github.com/luc-github/ESP8266/blob/master/keywords.txt
This is just a personal choice, html files and others files with static content are also supported

**Comment by mkeyno** [comment]
thanks @luc-github for quick reply , I have same problem with 1.64 & 1.67 with last stable version , do you have plan to update for new version , also why don't make it as arduino library so we could extend its examples , your code as standalone example is very complicated for novice user like me 
by the way  have you check the new [Markus code on serial bridge ](https://github.com/Links2004/arduinoWebSockets/issues/61#issuecomment-198110316)
I really appreciated to have your comments 
BR

**Comment by luc-github** [comment]
you are using latest ESP core = 2.1.0 you must use the master of my git - this is not what you are doing , you use older version - this has been fixed https://github.com/luc-github/ESP8266/commit/9885d2cab944d876b3823130caf1f3ebc92eede3

you must sync your repository to get latest code

**Comment by mkeyno** [comment]
hi @luc-github ,I've upload the new master code when I upload the code and data file on my nodemcu , nothings happened , any sign of station or AP mode , also the serial output is like stock in boot mode

**Comment by luc-github** [comment]
did you uploaded the data directory ?

**Comment by mkeyno** [comment]
yes I did buddy

**Comment by luc-github** [comment]
what serial output show ? default is 9600 bauds

**Comment by luc-github** [comment]
you can discuss with module using serial also 
like typing : [ESP444]CONFIG

**Comment by mkeyno** [comment]
I put some Serial.print in the setup function , but nothings come out

**Comment by luc-github** [comment]
when connect Nodemcu nothing show ? even garbage ?

**Comment by mkeyno** [comment]
little garbage such as when it goes to boot mode , How ever I compiled the code with arduino 1.64 and many compile error come out , but with 1.6.7 no error

**Comment by luc-github** [comment]
Normally with nodemcu when you connect:
1: some garbage coming from nodemcu device
2: during 10s nothing display it is period to allow hard reset
3: IP
![image](https://cloud.githubusercontent.com/assets/8822552/13889835/f183da38-ed48-11e5-9ec0-02284705d36f.png)

**Comment by luc-github** [comment]
here clean start then type [ESP444]CONFIG on my node mcu

![image](https://cloud.githubusercontent.com/assets/8822552/13889905/3f982c6a-ed49-11e5-91c2-cfa178b379be.png)

**Comment by luc-github** [comment]
additionally - I only use 1.6.5 ide so not sure the behaviour with 1.6.7

**Comment by mkeyno** [comment]
![new bitmap image](https://cloud.githubusercontent.com/assets/6232001/13890065/c440e10e-ed5e-11e5-82ca-3da44f264281.jpg)

**Comment by mkeyno** [comment]
nothing else

**Comment by luc-github** [comment]
add return carriage to be able to key commands in serial monitor, need \n

**Comment by mkeyno** [comment]
now its works , tnx buddy for your patient and time but when I connected to AP and browse to 192.168.0.1  nothings happened and downloaded
![new bitmap ifmage](https://cloud.githubusercontent.com/assets/6232001/13890287/df0823c0-ed5f-11e5-9ddc-908518d793be.jpg)

**Comment by luc-github** [comment]
do not forget to close issue if ok - thanks

**Comment by mkeyno** [comment]
sure , but still no web loaded on any 80 or 8888 port ,   don't you think it would be better if use the SPIFF Dir to check the files or any of feature such as Server.OnfileUpload to update the file

**Comment by luc-github** [comment]
I can reproduce the issue - I was in station mode before 
seems new issue due to 2.1.0 as it was ok with 2.0.0 - will check

**Comment by mkeyno** [comment]
thanks any way Luc , I'll be following you

**Comment by luc-github** [comment]
I create issue https://github.com/luc-github/ESP8266/issues/85
seems problem with captive portal -
