### ISSUE TITLE
[FEATURE REQUEST]🦄WhatsApp Notification

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#888]
How to do is here https://www.callmebot.com/blog/free-api-whatsapp-messages/ - it is free and it use same way as others - so it is easy to implement

**Comment by kleffa** [comment]
I started to read the api, and found this...
https://github.com/hafidhh/Callmebot-ESP32

**Comment by luc-github** [comment]
Close issue as implemented - esp3d.io is also updated for ESP3D
