### ISSUE TITLE
[Question]<ESP3D comuncation with Klipper>

### ISSUE THREAD

**Issue by Ultor3D** [luc-github/ESP8266#889]
Hello, I am using klipper FW on some of my machines using RPI4 and USB to control all the machines. The problem is that we are limited with the number of USB Ports of the Raspberry. Now I am trying to implent a wirless communication betwen klipper and The raspebrry PI usinfg and ESP32 directly connected to the printer Board. To resume: 

- The printer connects to ---> ESP32 Board ----> RPI4 (Moonracker) ----> Mainsail

Can we use ESP3D in this case?
Does ESP3D supports Klipper FW ?

**Comment by luc-github** [comment]
ESP3D cannot replace a Raspberry PI sorry - so klipper is not supported by ESP3D

**Comment by Ultor3D** [comment]
Thank you for your answer but I am not looking for replacing a raspberry pi with ESP3D, But how can both comunicates together. 
By for example sending Serial threw WIFI (ESP3D) Tocontroll klipper. ESP3D and RPI will work togerther and we can consider the RPI as master or Edge and the ESP32 Board  with ESP3D as Slave

**Comment by luc-github** [comment]
looking at GCODE supported : https://mmone.github.io/klipper/G-Codes.html seems close to Marlin so it may work 
if you can connect esp board to raspberry by serial and  klipper can catch the command by serial - it may work  - but as I do not have any klipper system I cannot say sorry
Additionnally I do not know how to transfert any file to klipper / raspberry
