### ISSUE TITLE
Kingroon kp3s no work

### ISSUE THREAD

**Issue by pafftis** [luc-github/ESP8266#892]
There is a King room kp3s printer. Compiled the firmware file for esp3d, uploaded it to Webos D1min, and also installed the Web interface. I found the TX and RX pins on the board of my printer. Connected them to the printer tx to rx, rx to tx. The wimax d1 mini module has started, but does not show any statuses.

https://ibb.co/P1DjsFT
https://ibb.co/8PwNBdr

I tried two different places with rx and tx prints on my board from the printer. Then there was nowhere and nothing appeared.

**Comment by luc-github** [comment]
how do you power the esp board ?

**Comment by pafftis** [comment]
> 

5v -> 5v motherboard
Gnd -> gnd motherboard

Wemos d1 min
Marlin 2.1
Esp3d 2.1

**Comment by luc-github** [comment]
I see you do not use RX/TX but RX2/TX2 did you enabled this port on Marlin ?

Be also sure this port baud rate is same as ESP serial baud rate

**Comment by pafftis** [comment]
> 

I soldered to tx and rx, the one that comes from usb. And where in the settings should I enable this port?

**Comment by pafftis** [comment]
Port rate 25000

**Comment by luc-github** [comment]
>I soldered to tx and rx, the one that comes from usb. And where in the settings should I enable this port?

This one is the default one - if your board worked with usb already no need to enable new port in Marlin

>Port rate 25000

I guess you mean 250000,  be sure ESP3D  baud rate is also 250000

As you use RX/TX from USB be sure nothing is connected to USB

try to type `M115` in WebUI terminal  to see if any output

**Comment by pafftis** [comment]
My board uses marlin. The USB port is completely free. The sd card is also removed. There is no information about the status of my printer in the web interface.

**Comment by luc-github** [comment]
I suggest you to test your serial connection with USB/Serial adapter to verify serial is working on your wires and you also can test your wemos mini

**Comment by pafftis** [comment]
I connected my laptop with a printer management program to usb and it was determined and worked well. If I also connect my wemos d1 mini to the printer with a usb wire, should the op also work?

**Comment by luc-github** [comment]
I am talking about to the Rx and Tx  wires you soldered not usb connector.
you must test they are working using a serial/usb adapter and check them in same way you tested USB port

In same idea you can also test the wemos mini rx/tx pins using serial usb adapter to check they are ok

**Comment by luc-github** [comment]
can you also share the output of `[ESP420]` command in webui terminal ?

**Comment by pafftis** [comment]
![Screenshot_20230224_194138_com yandex browser](https://user-images.githubusercontent.com/68192908/221236535-dbe4906c-e5b1-4ba3-becf-bed8f6e613a8.jpg)
I checked the tx and rx on the wemos d1 mini, they are working. Those wires that I soldered checked with a tester, they are called. It is learned that wemos 100% has all contacts with the board from the printer.

**Comment by pafftis** [comment]
I also tried to connect my printer to the computer via usb. The computer successfully detects the printer and lets you control it.

**Comment by luc-github** [comment]
How did you tested your wires do proper rx/tx communication?

**Comment by pafftis** [comment]
I just rang them to exclude the moment that there is some kind of wire break or bad contact. Unfortunately, I have nothing else to check. Before that, the person who installed klipper on his printer told me that it was tx and rx. I do not know how I can find out where my printer's rx and tx boards are

**Comment by pafftis** [comment]
I don't know then how else to find the tx and rx ports on the board. Author, thank you very much for the application. Maybe you will add printers to the wiki that are already working for sure and that people know exactly which tx and rx ports are working. In my printer, I'm no longer sure what exactly these ports are. And I do not know how to find it.

**Comment by luc-github** [comment]
as I wrote you before you should use usb serial adapter to test your rx/tx are correct/working
like https://shopee.tw/product/10647501/76192284/promotion/card?subtype=big_card_a&gclid=Cj0KCQiA3eGfBhCeARIsACpJNU9UfYjeEyJuO5VO9IZZ8ElfRyXPeyzRdHnliGB4d-NNNsY8dH4Mn20aAsTdEALw_wcB
