### ISSUE TITLE
Error: 'struct camera_config_t' has no member named 'pin_sccb_sda'

### ISSUE THREAD

**Issue by 3D-Darryl** [luc-github/ESP8266#895]
When compiling 3.0 with Ai Thinker camera,  the above error pops up for pin_sccb_sda and pin_sccb_scl.  Both errors go away if the suggested fix  is done in camera.cpp  i.e. pin_sccb_sda -> pin_sscb_sda  and pin_sccb_sc -> pin_sscb_scl.
Not sure if this is correct fix as camera only acquires an image on powerup and never again.

**Comment by luc-github** [comment]
What esp32 core version are you using ? this is due to change in latest core update that is not yet supported in esp3d
http://esp3d.io/esp3d/v3.x/installation/arduino/index.html


About single image capture, yes this is normal if you do not set a refresh :
http://esp3d.io/esp3d-webui/v3.x/documentation/camera/index.html

**Comment by 3D-Darryl** [comment]
I do not know how to find a code revision, but I downloaded it on 26-Feb.  The only commits I saw had to do with documentation.
I Tried a refresh of 100mS and 500mS, but never had any updates.

**Comment by luc-github** [comment]
You use arduino check board manager and check the esp32 board

**Comment by 3D-Darryl** [comment]
The board is Ai-Thinker ESP32-CAM, what you meant by "core"?

**Comment by luc-github** [comment]
https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-board-manager

**Comment by 3D-Darryl** [comment]
Thank you for your patience.  ESP32 Arduino 2.0.3 is installed

**Comment by luc-github** [comment]
should be 2.0.6
Ide 2.X
![image](https://user-images.githubusercontent.com/8822552/222024848-de904b37-e6c7-48b2-ad23-4d2c2fb793cf.png)

Ide 1.8.X
![image](https://user-images.githubusercontent.com/8822552/222025140-7b79a808-d7ad-4811-98dd-1a21a94b8147.png)

**Comment by luc-github** [comment]
any update ?

**Comment by 3D-Darryl** [comment]
I want to thank you for your interest and support.  I struggled for 3 weeks
to get the esp8266  working, where my hope was to add a serial camera (but
there is probably not enough IO).  Then I found the ESP32 with a camera and
the promise of software to support it, but after struggling with that for 2
1/2 weeks i am left with an Arduino IDE that has become recalcitrant.  You
had suggested that allowing the update was my error, but I can't guarantee
that the Arduino or its libraries will never be updated, and in fact will
need updates for future projects.  So I cannot compile the camera code and
am left with no way forward.
[image: image.png]
I decided to stop banging my head against the wall and I put the project
aside to move to something more fruitful and less frustrating.  I plan to
have another look at it in April by which time perhaps wiser heads will
have found a solution.
Thank you again for your support.

**Comment by luc-github** [comment]
I suggest you to use platformio instead of arduino ide - you won't have to handle anything because I already did :
http://esp3d.io/esp3d/v3.x/installation/index.html#setup-your-development-environment

**Comment by luc-github** [comment]
I close issue then

**Comment by 3D-Darryl** [comment]
Luc,
    Platform IO has even more issues.  It no longer builds the Nordic
examples that worked last week, and it won't build the Marlin code anymore
because of (apparently) an issue with the crypto code.  I have not found a
solution there either.  But it never built the ESP32 code.
Darryl

**Comment by luc-github** [comment]
well issue is your side yesterday the build was passing using arduino and platformio
https://github.com/luc-github/ESP3D/actions/workflows/build-ci.yml

**Comment by 3D-Darryl** [comment]
OK, thanks.

**Comment by luc-github** [comment]
the auto build do fresh setup for each build so you may have a look to see what it is doing compare to your setup
https://github.com/luc-github/ESP3D/blob/3.0/.github/workflows/build-ci.yml

https://github.com/luc-github/ESP3D/tree/3.0/.github/ci
