### ISSUE TITLE
ESP32 LoRa Heltec v2 with display oled 128x64- Display not working display

### ISSUE THREAD

**Issue by PatricLeal** [luc-github/ESP8266#897]
When trying to upload ESP3D to the Heltec Lora board, everything works perfectly, but the OLED display does not show any visual information.

As I tried to force declaration of pins in configuration.h but I was not successful in displaying the screen.

Configuration.h file section:
/***************************************************
*
* display settings
*
* rendering screens
*
************************************/

// printer screen
// Your printer has a display
#define PRINTER_HAS_DISPLAY

// ESP3D screen
// OLED I2C SSD1306 128X64
// Screen connected to ESP board
#define DISPLAY_DEVICE OLED_I2C_SSD1306_128X64

// Display i2C address
// Wire address of display
#define DISPLAY_I2C_ADDR 0x3c
#define ESP_SDA_PIN 0
#define ESP_SCL_PIN 15
#define ESP_RST_PIN 16
/***************************************************
*
* Levels of security
*
* How commands are allowed to be sent to ESP3D
*
************************************/

// Enable serial commands
// Allow commands to be sent to ESP3D via serial port
#define SERIAL_COMMAND_FEATURE
-------------
plataformio.ini file:

[platform]
src_dir = esp3d
build_dir = .pioenvs
lib_dir = libraries
libdeps_dir = .piolibdeps
data_dir = esp3d/data
default_envs = esp32_8MB_disp_wifi

[env:esp32_8MB_disp_wifi]
platform = espressif32@6.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_echo = yes
monitor_filters = send_on_enter, colorize, esp32_exception_decoder
; set frequency to 240MHz
;board_build.f_cpu = 240000000L
; set frequency to 80MHz
;board_build.f_flash = 80000000L
;board_build.flash_mode = qio
upload_speed = 460800
extra_scripts = pre:platformIO/extra_script.py
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_flags = -DCORE_DEBUG_LEVEL=0

![WIFI_LoRa_32_V2-Heltec-pinout-diagram-scaled](https://user-images.githubusercontent.com/26906375/222221212-67b21c0d-eba4-499a-b71d-5bba6e5ad814.jpg)
![esp32-heltec-schematic-diagram](https://user-images.githubusercontent.com/26906375/222221241-4cb2a9c1-2402-4b93-8118-7edbba204317.png)
[WiFi Lora32Manual.pdf](https://github.com/luc-github/ESP3D/files/10863967/WiFi.Lora32Manual.pdf)

*** In test applications the display of esp32 lora wifi works normally using SSD1306 by Heltec-Aaron-Lee library for display.

**Comment by luc-github** [comment]
What Firmware version are you using ?

This board need a special setup on pin 16  to reset screen at start if I remember well

the oled pins should be in ESP3D V3:
```
/* ESP3D screen
* Screen connected to ESP board
* OLED I2C SSD1306 128X64
* OLED_I2C_SSDSH1106_132X64
* TFT_SPI_ST7789_240X240
* TFT_SPI_ST7789_135X240
*/
#define DISPLAY_DEVICE OLED_I2C_SSD1306_128X64

/* Flip screen
* Flip/rotate screen
*/
//#define DISPLAY_FLIP_VERTICALY

/* Display i2C address
* Wire address of display
*/
#define DISPLAY_I2C_ADDR 0x3c

/* Display reset pin
* The pin used to reset the screen (optional)
*/
#define DISPLAY_I2C_PIN_RST 16

#define ESP_SDA_PIN 4
#define ESP_SCL_PIN 15
```
There is typo in your reset pin definition, should be `DISPLAY_I2C_PIN_RST `  not <s>ESP_RST_PIN </s>and pins are incorrect

**Comment by luc-github** [comment]
did it fixed your issue? it works on my board

**Comment by luc-github** [comment]
I close issue if no feedback
