### ISSUE TITLE
After upload - instructions

### ISSUE THREAD

**Issue by openhardwarecoza** [luc-github/ESP8266#90]
Hi

I am using an ESP07  - just bench testing 

: Set to 1MB flash, 512K SPIFS
: Uploaded the .ino
: Uploaded the SPIFS

Restarted with GPIO0 in RUN mode

Nothing popping up in serial monitor, not any AP to connect to?

**Comment by luc-github** [comment]
Are you sure your ESP 07 has 1M flash ?
What is your IDE version / ESP Core version / Operating System ?
default baud rate is 9600 and need 10 s before it display ```M117 192.168.0.1```
Set your terminal to CR+LF and type 10 sec after starting
```
[ESP444]CONFIG
```
If flash is ok it should display EEPROM config

**Comment by openhardwarecoza** [comment]
Spot on!
Sorry!   It only has 512K - not 1M as advertised (thanks china lol)

**Comment by luc-github** [comment]
Well for 512K current FW won't fit - you need to use the limited one which do not support latest core
I dropped the support as ESP01 has now 1M flash

**Comment by openhardwarecoza** [comment]
I set it to 1M/128 SPIFS:

Uploaded without issue and up and running 

![screenshot_2016-05-10-11-44-46](https://cloud.githubusercontent.com/assets/7695323/15142330/d4b389d2-16a4-11e6-863a-3f84b5b8ccf4.png)

Havent done any more testing.  But noted will order some 1M ESPs then (:

**Comment by luc-github** [comment]
good then - Web FW update should work with 1M/128K but not with 1M/256k
I suggest you to check 12E or 12F models they usually have 4M flash and almost same price as ESP01 - and they are more confortable for working with

**Comment by luc-github** [comment]
Do not forget to flash with mcu at 160Mhz to speed up ui reaction

**Comment by openhardwarecoza** [comment]
Thanks.  I'll contibute a few Wiki pages to the project (:

I still have 60+ ESP07s here so glad it sort of works. 

Last question: Whats the admin user's default password?

**Comment by openhardwarecoza** [comment]
Yes i am on 160mhz

**Comment by luc-github** [comment]
admin / admin -  yes saw it so removed my comment :smile:

**Comment by openhardwarecoza** [comment]
(: Sorry the email notification came through still (:

Pretty responsive I must say.  Now to get back home and hook it to a printer

**Comment by luc-github** [comment]
Thanks a lot for your feedback - appreciate - I am not good in wiki :blush:

**Comment by openhardwarecoza** [comment]
First two wiki entries up for your review:

https://github.com/luc-github/ESP8266/wiki/Flash-Size

https://github.com/luc-github/ESP8266/wiki/Install-Instructions

**Comment by luc-github** [comment]
Wow nice - thanks a lot -I noticed list was not displaying properly so I corrected it,  markdown is sometimes painful with line feed - need to add 3 spaces at the end of the line to get proper return carriage

Thanks a lot
