### ISSUE TITLE
Problem with print 

### ISSUE THREAD

**Issue by radsonpatrick** [luc-github/ESP8266#900]
i'm have problem with start print using esp sd_card : 
![image](https://user-images.githubusercontent.com/43654273/222781573-ac79109a-cff5-45cf-836c-f06a5c7e446c.png)
![image](https://user-images.githubusercontent.com/43654273/222781607-4311a2c7-c970-496e-aa83-042ad1d974d7.png)
but print with sdcard(inside printer) is normal.

this is  output [ESP800] command :

[ESP800]
FW version:3.0.0.a221
FW target:marlin
FW ID:20
Setup:Enabled
SD connection:direct
Serial protocol:Raw
Authentication:Disabled
Web Communication:Synchronous
Web Socket IP:192.168.0.13
Web Socket Port:81
Hostname:esp3d
WiFi mode:STA
Web update:Enabled
Flash File System:LittleFS
Host Path:/
Time:none

**Comment by luc-github** [comment]
printer does not have access to your esp sd card so print command M23/M24 cannot  work , this is normal.
