### ISSUE TITLE
Implement more than 1 temperature/humidity sensor

### ISSUE THREAD

**Issue by Stephano2000** [luc-github/ESP8266#902]
Currently ESP3D provides for the setup of 1  temperature/humidity sensor. It would be great if one is able to setup more than 1 sensor, be it for temperature/humidity or other.

One practical application is having a load cell (weight sensor) to weigh the filament spool while it's being dehumidified or to check moisture absorption.

**Comment by luc-github** [comment]
Current arch design does not support  multiple sensors, a new logic should be implemented for setup, for data transmission in ESP3D and it would need also a new logic for webui display - nothing is really hard to do but need time and test and I do not have bandwidth for this currently - unlike someone else work on it and do a PR, it will take time before it is implemented
