### ISSUE TITLE
[FEATURE REQUEST]<The display adds more information>

### ISSUE THREAD

**Issue by liqijian101** [luc-github/ESP8266#903]
The display screen adds more display information, such as temperature

**Comment by luc-github** [comment]
ESP3D is not a standalone solution - ESP3D does not send any GCODE by it self to refresh screen, it does not interprete any GCODE response neither , display information is not the issue, displaying information that ESP3D does not have, that is the main topic of such request.

This FR is already part of https://github.com/luc-github/ESP3D-TFT ongoing project but won't be in ESP3D anytime soon
