### ISSUE TITLE
[BUG] Can't get ESP8266 to connect to printer

### ISSUE THREAD

**Issue by mikedattolo** [luc-github/ESP8266#906]
I am using  a BTT octopus board and a 2a54n - ESP8266 made by Hiletgo that claims to use a baud rate of 9600 and using esp3d flashed to the esp8226 I can connect using the access point but can get the ESP to pull up my printers config whatsoever, I have made sure in marlin with my btt octopus that I have the serial port activated yet can't get it to work

**Comment by luc-github** [comment]
please give informations as requested in template
