### ISSUE TITLE
[BUG]<ESP_ TIMEZONE cannot be set to a negative number >

### ISSUE THREAD

**Issue by liqijian101** [luc-github/ESP8266#912]
**ESP3D Firmware:**

- ESP3D FW version: 3.0.0.a222
- ESP3D-WebUI Version:3.0.0.a32.M2.1
- Wifi mode:STA
- Flash method:  PlatformIO

- MCU: ESP32C3
- Flash size: 4M

**Additional context**

ESP_ TIMEZONE cannot be set to a negative number

**Comment by luc-github** [comment]
Fixed - thank you for raising it
