### ISSUE TITLE
[BUG]<Build ESP32-C3 Project shows 'Serial2' was not declared in this scope>

### ISSUE THREAD

**Issue by tongsuh** [luc-github/ESP8266#915]
**Describe the bug**
i am new to ESP3D, and i downloaded the ESP3D-3.00-alpha3 RELEASE , using PlatformIO to build  ESP32-C3 Project Task.

TERMINAL shows :
esp3d/src/modules/serial/serial_service.cpp:41:59: error: 'Serial2' was not declared in this scope

ask for help, thanks a lot :)

PS: i didn't change any code. 

**To Reproduce**

1. Open 'VScode'->Open 'PlatformIO'->Open 'ESP3D-3.0.0-alpha3' folder->Open 'PROJECT TASKS'
4. Click on 'esp32-c3'->Click on 'General'->Click on 'build'
5. See error on TERMINAL 

**Expected behavior**

build SUCCESS

**Screenshots**

![image](https://user-images.githubusercontent.com/45163974/232206485-a3bea680-4dcf-4a61-b727-0460b1ed021c.png)

**ESP3D Firmware:**

- ESP3D FW version: 3.0.0-alpha3
- Flash method: PlatformIO
- Any change done in FW: changed NOTHING

**Comment by luc-github** [comment]
please use latest git , not prerelease package,  this issue has already been fixed in it : https://github.com/luc-github/ESP3D/pull/825

**Comment by tongsuh** [comment]
> please use latest git , not prerelease package, this issue has already been fixed in it : #825

thankyou , i'll have a try

**Comment by tongsuh** [comment]
appreciate for your help, my problem fixed ,and also for those who download Releases , you can change the MAX_SERIAL value to 2 ,and delete '&Serial2' in serial_service.cpp
![image](https://user-images.githubusercontent.com/45163974/232284982-62cab3a3-4bcd-4715-bf48-c1b7bb462e94.png)
