### ISSUE TITLE
[BUG] Not all services are announced with Zeroconf

### ISSUE THREAD

**Issue by probonopd** [luc-github/ESP8266#919]
**Describe the bug**

Zeroconf does not announce the printer as `_http._tcp`, only `_esp3d._tcp` (what software uses that, actually?) and `_arduino._tcp` (for OTA). As a result, I cannot open the web interface from the browser using Zeroconf. 

Also, `_ftp._tcp` is not advertised. As a result, I cannot access FTP via Zeroconf. 

Also, all other services are not advertised.

Why?

**To Reproduce**

1. Enable Zeroconf
2. On a computer, run a Zeroconf browser, e.g., `avahi-browse -a -r`. You should see `_http._tcp` and one entry per service (e.g., FTP,...) but they are missing

**Expected behavior**

HTTP and all services are advertised with Zeroconf so that Zeroconf-enabled applications can find them.

**ESP3D Firmware:**

3.0.0

**Board used (please complete the following information):**

ESP32-CAM

**Comment by luc-github** [comment]
>_esp3d._tcp (what software uses that, actually?)

ESP3D it self :
Get available ESP3D list
output is JSON or plain text according parameter
`[ESP450]json=<no> <pwd=admin/user>`

**Comment by luc-github** [comment]
about list of services, I did not implemented that yet - it is in todo list

To see OTA (_arduino._tcp) you need to enable it : https://github.com/luc-github/ESP3D/blob/3.0/esp3d/configuration.h#L376-L379
and you will see it: 
![image](https://user-images.githubusercontent.com/8822552/232662200-bb582991-ac8b-4cb6-bbe3-ff50a281625a.png)

**Comment by luc-github** [comment]
http/ftp/telnet/webdav/websocket service declarations in mdns service added in a225

**Comment by probonopd** [comment]
Thank you very much @luc-github. Appreciate it. :+1:
