### ISSUE TITLE
[FEATURE REQUEST] ESP32 built-in temperature sensor support

### ISSUE THREAD

**Issue by ansonl** [luc-github/ESP8266#921]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Ability to use ESP32 built in temperature sensor as one of the temperature sources. It would be helpful for getting an approximation of controller board temperature to dynamically turn on controller board cooling fans. 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/temp_sensor.html

**Describe alternatives you've considered**

I could wire and mount separate temperature sensor for the controller board and read from it in controller board firmware. It would be helpful to use the built in capability of ESP32 if it already exists. 

**Additional context**

**Comment by luc-github** [comment]
this sensor is already used and temperature is displayed in information page 
![image](https://user-images.githubusercontent.com/8822552/233870377-9d8a11ec-705e-4313-bfd2-70b60f3cf065.png)

ESP3D does not control any fan so use this temperature as reference is not really useful

**Comment by ansonl** [comment]
Thank you for the info. That answered my question!
