### ISSUE TITLE
How to upload to SD card in ESP3D 3.0?

### ISSUE THREAD

**Issue by Stephano2000** [luc-github/ESP8266#924]
It has been some time since i haven't used ESP3D and Marlin, so i might have oddly forgotten some basics.
ESP3D 3.0
Ramps board + 12864 LCD controller with SD card
ESP3D web interface shows the contents of the SD card along with run and delete buttons. However there is no upload button. The dropdown menu shows only refresh.
I remember i used to upload to the SD card, but this could have been on ESP3D 2.x.
I have uncommented BINARY_FILE_TRANSFER.

Any pointers?
Thank you

**Comment by luc-github** [comment]
Supported SD modes in V3 are described here : http://esp3d.io/esp3d/v3.x/documentation/sdtransfer/index.html
and status is here : https://github.com/luc-github/ESP3D/discussions/540#discussioncomment-2897564

```
UPLOAD_SERIAL_SD (implemented in 2.1 but not more available in 3.0)
M28/M29 protocol is too slow and buggy with external queries
``` 

The M28/M29 protocol support has been dropped in V3
