### ISSUE TITLE
[FEATURE REQUEST]<Please add Pause/Resume and STOP button>

### ISSUE THREAD

**Issue by j-snijder** [luc-github/ESP8266#927]
**Is your feature request related to a problem? Please describe.**

Missing Pause/Resume and STOP button on web interface>

**Please add Pause/Resume and STOP button**

When push pause, printing pause, on push Resume it resumes
When Push STOP printer goes to immediate stop of print and cooles down

**Describe alternatives you've considered**

Alternative could be to add a clear instruction on how to add custom buttons that actually communicate with the printer.

**Additional context**

**Comment by luc-github** [comment]
This feature is implemented in V3 - did you tried it ?
on 2.1 you can add it to macro buttons according your printer

**Comment by j-snijder** [comment]
Hi,

I have a Zonestar Z9V5 with WiFi and your ESP fw on it.
Macro function is there but command is not recognized by Marlin fw on printer, although M25 and M24 are Marlin codes.

I target the ESP as the choice of 3 target (ESP - URI or SD) But is that the right target ?

**Comment by luc-github** [comment]
what FW version are you using?

**Comment by j-snijder** [comment]
FW version: 2.1.0.c26 ESP8266/8586
WebUI version: 2.1b70

copied this from info screen of ESP

**Comment by luc-github** [comment]
2.1 you need to create file with commands inside the file stored on ESP Filesystem or SD

**Comment by j-snijder** [comment]
The web UI has an option for fw update, how to do it and where to find file ?

**Comment by j-snijder** [comment]
<html>
<body>
<div class="modal-header" style="box-sizing: border-box; padding: 2px 16px; color: rgb(15, 15, 15); background-color: rgb(242, 242, 242); border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom: 1px solid rgb(207, 207, 207); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 24px;"><div class="modal-title" id="fw_update_dlg_title" translate="" english_content="ESP3D Firmware Update" style="box-sizing: border-box;">ESP3D Firmware Update</div></h3></div><div class="modal-body" style="box-sizing: border-box; padding: 10px 16px; color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Select fileNo file chosen | Select file | No file chosen |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
Select file | No file chosen

</div>
</body>
</html>

**Comment by luc-github** [comment]
>The web UI has an option for fw update, how to do it and where to find file ?

you need to build the binary by yourself

**Comment by j-snijder** [comment]
OKay, not for me then, am not into that kitchen skills

**Comment by luc-github** [comment]
Have a look to https://esp3d.io/ it is not that hard if you use platformio - I have setup everything

**Comment by j-snijder** [comment]
Can you then give me an example of the file I need to create on SD or upload to the ESP to get me a pause button and a resume button ?

All else what I need I can then add later

**Comment by luc-github** [comment]
just a file with the gcode pause command / resume command  - if you are using Marlin 
Pause : https://marlinfw.org/docs/gcode/M025.html
Restart: https://marlinfw.org/docs/gcode/M024.html
Stop: https://marlinfw.org/docs/gcode/M524.html

One file for each command / macro

**Comment by luc-github** [comment]
As no new feature come to 2.X and this feature is already present in 3.0 I close FR
