### ISSUE TITLE
[Question]<ESP32CAM doesn't work with [ESP201]>

### ISSUE THREAD

**Issue by Salvatore805** [luc-github/ESP8266#937]
**ESP32CAM doesn't work with [ESP201]**

i'm trying to make screenshot in cura with the Command [ESP201]P0 V1 but the terminal answer is "error: Missing pin".
how i can solve?

**Comment by luc-github** [comment]
[ESP171] not  [ESP201]
http://esp3d.io/esp3d/v3.x/documentation/commands/index.html

**Comment by Salvatore805** [comment]
I mean that fromCURA I want to send a GCODE command that allows me to take a picture and save it in the SD memory of the ESP32CAM

**Comment by luc-github** [comment]
read my comment and read the link I gave it answer you question

**Comment by Salvatore805** [comment]
yes i try but this is the result
![Screenshot 2023-08-04 004904](https://github.com/luc-github/ESP3D/assets/141319509/77b62630-6406-4169-bf0c-613da29ac337)

**Comment by luc-github** [comment]
are you trolling ? did you read the command I gave you ? why use ESP701 ?

**Comment by Salvatore805** [comment]
sorry, my translator changed the command. now sending this [esp171] the terminal tells me that the snapshot has been taken but I can't see it saved in the SD
