### ISSUE TITLE
[BUG] platformio.ini env:esp01s_160mhz] has a typo in the platform setting causing build to fail

### ISSUE THREAD

**Issue by andy-spoo** [luc-github/ESP8266#940]
**Describe the bug**

**To Reproduce**

1. Select Visual Studio Code as the build environment.
2. Load V3 of ESP3D
3. Go to the Platformio section.
4. Select esp01s_160mhz as the build environment.
5. Build fails.

**Expected behaviour**

It should compile.

**EASY FIX**
Original code:-   platform = espressif8266@@4.1.0
Needs to have an '@' removed, so it reads platform = espressif8266@4.1.0

**Comment by luc-github** [comment]
Indeed this typo is present since february and it is not seen by CI because it only test the esp8266 env not all 
Fixed in  https://github.com/luc-github/ESP3D/commit/7427f696b42f99352d9a07aa4ca4db2ba302dfdd

**Comment by andyspoo** [comment]
It did make me feel like perhaps I am the only one using this board :-)

**Comment by luc-github** [comment]
Well several people use esp32 / ESP12 or esp01 but with 4MB to have the webupdate
There are  less and less true ESP01 used now I think, and these ones still use ESP3D 2.X because  ESP01M is not easy to update
