### ISSUE TITLE
[BUG] Terminal says`echo : Unknown command : "ek"`

### ISSUE THREAD

**Issue by Electrocat01** [luc-github/ESP8266#944]
**Describe the bug**

When I connect my printer (Alfawise U30 Pro) to the esp board, the terminal of ESP3D says `echo : Unknown command : "ek"` indefinitely. I am able to see the printer info (M115) displayed at the startup, but the commands I send are not interpreted by the printer.

**To Reproduce**

1. Connect the printer to the esp board.
2. Just look at the terminal on the main page.

**Expected behavior**

Just the startup info of the printer displayed in the terminal and the commands to be interpreted by the printer.

**Screenshots**

<img width="318" alt="image" src="https://github.com/luc-github/ESP3D/assets/77637516/c998196a-be1c-450a-9a50-49431aefcdd2">

**ESP3D Firmware:**

- ESP3D FW version: Tested on 2 versions : Latest 2.1.x & latest on 3.0 branches.
- ESP3D-WebUI Version: For 2.1.x : the latest found in the esp3d/data folder ; for 3.0 the latest found in the dist folder of the ESP3D-WEBUI repo.
- Wifi mode: STA
- Flash method: PlatformIO
- Any change done in FW: None

**Target Firmware:**

- Name: Marlin
- Version 1.1.9

**Board used:**

Tested on 2 boards : 
1. 
  - MCU: ESP8266
  - Name: ESP8266-01
  - Flash size: 1M

2. 
  - MCU: ESP32-D0WDQ6 (revision v1.0)
  - MCU Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
  - Name: ESP32 Dev Module
  - Flash size: 4M
  - Crystal: 40MHz

**Additional context**

- Wiring : 2 wires connected to the CHR340 Chip oh the mainboard of my printer.

**Comment by luc-github** [comment]
1 - first look like you have some noise on serial `ek` vs `ok`  is not good
2 - may I know what setting do you have in webui for boot delay ?
![image](https://github.com/luc-github/ESP3D/assets/8822552/bbefb801-fdbb-42a5-9097-c4eb1d5daf74)

**Comment by Electrocat01** [comment]
Update : The problem is solved, it was a problem with the mainboard of my printer.
It was that a pin was somehow connected to another with some dust or something like that.

Sorry for the useless issue!
