### ISSUE TITLE
[Question]<How to use ESP3D with the MCP23017 component in the components/expander/io_expander/mcp23017 directory?>

### ISSUE THREAD

**Issue by liu2-3zhi** [luc-github/ESP8266#946]
How to use ESP3D with the MCP23017 component in the components/expander/io_expander/mcp23017 directory? https://github.com/espressif/esp-iot-solution/tree/d7f413d058e7acbc1832305c65d211ee13fd952d/components/expander/io_expander/mcp23017

**Comment by liu2-3zhi** [comment]
Please forgive my desire, I want to enable all features, including Ethernet, camera, buzzer, and so on. The number of I/O has prevented this behavior.

**Comment by luc-github** [comment]
I am not sure because I never needed to code ioexpander but for arduino I guess you can use this arduino library https://www.arduino.cc/reference/en/libraries/mcp23017/
