### ISSUE TITLE
[FEATURE REQUEST]🦄Change ESP_DIRECT_SD to ESP_NOT_SHARED_SD for consistency

### ISSUE THREAD

**Issue by luc-github** [luc-github/ESP8266#955]
in configuration.h
```
/* SD card connection
* ESP_NO_SD //(default)
* ESP_DIRECT_SD //Only your ESP board is connected to SDCard
* ESP_SHARED_SD //Printer SD Card is also connected to ESP3D
* Does your system has SD card and how it is connected to your ESP3D
*/
```
ESP_DIRECT_SD seems confusing for users and is often used when ESP_SHARED_SD should be used, the configurator must be updated also

**Comment by tjeerdvandijk** [comment]
Agreed, im trying to figure out what it means. 

currently it says `Your system has SD card and your ESP is connected to it using shared solution`

What exactly is a shared solution? Does it simply mean the printer has a sd card? and we do not have to connect anything to the esp?

**Comment by Sergey3112** [comment]
Как сделать, чтоб вообще видело SD карту?

**Comment by luc-github** [comment]
Configurator and Documentation have been updated also
