### ISSUE TITLE
[BUG] FTP not showing full directory listings on SD storage on Fysetc SD-WIFI-PRO

### ISSUE THREAD

**Issue by y2kdread** [luc-github/ESP8266#957]
**Describe the bug**

When I access esp3d through FTP, I am unable to list the full list of files/directories on the SD portion of the storage.

**To Reproduce**

1. Connect to FTP using FTP client
2. Browse to the "SD" folder
3. Full list of files/folders are not shown

**Expected behavior**

I should be able to see all files and directories on the SD card

**Screenshots**

[https://imgur.com/YGLZEmg](url)
[https://imgur.com/0UFANrS](url)

**ESP3D Firmware:**

- ESP3D FW version: 3.0.0.a225
- ESP3D-WebUI Version: 3.0.0-a40.M2.1
- Wifi mode: Client Mode
- Flash method: PlatformIO

**Board used (please complete the following information):**

- MCU: ESP32
- Name: Fysetc SD-WIFI-Pro
- Flash size: 8M

**Comment by luc-github** [comment]
Did you configured your ftp client properly for esp3d ? 

https://esp3d.io/esp3d/v3.x/documentation/ftp/index.html

![image](https://github.com/luc-github/ESP3D/assets/8822552/16d5e16b-3e9c-4ce0-bf61-8f17c244e391)

**Comment by luc-github** [comment]
I cannot duplicate your issue using the setting as above
![image](https://github.com/luc-github/ESP3D/assets/8822552/97b1b6c5-1914-4eaa-9d71-d427a1b3f9c8)

**Comment by y2kdread** [comment]
That setting was incorrect in FileZilla, but I am still seeing the same thing with it set to only 1 connection.


![Screenshot 2023-10-25 131150](https://github.com/luc-github/ESP3D/assets/52291071/797c60cc-197f-41e2-8173-deb721a47b9e)

**Comment by luc-github** [comment]
this issue is different than webdav one ? even on limited number of file you have issue ?

**Comment by y2kdread** [comment]
It is on the entire SD file system, I don't see any of the files or folders in the root apart from the "System Volume Information"

I have a feeling it may be related, but it is just a hunch.

**Comment by luc-github** [comment]
looks like more the fat file system is corrupted in that case 
like not clean eject from pc

**Comment by y2kdread** [comment]
I've actually tried testing this out by performing a full reflash of ESP and formatting the card with the SD formatting tool. I can try again just to be safe.

**Comment by luc-github** [comment]
after formating the SD how did you uploaded files  ?

**Comment by y2kdread** [comment]
I just copied the data from the original SD card.

**Comment by luc-github** [comment]
my question was : HOW ?
Windows File manager ?
Your OS file manager ?
WebDav ?
FTP?
your  CPAP machine ?

**Comment by y2kdread** [comment]
Oh ok. 

I copied using Windows file explorer from the original card to the esp card.

**Comment by luc-github** [comment]
I did same and I reproduce your issue 
![image](https://github.com/luc-github/ESP3D/assets/8822552/e8248ddf-2141-4f7c-8030-d7fac01ccb6d)
which is weird is that webdav is able to see the content 
![image](https://github.com/luc-github/ESP3D/assets/8822552/46ffab7a-3f6b-47a5-8866-e68a819deb2d)
So it is not question of SD formating but another issue in code for sure
It has been years that I did not looked at this part of code, so I will dig in 😓

**Comment by luc-github** [comment]
Ok I am solving the bug - looks like the SD access was not well handled and sometimes even handled upside down...
So only first file/dir was listed on SD, no issue on FS because the FS is never released.

Listing 1000 files take around 4min in debug mode but so far it is working on my devt branch - I will continue to to review ftp code today and push the fix if no blocking point

**Comment by luc-github** [comment]
Fix is now available - please give a try

**Comment by y2kdread** [comment]
The fix you put in place resolved the issue. Thanks a ton!
