### ISSUE TITLE
[BUG]Pull request #960 generate a compiling error with activated CAMERA_DEVICE = CAMERA_MODEL_AI_THINKER

### ISSUE THREAD

**Issue by DivingDuck** [luc-github/ESP8266#963]
**Describe the bug**

Last code update from pull request #960 generates a compiler error when a camera modul is activated (in my case `CAMERA_DEVICE = CAMERA_MODEL_AI_THINKER`)

Error:

Involved files:
configuration.h, line 493
camera.cpp, line 81

```
**'HTTP_Server' has not been declared
name followed by '::' must be a class or namespace name**
```

**To Reproduce**

Activate ` CAMERA_DEVICE = CAMERA_MODEL_AI_THINKER` in configuration.h, line 493

**Expected behavior**

n/a, compiling w/o error

**Screenshots**

![ESP3D_issue#963](https://github.com/luc-github/ESP3D/assets/8143022/33fcb70e-7be4-4e1a-a1b2-7040b7f5b64e)

**ESP3D Firmware:**

- ESP3D FW version: 3.0.0.a225
- ESP3D-WebUI Version: 3.0.0-a42S2
- Wifi mode: STA
- Flash method: OTA
   Build with VSC and PlatformIO:

- Any change done in FW:
  see configuration.h in attachment

**Target Firmware:**

- Name: Smoothieware

**Board used (please complete the following information):**

- MCU: ESP32
- Name: ESP32CAM
- Flash size: 4M

**Additional context**

Up to last update ESP3D was compiling fine.
Turning camera.cpp, line 81 into a comment line will compile the firmware.
After uploading the new firmware I recognize in -->Settings --> Features a error message `parsing data error, data are incorrect`

Attachment:

[ESP3D-Issue#963.zip](https://github.com/luc-github/ESP3D/files/13302739/ESP3D-Issue.963.zip)

Edit: forgot attachment...

**Comment by luc-github** [comment]
Indeed this case did not go thrue the CI test and I forget to add the corresponding header, thank you for raising the issue - it is now fixed https://github.com/luc-github/ESP3D/commit/265e0e60a2ebb3ff1883c898de83210027f4cbf1
