### ISSUE TITLE
Add "Flip horizontally" for camera settings

### ISSUE THREAD

**Issue by DivingDuck** [luc-github/ESP8266#965]
**Feature request**

Is it maybe possible to add Flip horizontally to configuration.h some time in the future? I do add this often after an update manually and like to ask for adding the lines below:

```
/* Flip horizontally
* Flip camera horizontally
*/
//#define CAMERA_DEVICE_FLIP_HORIZONTALY
```
![ESP3DFlippHorizontally_FR](https://github.com/luc-github/ESP3D/assets/8143022/430879fb-6047-4431-bc5d-dae1978c1039)

It would be also great having the controlls available in [Settings/Interface/Extra content Panel] or better(?) in [Dashboard/Camera Panel] as well so that it is possible to flip the view horizontal or vertical while running ESP3D-WebUI.

![ESP3DFlippHorizontally_FR1](https://github.com/luc-github/ESP3D/assets/8143022/e9b8607e-3b2e-426b-9153-c375ca321c5b)![ESP3DFlippHorizontally_FR2](https://github.com/luc-github/ESP3D/assets/8143022/c176b2bb-250f-40dd-9957-d3303a116812)

Not important but nice to have if needed.

Best regards,
DD

**Comment by luc-github** [comment]
actually the define is already in the configurator :
![image](https://github.com/luc-github/ESP3D/assets/8822552/80fad358-ffa6-4410-b2b0-8e94f0094084)

I may missed to add the line in default configuration.h I will add it
Edit: updated

About the extra buttons - I would like to avoid to add such button that will almost be never used used - on other hand you can add them by yourself in Macro panel using the [ESP170] command

**Comment by DivingDuck** [comment]
This is a good idea too. Thanks for pointing me to it.

**Comment by luc-github** [comment]
Another possible solution if you want to play, is to do a little extension that has the display of camera,  do the refresh  and all buttons you need : https://esp3d.io/esp3d-webui/v3.x/documentation/api/extensions/index.html

then add it as new panel of page

**Comment by DivingDuck** [comment]
Hey, new playground...
I will see how this works for me some time later today (hopefully) as I need to do some day work now. I will come back as soon had the time playing a bit with extensions (what I didn't before) :)

Again, thanks a lot

Btw, you can close the issue if you want. I updated my source file already and the rest I got managed with your hints. If not, I will come back and ask for help.

**Comment by luc-github** [comment]
Sure 😺  have fun ^_^
