### ISSUE TITLE
[Question] [ESP3D v3] Hide print status responses

### ISSUE THREAD

**Issue by dbuezas** [luc-github/ESP8266#972]
I'm polling `M27 S0` to so the print status pane is kept up to date, but unsetting verbose mode in the console doesn't hide these:

```log
Not SD printing
Not SD printing
Not SD printing
```

```log
SD printing byte 1875/6643274
```

Is there any way to hide them from the console the same way that temperature reports are hidden ?

**Comment by luc-github** [comment]
need to add them to the list here : https://github.com/luc-github/ESP3D-WEBUI/blob/3.0/src/targets/Printer3D/Marlin/stream.js#L23-L36
