### ISSUE TITLE
[Question] [ESP3D v3] Hide notifications

### ISSUE THREAD

**Issue by dbuezas** [luc-github/ESP8266#973]
Is there any way to not display these notifications? 

<img width="736" alt="image" src="https://github.com/luc-github/ESP3D/assets/777196/aa101e1b-c956-4ca0-a792-a75894464a55">

It seems like these aren't hidden if the tab is not in the foreground for a while so they also accumulate.

**Comment by luc-github** [comment]
they should hide after a while
but I think they are meaningless they should not be send if they are using HOMEASSITANT I think
same for display:
Check here :
https://github.com/luc-github/ESP3D/blob/3.0/esp3d/src/modules/notifications/notifications_service.cpp#L188-L196

**Comment by dbuezas** [comment]
It looks like there is a bug on top of that. If I leave the tab in the background they accumulate and only the last one is removed:
<img width="1091" alt="image" src="https://github.com/luc-github/ESP3D/assets/777196/bab16b1f-8951-47fe-8245-c52d567bf376">

**Comment by luc-github** [comment]
what do you mean by `tab in background` ?

**Comment by dbuezas** [comment]
For example if you have 2 tabs open in your browser, one is ESP3D and the other is youtube, but you are watching youtube so the ESP3d is "in the background", or inactive

**Comment by dbuezas** [comment]
I opened a PR https://github.com/luc-github/ESP3D-WEBUI/pull/375
