### ISSUE TITLE
[BUG]Baudrate not updating

### ISSUE THREAD

**Issue by dbuezas** [luc-github/ESP8266#975]
**Describe the bug**

I set it to 500000, saved and restarted
<img width="326" alt="image" src="https://github.com/luc-github/ESP3D/assets/777196/ceb53397-28cc-4fd6-acff-1c3304c1ca7d">

**To Reproduce**

1. Go to UI
2. Increase to 500000
3. Save, restart

**ESP3D Firmware:**

- ESP3D FW version: v3/Refactoring-internal-clients/c7957a2fe1068446fdbab6302314e3a1f155ef32
- ESP3D-WebUI Version: v3
- Wifi mode: Client
- Flash method: PlatformIO] 
- Any change done in FW:

**Board used (please complete the following information):**

- MCU: ESP8266 ESP-12s
- Name: BTT wifi board
- Flash size: 4MB

**Additional context**

It also doesn't actually change the baud rate, it stays at 115200

**Comment by luc-github** [comment]
I will have a look today, I can duplicate issue
It seems change is well applied but not reflected even chacking with [ESP901]
so issue is in FW definitly - change fully ok if only use [ESP901] so issue should be in [ESP401]

**Comment by luc-github** [comment]
Fixed - had 2 issues actually : wrong validation Fn (bad copy and paste when did the rewrite) and the error of not saving was not raised 

Thank you for rasing it ^_^
