### ISSUE TITLE
[Question]What is the boot sequence delay for?

### ISSUE THREAD

**Issue by dbuezas** [luc-github/ESP8266#976]
I set it to zero so the board starts up faster. What is it good for?
<img width="327" alt="image" src="https://github.com/luc-github/ESP3D/assets/777196/6634c1b9-376e-44cc-ac0a-3bd0b56a15b9">

**Comment by luc-github** [comment]
it is usefull for boards which start slower than ESP3D, it avoid to overload their serial buffer with ESP3D commands / message. it allow to display the IP on printer screen on time, etc... it really depend on what board is connected to ESP3D
