### ISSUE TITLE
[Question] ESP3D vs Marlin port config

### ISSUE THREAD

**Issue by albertovm** [luc-github/ESP8266#979]
I have a Biqu B1 and my ESP01 is connected to serial located in its TFT display.
Anybody knows if I need to enable any specific port in Marlin to ESP01 communicate with the printer?
ESP01 is starting up and I am able to connect the website, but ESP3D do not find any printer, and the printer do not find the ESP3D.
Thanks!

**Comment by luc-github** [comment]
if your ESP is connected to TFT Marlin does not need any configuration unless your TFT has no FW , but in that case you need to check the pinout of Serial and what serial is related in Marlin
