### ISSUE TITLE
[Question]<How to compile esp3d 3.0>

### ISSUE THREAD

**Issue by ravazzz** [luc-github/ESP8266#981]
Hi, can you explain how to compile esp3d 3.0? I am using arduino IDE to compile but it give me always error 

**In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP104.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP104.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP110.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP110.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3doutput.h:49:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3doutput.cpp:21:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3doutput.h:49,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3doutput.cpp:21:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP102.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP102.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP108.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP108.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\benchmark.cpp:21:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\benchmark.cpp:21:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\modules\authentication\authentication_service.h:34:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\commands.h:25,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\commands.cpp:21:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\modules\authentication\authentication_service.h:34,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\commands.h:25,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\commands.cpp:21:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP103.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP103.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP107.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP107.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP101.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP101.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP106.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP106.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3d_string.cpp:24:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3d_string.cpp:24:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP105.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP105.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP0.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP0.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP100.cpp:20:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP100.cpp:20:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3d.cpp:29:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3d.cpp:29:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3d.cpp: In member function 'bool Esp3D::begin()':
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3d.cpp:106:29: error: 'ESP_SERIAL_OUTPUT' was not declared in this scope
   if (!serial_service.begin(ESP_SERIAL_OUTPUT)) {
                             ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3d.cpp: In member function 'void Esp3D::restart_now()':
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\esp3d.cpp:241:26: error: 'ESP_SERIAL_OUTPUT' was not declared in this scope
     serial_service.begin(ESP_SERIAL_OUTPUT);
                          ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP111.cpp:21:0:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:38:2: error: #error "No configuration file found"
 #error "No configuration file found"
  ^
In file included from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\esp3d_config.h:46:0,
                 from C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\core\espcmd\ESP111.cpp:21:
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:33:2: error: #error Choose Preferences or EEPROM for settings
 #error Choose Preferences or EEPROM for settings
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:54:2: error: #error ESP_SERIAL_OUTPUT must be defined
 #error ESP_SERIAL_OUTPUT must be defined
  ^
C:\Users\Gian\Desktop\ESP3D-3.0\esp3d\src\include\sanity_esp3d.h:64:2: error: #error Serial 2 is not available in ESP8266
 #error Serial 2 is not available in ESP8266
  ^

exit status 1

Compilation error: #error "No configuration file found"**

Where can i find the complete ino? I have added configuration.h inside the folder of esp3d but it doesn't compile.

**Comment by luc-github** [comment]
everything is here : https://esp3d.io/esp3d/v3.x/installation/index.html
