### ISSUE TITLE
[BUG] No IP Address on LCD/TFT of printer 

### ISSUE THREAD

**Issue by firepower9966** [luc-github/ESP8266#986]
**Describe the bug**

No IP Address shown on LCD / TFT of printer in STA Mode. 
When in AP Mode it shows IP address and status messages.

Turn on or reset 3D Printer does not show IP address when connects in STA mode.

Display IP address on start up

**Screenshots**

**ESP3D Firmware:**

- ESP3D FW version:  FW: 2.1.3b0
- ESP3D-WebUI Version: UI: 2.1b77
- Wifi mode: STA
- Flash method: [PlatformIO]  Have used both, Arduino IDE 2.2.1 {to set FS size and full erase when got json error}
    If you build with Arduino:
    - Arduino ESP8266 package version: [e.g. 2.5.2] 
Generic ESP8266 

**Target Firmware:**
Marlin bugfix-2.1.x (Jan  1 2024 23:40:20)

**Board used (please complete the following information):**

- MCU:[ESP8266 ESP12S]
- Name:[MKS Wifi]
- Flash size: [4M: 2M/2M]

**Additional context**
I previously had IP address shown using ESP8266 D1 mini and ramps 1,4 Atmega2560 with LCD 12864 / LCD 2004
I am now using MKS Wifi with MKS Robin Nano V3,1 and TS35 V2,0 but no IP address, but everything else works fine
have tried with and without  #define DISABLE_CONNECTING_MSG
have tried changing Delay esp3d.h and still not IP, using 12s as it allows it to start and show firmware boot message in console of ESP3D.

[esp3d.zip](https://github.com/luc-github/ESP3D/files/13805635/esp3d.zip)

**Comment by luc-github** [comment]
Does the IP appear on TFT if you do an `[ESP444]RESTART` in webui terminal ?
What is the zip file for ?

**Comment by firepower9966** [comment]
Zip File contains my config.h and esp3d.h so you can check my setting.

**Comment by luc-github** [comment]
![image](https://github.com/luc-github/ESP3D/assets/8822552/cb3b12e4-9126-4284-8edc-bcd358ed0423)
no you put wrong file, you put config.cpp not .h

**Comment by firepower9966** [comment]
here correct file. 
[esp3d.zip](https://github.com/luc-github/ESP3D/files/13808517/esp3d.zip)

**Comment by luc-github** [comment]
Does the IP appear on TFT if you do an [ESP444]RESTART in webui terminal ?

**Comment by firepower9966** [comment]
I currently printing , I will update later in about half an hour to complete print.

**Comment by luc-github** [comment]
also does any command work from WEBUI to monitor / control printer ?

**Comment by firepower9966** [comment]
[ESP444]RESTART  show disconnected on TFT
even when reconnects and i read sdcard or send command.
all commands work , gcode, mcode and [ESPcodes]
I can homee, set and monitor temp, fan, read and upload and print from sdcard/
everything seems to work ok , just no ip address on start up or reset
I can send text to TFT using M117 from ESP3D console of webui

**Comment by luc-github** [comment]
does `[ESP111]M117`  display the IP ?

**Comment by firepower9966** [comment]
Only in Webui console
[ESP111]M117
M117192.168.1.11
I have already tried to do same as custom command sent from printer, but not display 

#define CONFIG_MENU_ITEM_1_DESC "Wifi IP ?"
 #define CONFIG_MENU_ITEM_1_GCODE "M118 [ESP111]"

and even adding M117 but no display on TFT  but shows IP on console or/and echo:Unknown command: in webui console.

**Comment by luc-github** [comment]
what about : `M117 192.168.1.11` from webUI terminal

**Comment by firepower9966** [comment]
Yes that displays 192.168.1.1 on TFT
M117 works from console no problem.

**Comment by firepower9966** [comment]
would adding space character before IP address allow M117 to show IP
[ESP111]M117
M117192.168.1.11 change to this  M117 192.168.1.1

**Comment by luc-github** [comment]
yes you can add space to end
 `[ESP111]M117 `

**Comment by firepower9966** [comment]
that shows in console 
[ESP111]M117
M117192.168.1.11

and no IP on TFT/LCD

**Comment by firepower9966** [comment]
I like to get IP to show on LCD, but if it cant its ok, I can get IP from router if neeeded, and DHCP saves it for a time also.

Also it shows IP in AP when doing fiirst setup to upload index.html.gz

I dont want to give you head ache from this or waste your time, 
I happy to test to get it to work but but if it cant it no great problem. 
ESP3D works fine and the MKS file transfer is great compared to the glacial slow transfer of standard serial wifi. 
I mainly just use to send console commands when configuring options for marlin firmware updates.

**Comment by luc-github** [comment]
I am checking  on it because the code is very old, I am adding possible solution now, 2.1 use HK wifi method not serial solution for emulating MKS WiFi module so I may missed that in 2.1

but I do not understand :
> ESP3D works fine and the MKS file transfer is great compared to the glacial slow transfer of standard serial wifi.

ESP3D 2.1 does not support MKS file transfert only ESP3D 3.0 so I do not understand : how can you have fast file transfert on 2.1 ?

**Comment by firepower9966** [comment]
Its seems to work you have the option in config.h 
//MKS TFT WIFI support see Wiki for wiring
#define MKS_TFT_FEATURE

I can not get ESP3D 3.0 to work no wifi comms have tried twice,but ESP3D 2,0 work well

what the main differences of 2.1 vs 3.0 ?

**Comment by luc-github** [comment]
`MKS_TFT_FEATURE` just allow MKS TFT to get IP in settings and so make the communication active, it does not do anything on file upload

3.0 is a complete rewrite and has native support of MKS WIFI

**Comment by luc-github** [comment]
I think it is fixed now I have tested with your config

**Comment by firepower9966** [comment]
Maybe it just placebo , lol
I use USB stick for transfer as my PC is next to my printer.

**Comment by firepower9966** [comment]
I will reflash firmware with MKS TFT WIFI  disabled. maybe thats the issue
//MKS TFT WIFI support see Wiki for wiring
//#define MKS_TFT_FEATURE

**Comment by luc-github** [comment]
if you do this the TFT may think there is not WIFI module, just download the FW on git I have already pushed the fix
https://github.com/luc-github/ESP3D/commit/460a145a91588f7451fe7016b8db6c0a67758b4c

**Comment by firepower9966** [comment]
Thats it now see IP 
now shows 
Wifi ssid 
disconnect 
IP

**Comment by firepower9966** [comment]
MY wifi in on mainboard 
I will update to latest 2.1 ?

**Comment by luc-github** [comment]
yes or change the code I have linked to esp3d.cpp

**Comment by firepower9966** [comment]
Working OK
see IP on TFT
Thank you for you help fixing this.
very happy.

**Comment by luc-github** [comment]
cool thank you for reporting it 😺

**Comment by luc-github** [comment]
I close issue then

**Comment by firepower9966** [comment]
yes thank you.

**Comment by luc-github** [comment]
for more info you can check here : https://esp3d.io/esp3d/v3.x/index.html
