### ISSUE TITLE
Got error "connection with board is lost" and  "websocket connection error"

### ISSUE THREAD

**Issue by dialdhruv** [luc-github/ESP8266#996]
Bundrate is 250000
ESP3D-WEBUI-3.0.0-alpha3
ESP3D-3.0.0-alpha3

using Webui \ESP3D-WEBUI-3.0.0-alpha3\server\Printer3D\Marlin\Flash

When I load the page it works properly for 2-3 seconds then after it shows the below error.

![WhatsApp Image 2024-02-04 at 21 58 04_d5cab3d2](https://github.com/luc-github/ESP3D/assets/53616289/6dde5dac-7830-4611-81e7-93592248abf2)

![WhatsApp Image 2024-02-04 at 21 58 04_e386b4d4](https://github.com/luc-github/ESP3D/assets/53616289/ee698f64-b2f7-46d1-9a6e-4811c37c0978)

**I have tried with firmware 2.X and it is working fine for me. No any issue was found with 2.X firmware version**

**Comment by luc-github** [comment]
the webui and fw are not sync , which mean  one of then is not alpha3
please use latest git version for both it should be ok

**Comment by dialdhruv** [comment]
> Thank your for submiting, please be sure you followed template or your issue may be dismissed. if you deleted the template it is [here](https://github.com/luc-github/ESP3D/blob/2.1.x/.github/ISSUE_TEMPLATE/bug-report---problem.md)

I did not understand template. Are you talking about webui?
Webui and firmware version both 3.0.0-alpha3

**Comment by dialdhruv** [comment]
> the webui and fw are not sync , which mean one of then is not alpha3 please use latest git version for both it should be ok

I have download both from github release and both version is template 3.0.0-alpha3

**Comment by luc-github** [comment]
I mentionned git version - not release 

![image](https://github.com/luc-github/ESP3D/assets/8822552/b7041e73-c8f5-41eb-b748-abae8d0b0bff)

Git version is more updated

**Comment by luc-github** [comment]
I close issue as cannot duplicate on git version

**Comment by luc-github** [comment]
I have also tested with https://github.com/luc-github/ESP3D/tree/v3.0.0-alpha3 and https://github.com/luc-github/ESP3D-WEBUI/tree/v3.0.0-alpha3 and cannot duplicate
